/** PostgreSQL registry data — high availability topics */
import { q } from './_postgresqlRegistryData.part1.mjs';

export const PART5 = [
  { topic: 'high-availability', file: 'highAvailability.js', questions: [
    q('pg-high-availability-1','high-availability','highAvailability.js','easy','Very Common','DBA',
      'What are the core components of PostgreSQL high availability?',
      { interview:'Primary-replica streaming replication for data redundancy. Automatic failover via Patroni/repmgr/Stolon with DCS (etcd/Consul). Connection routing via PgBouncer/HAProxy/VIP. WAL archiving for PITR. Monitoring replication lag, slot health, and leader status. Quorum sync for RPO zero when required.',
        explanation:'HA stack: app → pooler → Patroni-managed nodes → etcd quorum. Load balancer health checks read-only vs primary. Watchdog/fencing prevents split-brain. Backup independent of HA for logical errors. Multi-AZ placement for AZ failure tolerance.',
        production:'Patroni + etcd 3-node cluster on K8s, PgBouncer service, sync rep to 2 replicas in different AZs. Quarterly failover drill RTO 45s measured.',
        followUps:['Patroni vs repmgr vs manual?','etcd quorum sizing?','HA without automatic failover acceptable when?','Aurora HA vs Patroni?'],
        mistakes:['Two nodes only for etcd — no quorum','HAProxy without read/write split sending writes to replica','No fencing on old primary after failover','Treating read replica as DR without promotion test'],
        seniorInsights:'Draw full stack diagram in interview — pooler, DCS, sync/async tiers, backup side channel.',
        commands:['patronictl list','SELECT * FROM pg_stat_replication;','curl http://etcd:2379/v2/keys/patroni/leader'],
        bestPractices:['Odd-number etcd cluster for quorum','Automate failover with fencing','Separate read and write endpoints in app config','Quarterly failover and PITR drills'] }),
    q('pg-high-availability-2','high-availability','highAvailability.js','medium','Common','Cloud Engineer',
      'Design multi-AZ PostgreSQL HA on Kubernetes with Patroni operator.',
      { interview:'Zalando Postgres Operator or CrunchyData PGO deploys Patroni StatefulSets across AZs. Pod anti-affinity spreads replicas. PersistentVolume per pod on fast storage. Services: primary (-rw) and replica (-ro). Sync rep via Patroni synchronous_mode or native sync_standby_names.',
        explanation:'Operator handles failover, backup sidecars (WAL-G), connection pooling optional PgBouncer sidecar. etcd as Patroni DCS or Kubernetes endpoints. Upgrades: rolling pod restart. Monitor via Prometheus postgres_exporter. Network policies restrict replication traffic.',
        production:'GKE 3-AZ Patroni cluster, 1 primary 2 sync replicas, PgBouncer sidecar 1000 app connections → 30 PG connections. Failover tested via pod delete — 38s leader election.',
        followUps:['Local PV vs network storage for PG on K8s?','Operator upgrade strategy?','Cross-cluster DR on K8s?','Resource limits for PostgreSQL pods?'],
        mistakes:['Single AZ node pool — defeats multi-AZ','Shared RWO volume across pods','No podDisruptionBudget — voluntary eviction causes outage','Under-provisioned etcd on same nodes as PG'],
        seniorInsights:'K8s PG HA answer must mention storage class IOPS and anti-affinity — not just Patroni logo.',
        commands:['kubectl get postgresql -n db','kubectl exec -it cluster-0 -- patronictl list','kubectl get pods -o wide -n db'],
        bestPractices:['Pod anti-affinity across AZs','Dedicated fast storage class for WAL/data','PodDisruptionBudget minAvailable 1 for primary','Monitor Patroni leader via Prometheus'] }),
    q('pg-high-availability-3','high-availability','highAvailability.js','medium','Very Common','Database Engineer',
      'Monitor PostgreSQL HA health: replication, lag, and leader election.',
      { interview:'Metrics: pg_stat_replication replay_lag, pg_replication_slots retained WAL, Patroni /health and /patroni endpoints, pg_is_in_recovery() on each node, connection count per role. Alerts: lag > SLO, slot inactive, no primary in DCS, split-brain detection via timeline.',
        explanation:'postgres_exporter custom queries for lag bytes. Patroni exposes REST API cluster state. Alert on synchronous_standby_names unfulfilled — commits blocking. Grafana dashboards: lag p99, connections, checkpoints, autovacuum. Synthetic write+read probe through pooler.',
        production:'Datadog monitors: replay_lag > 5s page, patroni_has_leader=0 critical, pg_wal_lsn_diff slot > 5GB warning. Reduced undetected replica failure MTTR from 45min to 3min.',
        followUps:['Lag alert threshold tuning?','False positive lag during vacuum?','Monitor etcd health separately?','CloudWatch RDS replica lag vs replay_lag?'],
        mistakes:['Only monitoring primary CPU not replica lag','No alert on missing sync standby','Patroni REST not scraped by monitoring','Treating flush_lag as user-visible lag on hot standby'],
        seniorInsights:'HA monitoring minimum: leader exists, replay_lag SLO, slot retention, sync standby count.',
        commands:['SELECT application_name, state, replay_lag, sync_state FROM pg_stat_replication;','curl -s http://patroni:8008/patroni | jq .','SELECT pg_is_in_recovery();'],
        bestPractices:['Alert on replication lag exceeding SLO','Monitor Patroni leader and member state','Track replication slot WAL retention','Synthetic transaction probes through HA endpoint'] }),
    q('pg-high-availability-4','high-availability','highAvailability.js','hard','Common','DBA',
      'Compare Patroni, repmgr, and cloud-managed HA for PostgreSQL.',
      { interview:'Patroni: DCS-based leader election, REST API, flexible, industry standard self-managed. repmgr: simpler, witness server, good for smaller deployments. RDS Multi-AZ: managed sync failover same region. Aurora: storage-layer replication, faster failover, different consistency model.',
        explanation:'Patroni supports sync rep, cascading, K8s native. repmgr less active development vs Patroni. Cloud managed trades control for ops reduction. pg_auto_failover (Microsoft) alternative with monitor node. Choose based on team skill, compliance, multi-cloud need.',
        production:'Migrated repmgr to Patroni for K8s compatibility and better REST integration. Kept RDS Multi-AZ for internal tools tier with different RTO/RPO SLA.',
        followUps:['pg_auto_failover vs Patroni?','Aurora storage vs WAL replication?','Custom HA without DCS risks?','License/support considerations?'],
        mistakes:['DIY heartbeat script without fencing in 2024','Patroni without etcd TLS in production','Assuming Aurora identical to PostgreSQL semantically','repmgr without witness on 2-node cluster'],
        seniorInsights:'Pick HA tool matching platform: Patroni for K8s/bare metal, RDS for managed tier, hybrid common at scale.',
        commands:['patronictl list','repmgr cluster show','aws rds describe-db-instances --query \'DBInstances[*].[DBInstanceIdentifier,MultiAZ]\''],
        bestPractices:['Standardize on Patroni for self-managed clusters','Use cloud managed HA for appropriate tier SLAs','Never run custom failover scripts without fencing','Document HA tool choice per environment tier'] }),
    q('pg-high-availability-5','high-availability','highAvailability.js','hard','Rare','Cloud Engineer',
      'Architect cross-region DR with RPO/RTO tiers alongside same-region HA.',
      { interview:'Same-region: sync Patroni replicas RPO 0, RTO ~60s. Cross-region: async physical replica or WAL archive to DR region RPO minutes-hours. DNS/global load balancer routes after regional failover. Application dual-write or read-only DR until promotion. Compliance data residency may restrict region.',
        explanation:'DR promotion: Patroni in DR as independent cluster restored from archive or replica lag accepted. Route53 health check fails over write endpoint. Test regional failure game-day annually. Split-brain across regions prevented by never auto-promoting both.',
        production:'US-East Patroni primary + sync replicas; US-West async replica + daily wal-g copy. Regional DR runbook promotes West replica with 15-min RPO acceptance; RTO 90 min last drill.',
        followUps:['Global database product comparison?','Cross-region sync rep latency impact?','Data residency blocking cross-region DR?','Active-active multi-region PG?'],
        mistakes:['Cross-region sync rep killing commit latency','No DR drill — West replica 7 days lag at real outage','DNS TTL too high slowing cutover','Assuming same-region HA equals regional DR'],
        seniorInsights:'Separate same-region HA (RPO 0) from cross-region DR (RPO > 0) — different architecture and cost.',
        commands:['SELECT application_name, replay_lag FROM pg_stat_replication;','pgbackrest --stanza=main info','patronictl list --role=master'],
        bestPractices:['Document distinct RPO/RTO for HA vs DR tiers','Annual cross-region failover drill','Automate WAL shipping to DR region','Keep DR runbook independent of primary tooling'] }),
  ]},
  { topic: 'failover', file: 'highAvailability.js', questions: [
    q('pg-failover-1','failover','highAvailability.js','easy','Very Common','DBA',
      'Describe manual PostgreSQL failover steps and risks.',
      { interview:'On standby: pg_ctl promote or touch trigger_file (legacy). Old primary must stop accepting writes — fence via Patroni, STONITH, or network isolation. Update application connection strings or VIP. Verify timeline, pg_stat_replication on new primary, recreate slots for remaining replicas.',
        explanation:'Unplanned promotion with lag = data loss equal to replay lag at failure. Split-brain if old primary not fenced — dual writes corrupt data. pg_rewind reintegrates old primary as replica. Synchronous rep reduces loss window. Document promotion checklist.',
        production:'Primary hardware failure — Patroni auto-promoted replica in 42s. Manual intervention only to decommission dead node. Previous manual runbook took 15 min before Patroni adoption.',
        followUps:['pg_ctl promote vs pg_promote()?','Failover vs switchover?','How much data loss with 30s replay lag?','Reintegrate old primary after failover?'],
        mistakes:['Promoting replica without stopping old primary','Not measuring lag before manual promotion','Forgetting to recreate replication slots','Applications cache old primary DNS'],
        seniorInsights:'Manual failover interview: always mention fencing old primary first — split-brain is the disaster.',
        commands:['pg_ctl promote -D $PGDATA','SELECT pg_is_in_recovery();','patronictl failover','pg_rewind --target-pgdata=$PGDATA --source-server=...'],
        bestPractices:['Automate failover with Patroni where possible','Always fence old primary before promotion','Measure replay lag before accepting manual promotion','Maintain written failover checklist'] }),
    q('pg-failover-2','failover','highAvailability.js','medium','Common','Database Engineer',
      'How does Patroni perform automatic failover and leader election?',
      { interview:'Patroni agents on each node heartbeat to DCS (etcd). Leader holds leader lock key with TTL. On primary failure, lock expires, replica acquires lock, runs postgresql promote callback, updates leader key. Other replicas reconfigure primary_conninfo to new leader. REST API exposes role.',
        explanation:'loop_wait and ttl tune failover speed vs false positives. synchronous_mode waits for sync standby before responding. callbacks: on_role_change, reload config. bootstrap initializes new cluster. Watchdog optional for split-brain on primary isolation.',
        production:'Network partition isolated primary — Patroni primary demoted itself when could not renew DCS lock; replica promoted. 35s outage. postgresql.conf managed by Patroni — manual edits overwritten.',
        followUps:['Patroni synchronous_mode vs PostgreSQL native sync?','etcd split-brain impact?','Patroni pause mode maintenance?','Custom failover scripts via callbacks?'],
        mistakes:['Editing postgresql.conf outside Patroni scope','etcd on same failed AZ as only primary','ttl too high — slow failover','No application retry on connection failure during failover'],
        seniorInsights:'Patroni failover time = ttl + promote + DNS update — know default ~30-60s.',
        commands:['patronictl list','patronictl show-config','curl http://node:8008/patroni','patronictl pause --role=master'],
        bestPractices:['Run etcd in odd quorum across AZs','Configure application connection retry with backoff','Use Patroni for config management not manual edits','Test Patroni failover in staging monthly'] }),
    q('pg-failover-3','failover','highAvailability.js','medium','Very Common','Production Support',
      'Troubleshoot split-brain and dual-primary scenarios after failover.',
      { interview:'Symptoms: writes succeed on two nodes, divergent data, replication broken both directions. Cause: old primary not fenced during promotion. Fix: stop writes on wrong primary immediately, pg_rewind or rebuild wrong node as replica, audit divergent data manually if both accepted writes.',
        explanation:'Prevention: STONITH (shutdown old primary), Patroni DCS lock, load balancer health check only on DCS leader, iptables/cloud API isolate. Detection: compare pg_current_wal_lsn and timelines on suspected nodes. Never merge divergent PostgreSQL writes automatically.',
        production:'Misconfigured load balancer sent writes to both nodes 3 minutes during failover — 847 conflicting order rows. Old primary rewound via pg_rewind; conflicts reconciled from application audit log over 4 hours.',
        followUps:['Patroni watchdog mode?','Cloud API fencing example?','Timeline divergence detection?','Application idempotency during failover?'],
        mistakes:['Promoting without confirming old primary down','Load balancer TCP check only — both appear healthy','Delaying fencing hoping old primary recovers','No audit log to reconcile dual-write period'],
        seniorInsights:'Split-brain reconciliation is manual pain — prevention via fencing is the only production answer.',
        commands:['SELECT pg_current_wal_lsn(), pg_is_in_recovery(), pg_control_checkpoint();','patronictl list','# STONITH: aws ec2 stop-instances --instance-ids i-oldprimary'],
        bestPractices:['Implement automatic fencing in failover tooling','Load balancer must check Patroni leader role not just TCP','Alert on multiple nodes accepting writes','Maintain audit trail for post-failover reconciliation'] }),
    q('pg-failover-4','failover','highAvailability.js','hard','Common','Cloud Engineer',
      'Perform zero-downtime switchover (planned failover) with Patroni.',
      { interview:'patronictl switchover demotes current primary gracefully, promotes chosen replica, minimal connection drop. Requires healthy sync replica. Application connection pools recycle connections on error. switchover vs failover: no data loss, controlled timing during maintenance.',
        explanation:'Switchover steps: verify lag zero on target, patronictl switchover --master old --candidate new, verify patronictl list, rolling app pool reload. Maintenance: primary OS patches via switchover to upgraded standby. Schedule during low traffic; still test app retry.',
        production:'Monthly OS kernel patch: patronictl switchover to patched replica, patch old primary, switchover back. Total user-visible errors: 12 connection resets caught by app retry — zero failed transactions.',
        followUps:['Switchover with synchronous_mode required?','PgBouncer behavior during switchover?','Cancel switchover mid-flight?','RDS reboot vs switchover?'],
        mistakes:['Switchover to lagging replica','No sync standby available — data loss risk on crash mid-switch','Applications without connection retry','Switchover during active long transactions without notice'],
        seniorInsights:'Planned switchover proves HA works — run monthly, measure connection error rate.',
        commands:['patronictl switchover --master cluster-0 --candidate cluster-1','patronictl list','SHOW POOLS; -- pgbouncer reload'],
        bestPractices:['Monthly planned switchover drill','Verify sync replica caught up before switchover','Ensure app connection retry logic','Document switchover in maintenance runbook'] }),
    q('pg-failover-5','failover','highAvailability.js','hard','Rare','DBA',
      'Lead post-failover validation checklist before declaring all-clear.',
      { interview:'Verify: pg_is_in_recovery false on new primary only, pg_stat_replication shows connected replicas, replay lag nominal, application write/read smoke test, sequences advanced correctly, cron jobs running, replication slots recreated, backup jobs targeting new primary, monitoring updated leader tag.',
        explanation:'Check for orphaned prepared transactions, invalid indexes from interrupted CONCURRENTLY, subscription lag on logical replicas. Compare row counts critical tables vs pre-failover snapshot if available. Re-enable synchronous_standby_names if disabled during crisis.',
        production:'Post-failover checklist caught missing replication slot for analytics replica — CDC silent 2h until slot recreated. Added automated post-failover Ansible playbooks.',
        followUps:['Sequence jump after failover?','Logical replication re-point subscription?','Patroni post-failover config drift?','When to pg_rewind old primary vs rebuild?'],
        mistakes:['Declaring resolved after promote without replica connectivity','Backup still pointing at old hostname','Forgotten logical replication subscription update','Not checking invalid indexes after crash'],
        seniorInsights:'Failover is not done at promote — validation checklist is senior DBA differentiator.',
        commands:['SELECT pg_is_in_recovery();','SELECT * FROM pg_stat_replication;','SELECT indexrelid::regclass FROM pg_index WHERE NOT indisvalid;','SELECT pg_create_physical_replication_slot(\'replica1\');'],
        bestPractices:['Maintain post-failover checklist in runbook','Automate slot and subscription recreation','Run smoke tests before all-clear announcement','Verify backup and monitoring target new primary'] }),
  ]},
  { topic: 'connection-pooling', file: 'highAvailability.js', questions: [
    q('pg-connection-pooling-1','connection-pooling','highAvailability.js','easy','Very Common','Database Engineer',
      'Why is connection pooling essential for PostgreSQL applications?',
      { interview:'PostgreSQL uses process-per-connection — each backend consumes memory and file descriptors. Hundreds of app threads should not map 1:1 to backends. Pooler multiplexes many clients onto fewer server connections. Reduces memory pressure, speeds connection establishment, protects max_connections limit.',
        explanation:'Without pool: app server 200 workers = 200 PG backends × ~10MB. With pool: 200 clients → 20 server connections in transaction mode. Connection time ~ms vs fork backend ~20ms. Pool also centralizes SSL, auth, and routing to primary/replica.',
        production:'Java app with HikariCP pool_size=100 against PG max_connections=100 — exhausted connections during spike. Moved to PgBouncer transaction mode 1000 clients / 50 servers — stable under 3× traffic.',
        followUps:['App-side pool vs external PgBouncer?','max_connections sizing formula?','Pool after failover behavior?','RDS Proxy vs PgBouncer?'],
        mistakes:['max_connections=2000 on PG without pool','Double pooling app + PgBouncer without understanding mode','Each microservice opening 100 connections directly','Ignoring connection count in load tests'],
        seniorInsights:'Process-per-connection is THE reason pooler exists — quantify memory at interview.',
        commands:['SELECT count(*), state FROM pg_stat_activity GROUP BY state;','SHOW max_connections;','SELECT setting FROM pg_settings WHERE name=\'superuser_reserved_connections\';'],
        bestPractices:['Always pool at scale — external PgBouncer or RDS Proxy','Size server connections << client connections','Monitor pg_stat_activity connection count','Reserve superuser connections for admin'] }),
    q('pg-connection-pooling-2','connection-pooling','highAvailability.js','medium','Common','DBA',
      'Compare transaction pooling, session pooling, and statement pooling modes.',
      { interview:'Session mode: client owns server connection for session lifetime — compatible with all PG features, limited multiplexing. Transaction mode: server connection assigned per transaction only — high multiplexing, breaks session-scoped state (SET, temp tables, prepared stmts without DEALLOCATE). Statement mode: rare, per statement, most restrictions.',
        explanation:'Transaction mode: must not use SET without SET LOCAL, advisory locks problematic, LISTEN/NOTIFY broken, cursors dont survive. Session mode for ORMs needing prepared statements persistent. PgBouncer default transaction for web apps. RDS Proxy session pinning on SET variable.',
        production:'Django with transaction pooling failed — used SET search_path in middleware. Fixed: SET LOCAL search_path in transaction or switched affected services to session mode pool.',
        followUps:['Prepared statements in transaction mode?','PgBouncer max_prepared_statements PG 14+?','HikariCP + PgBouncer double pool?','Session mode connection count benefit?'],
        mistakes:['Transaction mode with app using SET SESSION','Prepared statement leak across transactions','Advisory locks in transaction pool — lock lost between txns','LISTEN/NOTIFY through transaction pooler'],
        seniorInsights:'Transaction mode caveat list is interview staple — SET, temp table, prepared stmt, advisory lock.',
        commands:['# pgbouncer.ini pool_mode = transaction','SHOW CONFIG; -- pgbouncer admin','SET LOCAL search_path TO app, public;'],
        bestPractices:['Use transaction mode for stateless web apps','Audit app for session-scoped features before transaction pooling','Use SET LOCAL not SET SESSION in pooled apps','Session mode for admin and migration tools only'] }),
    q('pg-connection-pooling-3','connection-pooling','highAvailability.js','medium','Very Common','Production Support',
      'Diagnose connection pool exhaustion and "too many clients" errors.',
      { interview:'Error: FATAL remaining connection slots reserved or too many clients. Check pg_stat_activity count vs max_connections. Identify source via application_name, client_addr. Causes: pool leak, connection storm deploy, long idle sessions, missing pooler, replication connections consuming slots.',
        explanation:'superuser_reserved_connections leaves slots for admin. idle in transaction holds connection. pg_stat_activity backend_start shows connection age. Terminate idle: pg_terminate_backend. PgBouncer wait queue SHOW POOLS cl_waiting. App connection leak shows steady count growth.',
        production:'Deploy doubled pod count each opening 50 connections — hit max_connections 300. Short-term: raised max_connections to 400. Fix: PgBouncer with default_pool_size=30, app pods reduced to 10 direct max.',
        followUps:['idle_in_transaction_session_timeout?','Connection leak detection in app?','Replication slots vs connection limit?','PgBouncer queue timeout?'],
        mistakes:['Raising max_connections indefinitely','Killing replication backends to free slots','No application_name — cannot trace source','Ignoring idle in transaction as connection consumer'],
        seniorInsights:'Connection incident triage: pg_stat_activity group by application_name, client_addr — find noisy neighbor.',
        commands:['SELECT application_name, client_addr, count(*) FROM pg_stat_activity GROUP BY 1,2 ORDER BY 3 DESC;','SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state=\'idle\' AND query_start < now()-interval \'1 hour\';','SHOW POOLS;'],
        bestPractices:['Set idle_in_transaction_session_timeout globally','Tag all connections with application_name','Alert connection count > 80% max_connections','Use pooler to bound server connection count'] }),
    q('pg-connection-pooling-4','connection-pooling','highAvailability.js','hard','Common','Cloud Engineer',
      'Design connection pooling architecture for microservices accessing shared PostgreSQL.',
      { interview:'Central PgBouncer cluster or sidecar per AZ. Per-service database roles and pool_size limits. Transaction mode for stateless APIs. Read/write split: separate pools to primary vs replicas. Avoid each microservice unlimited HikariCP — cap total server connections across fleet.',
        explanation:'Formula: sum(default_pool_size per service) + replication + admin < max_connections × 0.8. PgBouncer user auth via auth_query from pg_shadow. TLS termination at pooler. Kubernetes: PgBouncer Deployment as shared service in mesh.',
        production:'40 microservices shared one RDS — connection chaos. Deployed PgBouncer per AZ with auth_query, per-service user pool_mode=transaction max 15 server conns each. Total server connections capped 120 on max_connections=150 RDS.',
        followUps:['auth_user in PgBouncer?','RDS Proxy multi-tenant?','Circuit breaker on pool exhaustion?','Separate pool per database vs per user?'],
        mistakes:['Each microservice 50 Hikari connections no central cap','Shared DB user for all services — no attribution','Single PgBouncer SPOF without HA','No pool sizing math documented'],
        seniorInsights:'Fleet connection budget spreadsheet — service × pool_size = must fit max_connections.',
        commands:['# pgbouncer.ini auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1','auth_user = pgbouncer_auth','SHOW DATABASES;','SHOW CLIENTS;'],
        bestPractices:['Central connection budget across microservices','Per-service DB user and pool limits','HA PgBouncer with multiple instances + LB','Monitor PgBouncer SHOW STATS wait times'] }),
    q('pg-connection-pooling-5','connection-pooling','highAvailability.js','hard','Rare','Database Engineer',
      'Handle prepared statements, advisory locks, and LISTEN/NOTIFY with pooling.',
      { interview:'Transaction pooling: prepared statements must be DEALLOCATE ALL before connection return or use PgBouncer max_prepared_statements (PG14+). Advisory locks dont survive transaction end in transaction mode — use session mode or DB-level locking. LISTEN/NOTIFY requires dedicated session mode connection outside pool.',
        explanation:'PgBouncer tracks prepared stmts per client-server mapping in newer versions. ORMs (Rails, Hibernate) often incompatible with transaction pool without config. NOTIFY listener long-lived connection bypasses pooler to dedicated channel. pg_advisory_xact_lock preferred over session lock in transaction mode.',
        production:'Rails prepared statements broke under PgBouncer transaction mode — disabled prepared_statements in database.yml OR moved to session pool for Rails tier only while Node APIs stayed transaction pool.',
        followUps:['PgBouncer 1.21 prepared statement support?','Skip locked with transaction pool?','Temp tables in transaction mode?','RDS Proxy session pinning?'],
        mistakes:['ORM prepared statements + transaction pool without testing','pg_advisory_lock session lock in transaction pool','LISTEN through PgBouncer transaction pool','Not documenting which services need session mode'],
        seniorInsights:'Pool mode compatibility matrix per app framework — real production gotcha.',
        commands:['DEALLOCATE ALL;','SELECT pg_advisory_xact_lock(12345);','LISTEN order_events; -- dedicated session connection','SHOW CONFIG; | grep max_prepared'],
        bestPractices:['Test ORM with target pool mode in staging','Use pg_advisory_xact_lock in transaction pooled apps','Dedicated session connection for LISTEN/NOTIFY','Document per-service pool mode requirements'] }),
  ]},
  { topic: 'pgbouncer', file: 'highAvailability.js', questions: [
    q('pg-pgbouncer-1','pgbouncer','highAvailability.js','easy','Very Common','DBA',
      'What is PgBouncer and how do you configure basic pool settings?',
      { interview:'PgBouncer lightweight connection pooler. pgbouncer.ini: [databases] maps alias to connection string, [pgbouncer] pool_mode, default_pool_size, max_client_conn, listen_port 6432. Auth via auth_file or auth_query. Admin console: psql -p 6432 pgbouncer.',
        explanation:'default_pool_size server connections per user/database pair. max_client_conn total clients. reserve_pool for burst. server_lifetime recycles connections. unix socket or TCP. log_connections for audit.',
        production:'Standard config: transaction mode, default_pool_size=25, max_client_conn=1000, auth_query for credential rotation without ini reload.',
        followUps:['PgBouncer vs pgpool-II?','Unix socket vs TCP latency?','Multiple PgBouncer behind LB?','Version compatibility with PG 16?'],
        mistakes:['pool_mode=session defeating multiplexing purpose','auth_file plaintext passwords in repo','default_pool_size equal to max_client_conn','No max_db_connections limit per database'],
        seniorInsights:'Know pgbouncer.ini sections: databases, pgbouncer, users — admin question frequent.',
        commands:['psql -h localhost -p 6432 -U pgbouncer pgbouncer -c "SHOW POOLS;"','RELOAD; -- admin console','# pool_mode = transaction\ndefault_pool_size = 25\nmax_client_conn = 1000'],
        bestPractices:['Start with transaction mode for web workloads','Use auth_query for credential management','Set max_client_conn >> default_pool_size','Monitor via SHOW POOLS and SHOW STATS'] }),
    q('pg-pgbouncer-2','pgbouncer','highAvailability.js','medium','Common','Database Engineer',
      'Configure PgBouncer auth_query and integrate with SCRAM authentication.',
      { interview:'auth_query executes on PostgreSQL to fetch password hash for client user. auth_user connects to run query: SELECT usename, passwd FROM pg_shadow WHERE usename=$1. Supports SCRAM hashes from PG 10+. Avoids duplicating passwords in auth_file.',
        explanation:'Create pgbouncer_auth role with limited privileges executing security definer function if not direct pg_shadow access. SCRAM in PostgreSQL 14+ default. PgBouncer 1.17+ SCRAM client auth. Rotate passwords in PG only — pooler picks up on next auth.',
        production:'Migrated from auth_file MD5 to auth_query SCRAM — security audit finding closed. pgbouncer_auth user cannot login interactively, only via auth_query path.',
        followUps:['security definer function vs pg_shadow?','Client cert auth through PgBouncer?','auth_hba_file option?','Password rotation without disconnect?'],
        mistakes:['auth_user with superuser privileges','auth_file MD5 in 2024 production','auth_query function SQL injection in username','Not TLS between PgBouncer and PostgreSQL'],
        seniorInsights:'auth_query is production standard — explain auth_user minimal privilege pattern.',
        commands:['CREATE USER pgbouncer_auth PASSWORD \'...\';\nGRANT pg_read_all_settings TO pgbouncer_auth; -- or custom fn','auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1','auth_type = scram-sha-256'],
        bestPractices:['Use auth_query not static auth_file in production','SCRAM between client-PgBouncer and PgBouncer-PG','Minimal privilege auth_user','TLS for all pooler connections'] }),
    q('pg-pgbouncer-3','pgbouncer','highAvailability.js','medium','Very Common','Production Support',
      'Monitor PgBouncer with SHOW commands and troubleshoot pool saturation.',
      { interview:'SHOW POOLS: cl_active, cl_waiting, sv_active, sv_idle, maxwait. SHOW STATS: totals and averages. SHOW CLIENTS/SERVERS: connection detail. cl_waiting > 0 sustained = pool too small or slow queries holding server connections. maxwait shows longest wait seconds.',
        explanation:'Saturation fixes: increase default_pool_size, optimize long queries, ensure transaction mode releases quickly, add PgBouncer instances. query_wait_timeout kills waiting clients. server_idle_timeout closes unused server connections.',
        production:'cl_waiting peaked 847 during sale — default_pool_size 20 insufficient. Raised to 50, optimized 3 slow queries holding connections 30s+, cl_waiting zero during next sale.',
        followUps:['Export PgBouncer metrics to Prometheus?','pgbouncer_exporter Grafana?','Pool saturation vs PG CPU saturation?','reserve_pool configuration?'],
        mistakes:['Ignoring cl_waiting metric until users timeout','Increasing pool_size without checking PG max_connections headroom','Long transactions holding pooled server connection','No query_wait_timeout — infinite client wait'],
        seniorInsights:'SHOW POOLS cl_waiting is the PgBouncer panic metric — dashboard it.',
        commands:['SHOW POOLS;','SHOW STATS;','SHOW CLIENTS;','SET query_wait_timeout = 120; -- pgbouncer.ini'],
        bestPractices:['Dashboard cl_waiting and maxwait continuously','Size pool considering query duration P99','Set query_wait_timeout to fail fast','Alert sv_active approaching default_pool_size sustained'] }),
    q('pg-pgbouncer-4','pgbouncer','highAvailability.js','hard','Common','Cloud Engineer',
      'Deploy highly available PgBouncer tier with failover routing to PostgreSQL primary.',
      { interview:'Multiple PgBouncer instances behind HAProxy/NLB. Patroni REST or consul-template updates backend primary address in pgbouncer.ini or use host=all in database line with separate routing layer. On failover: RELOAD PgBouncer or automated config push. Health check PgBouncer not just PostgreSQL.',
        explanation:'PgBouncer HA not built-in — stateless pooler instances scale horizontally. primary_conninfo change on failover requires pgbouncer database host update — automate via Patroni callback script calling RELOAD. Avoid single PgBouncer pod SPOF. Co-locate pooler with app in same AZ for latency with cross-AZ PG replica routing for reads.',
        production:'3 PgBouncer instances behind NLB, Patroni on_failover callback runs sed + pgbouncer -R on all poolers. Failover connection blip 2s average with app retry.',
        followUps:['PgBouncer on same host as PG?','K8s headless service for PgBouncer?','Read/write split in PgBouncer config?','AWS RDS Proxy HA built-in comparison?'],
        mistakes:['Single PgBouncer instance production SPOF','Manual pgbouncer.ini host update during failover','HAProxy checking PG through wrong pooler backend','Not reloading all PgBouncer instances after primary change'],
        seniorInsights:'PgBouncer HA = stateless N instances + automated primary tracking — not Patroni for pooler itself.',
        commands:['# Patroni callback: sed -i "s/host=.*/host=newprimary/" /etc/pgbouncer/pgbouncer.ini && pgbouncer -R','SHOW DATABASES;','patronictl list'],
        bestPractices:['Run minimum 2 PgBouncer instances behind LB','Automate primary address update on failover','Health check each PgBouncer instance','Test failover end-to-end including pooler reload'] }),
    q('pg-pgbouncer-5','pgbouncer','highAvailability.js','hard','Rare','DBA',
      'Advanced PgBouncer tuning: pool sizing, timeouts, and multi-tenant isolation.',
      { interview:'Per-database pool_size override in [databases] section. max_user_connections limit noisy tenant. server_round_robin for load spread. pkt_buf/max_packet_size for large payloads. disable_pqexec for simple protocol. Application naming via connect_query SET application_name.',
        explanation:'Multi-tenant: separate database alias per tenant same PG database different pool_size. track_extra_parameters for SET tracking PG 14+. client_idle_timeout disconnects idle clients. query_timeout kills long server queries protecting pool.',
        production:'SaaS 200 tenants shared pool — one tenant batch job exhausted pool. Implemented per-tenant PgBouncer database alias with max_user_connections=5 for free tier, 50 for enterprise.',
        followUps:['PgBouncer vs RDS Proxy feature matrix?','Pool per tenant vs per tier?','admin_users security?','PgBouncer connection to multiple PG clusters?'],
        mistakes:['Single pool_size for heterogeneous tenant SLAs','No query_timeout — one slow query blocks pool','connect_query SET on every checkout overhead ignored','admin password default pgbouncer'],
        seniorInsights:'Multi-tenant pool isolation at PgBouncer layer — enterprise SaaS architecture pattern.',
        commands:['# [databases]\ntenant_a = host=pg dbname=shared pool_size=5 max_user_connections=5\ntenant_b = host=pg dbname=shared pool_size=50','connect_query = SET application_name=\'via-pgbouncer\'','SHOW CONFIG;'],
        bestPractices:['Tier pool limits by tenant SLA','Set query_timeout to protect shared pools','Secure admin console with strong auth_users','Use connect_query for application_name attribution'] }),
  ]},
];
