/** PostgreSQL registry data — btree, gin, brin, partitioning, performance, backup */
import { q } from './_postgresqlRegistryData.part1.mjs';

export const PART4 = [
  { topic: 'btree-index', file: 'indexing.js', questions: [
    q('pg-btree-index-1','btree-index','indexing.js','easy','Very Common','Database Engineer',
      'How does PostgreSQL B-tree index structure support range and equality queries?',
      { interview:'B-tree stores keys sorted with leaf pages linked for range scans. Root-to-leaf traversal O(log n). Supports =, <, <=, >, >=, BETWEEN, IN, IS NULL. Default for PRIMARY KEY and UNIQUE. Multi-column index uses leftmost prefix rule for composite keys.',
        explanation:'Internal pages hold pivot keys; leaves hold (key, heap_tid). Duplicate keys allowed unless UNIQUE. NULLs sorted with NULLS FIRST/LAST per index definition. page splits on insert; fillfactor default 90 leaves room. CLUSTER ON index reorders heap to match index — maintenance heavy.',
        production:'Slow ORDER BY created_at DESC LIMIT 20 — seq scan on 50M rows. CREATE INDEX CONCURRENTLY idx_orders_created ON orders (created_at DESC); query 800ms → 2ms.',
        followUps:['Composite index column order rules?','Index on UUID v4 random insert performance?','B-tree deduplication PG 13+?','When does planner skip index for ORDER BY?'],
        mistakes:['Wrong composite column order — filter on second column only','UUID v4 PK causing index bloat and page splits','Duplicate indexes on (a) and (a,b) without reason','Missing CONCURRENTLY on production CREATE INDEX'],
        seniorInsights:'Leftmost prefix rule is the #1 composite index interview question — give concrete multi-column example.',
        commands:['CREATE INDEX CONCURRENTLY idx_orders_created ON orders (created_at DESC);','EXPLAIN SELECT * FROM orders ORDER BY created_at DESC LIMIT 20;','SELECT * FROM pg_stat_user_indexes WHERE indexrelname = \'idx_orders_created\';'],
        bestPractices:['Order composite columns by selectivity and query patterns','Use CONCURRENTLY for production index builds','Consider time-ordered keys (bigint sequences) over random UUID PK','Verify index usage via pg_stat_user_indexes idx_scan'] }),
    q('pg-btree-index-2','btree-index','indexing.js','medium','Common','DBA',
      'Explain B-tree index bloat, fragmentation, and REINDEX strategies.',
      { interview:'Non-HOT updates and deletes leave empty index entries until vacuum reclaims — pages may stay allocated causing bloat. REINDEX rebuilds compact structure. REINDEX CONCURRENTLY (PG 12+) avoids long exclusive locks. pgstatuple and pgstattuple_approx measure bloat.',
        explanation:'Index bloat increases cache pressure and scan cost. VACUUM reclaims dead tuples but may not shrink index pages — REINDEX needed. REINDEX INDEX CONCURRENTLY builds new index, swaps via catalog update. pg_repack can rebuild indexes online too. autovacuum on index same as heap.',
        production:'users_email_idx bloated to 4GB (actual 800MB data) after bulk email update campaign. REINDEX INDEX CONCURRENTLY users_email_idx during low traffic; size 900MB, lookup latency halved.',
        followUps:['pg_repack vs REINDEX CONCURRENTLY?','Index bloat without heap bloat possible?','REINDEX on PK constraint index?','pgstatuple index scan safety?'],
        mistakes:['REINDEX without CONCURRENTLY on production OLTP','Ignoring index bloat focusing only heap pgstattuple','REINDEX entire database during peak','Not investigating update pattern causing bloat'],
        seniorInsights:'idx_scan high + idx_blks_read rising + index size growing = bloat suspicion before pgstattuple confirms.',
        commands:['CREATE EXTENSION pgstattuple;','SELECT * FROM pgstattuple(\'users_email_idx\');','REINDEX INDEX CONCURRENTLY users_email_idx;','SELECT pg_size_pretty(pg_relation_size(\'users_email_idx\'));'],
        bestPractices:['Monitor index size growth rate vs table growth','Use REINDEX CONCURRENTLY in maintenance windows','Fix HOT-unfriendly update patterns at source','Schedule bloat checks on top 20 indexes quarterly'] }),
    q('pg-btree-index-3','btree-index','indexing.js','medium','Very Common','Production Support',
      'Why might PostgreSQL ignore a B-tree index and how do you fix it?',
      { interview:'Planner chooses seq scan when estimated rows exceed index selectivity threshold, statistics stale, function wrapper prevents index use (WHERE lower(email)=), wrong data type coercion, or index invalid (CREATE INDEX CONCURRENTLY failed). EXPLAIN shows Seq Scan when index expected.',
        explanation:'Enable enable_seqscan off session-only to test index benefit. ANALYZE refreshes stats. Expression index must match expression exactly. Invalid indexes: indisvalid=false in pg_index. Cast mismatch: WHERE varchar_col = integer prevents index unless cast on column side.',
        production:'Query WHERE user_id = $1 seq scanned — user_id was text, parameter int implicit cast on column. Fixed query to cast parameter::text; Index Scan returned, 200ms → 3ms.',
        followUps:['Invalid index from CONCURRENTLY failure?','OR conditions and bitmap vs single index?','Statistics target too low for skewed column?','Partial index predicate mismatch?'],
        mistakes:['WHERE YEAR(created_at)=2024 instead of range on created_at','Not checking pg_index.indisvalid after failed CONCURRENTLY','Session enable_seqscan=off left in connection pool','Adding index without ANALYZE verifying plan change'],
        seniorInsights:'Always check implicit cast direction — index on column, cast on parameter not column.',
        commands:['EXPLAIN ANALYZE SELECT * FROM users WHERE user_id = 12345;','SELECT indexrelid::regclass, indisvalid FROM pg_index WHERE NOT indisvalid;','ANALYZE users;','CREATE INDEX CONCURRENTLY ... -- re-run if invalid dropped'],
        bestPractices:['Match query predicates to index definition exactly','Check indisvalid after CONCURRENTLY index builds','Run ANALYZE after index creation','Use EXPLAIN to verify index usage before closing ticket'] }),
    q('pg-btree-index-4','btree-index','indexing.js','hard','Common','Database Engineer',
      'Optimize composite B-tree indexes for multi-column WHERE and ORDER BY queries.',
      { interview:'Leading column must appear in WHERE for efficient use (exceptions with skip scan not native). Equality columns first, range last: (status, created_at) for WHERE status=\'open\' AND created_at > X. INCLUDE columns for covering without sort key ordering constraints.',
        explanation:'Index-only scan needs all SELECT/WHERE columns in index or INCLUDE. Sort direction: (created_at DESC) matches ORDER BY created_at DESC. Multiple indexes combined via BitmapAnd. Consider separate indexes if queries use different leading columns exclusively.',
        production:'Existing (created_at, status) unused — queries filter status first. Added (status, created_at DESC) partial WHERE status IN (\'open\',\'pending\'); 95th percentile 400ms → 15ms.',
        followUps:['Skip scan workaround in PostgreSQL?','INCLUDE vs composite for covering?','Multicolumn statistics for correlated filters?','Index merge bitmap performance?'],
        mistakes:['One composite trying to serve incompatible query patterns','Range column before equality in index definition','Ignoring sort direction mismatch in ORDER BY','10-column composite index hurting write path'],
        seniorInsights:'Draw two query patterns — show when two indexes beat one overloaded composite.',
        commands:['CREATE INDEX CONCURRENTLY idx_open ON orders (status, created_at DESC) WHERE status IN (\'open\',\'pending\');','EXPLAIN ANALYZE SELECT * FROM orders WHERE status=\'open\' AND created_at > now()-interval \'7 days\' ORDER BY created_at DESC;'],
        bestPractices:['Design composites per query pattern not per table','Put equality columns before range in index','Match DESC/ASC to ORDER BY direction','Split indexes when leading columns differ across queries'] }),
    q('pg-btree-index-5','btree-index','indexing.js','hard','Rare','DBA',
      'Manage B-tree index build impact on production: CONCURRENTLY, parallelism, and locks.',
      { interview:'CREATE INDEX CONCURRENTLY: SHARE UPDATE EXCLUSIVE — allows reads/writes but two table scans, longer build. Failed CONCURRENTLY leaves INVALID index. maintenance_work_mem sizes sort during build. max_parallel_maintenance_workers (PG 11+) parallelizes btree build.',
        explanation:'Non-concurrent CREATE INDEX blocks writes. Progress in pg_stat_progress_create_index. Long builds on huge tables — monitor replication lag and disk. DROP INDEX CONCURRENTLY similar lock level. Build during replica-first then CREATE on primary if acceptable lag.',
        production:'CREATE INDEX on 200GB table without CONCURRENTLY blocked checkout 22 minutes — incident. Policy: all production indexes CONCURRENTLY with lock_timeout alert; parallel_workers=4 cut build from 6h to 2h.',
        followUps:['INVALID index cleanup procedure?','Build index on replica then attach?','Lock queue behind CREATE INDEX?','Temp file usage during index build?'],
        mistakes:['CREATE INDEX without CONCURRENTLY on production','Ignoring INVALID index after failed build','maintenance_work_mem too low — disk sort spill','Not monitoring pg_stat_progress_create_index'],
        seniorInsights:'CONCURRENTLY failure leaves landmine INVALID index — monitoring indisvalid is production hygiene.',
        commands:['CREATE INDEX CONCURRENTLY idx_big ON big_table (col);','SELECT * FROM pg_stat_progress_create_index;','SELECT indexrelid::regclass, indisvalid FROM pg_index WHERE NOT indisvalid;','DROP INDEX CONCURRENTLY idx_invalid;'],
        bestPractices:['Mandatory CREATE INDEX CONCURRENTLY in production runbooks','Alert on invalid indexes','Size maintenance_work_mem for index builds','Monitor build progress and replication lag'] }),
  ]},
  { topic: 'gin-index', file: 'indexing.js', questions: [
    q('pg-gin-index-1','gin-index','indexing.js','easy','Very Common','Database Engineer',
      'When should you use a GIN index and what data types benefit most?',
      { interview:'GIN (Generalized Inverted Index) excels at containment queries: arrays @>, &&, jsonb @>, ?, full-text @@, hstore. Inverted structure maps elements to row TIDs. Larger and slower to update than B-tree but fast for multi-value search.',
        explanation:'jsonb default GIN opclass jsonb_ops supports many operators; jsonb_path_ops smaller/faster for @> only. array, tsvector, uuid[] supported. GIN fastupdate pending list — batch insert fast, merge on vacuum. gin_pending_list_limit controls flush.',
        production:'Product search on jsonb attributes: seq scan 4s. CREATE INDEX idx_products_attrs ON products USING gin (attributes jsonb_path_ops); search 40ms.',
        followUps:['jsonb_ops vs jsonb_path_ops?','GIN vs GiST for full-text?','gin_trgm_ops for LIKE?','GIN index size expectations?'],
        mistakes:['GIN on column with single scalar values','jsonb_path_ops when needing ? operator','Ignoring GIN write overhead on high-INSERT table','No gin_pending_list tuning on bulk load'],
        seniorInsights:'GIN = inverted index interview answer — draw word → row list analogy for FTS/jsonb.',
        commands:['CREATE INDEX idx_gin ON products USING gin (attributes jsonb_path_ops);','EXPLAIN SELECT * FROM products WHERE attributes @> \'{"color":"red"}\';','SELECT pg_size_pretty(pg_relation_size(\'idx_gin\'));'],
        bestPractices:['Use jsonb_path_ops when only @> containment needed','Measure write impact before GIN on hot OLTP tables','Run VACUUM after bulk jsonb load to merge GIN pending','Choose operator class matching query operators'] }),
    q('pg-gin-index-2','gin-index','indexing.js','medium','Common','DBA',
      'Explain GIN pending list, fastupdate, and vacuum maintenance.',
      { interview:'gin_fastupdate=ON (default): changes accumulate in pending list instead of immediate index merge — faster inserts, slower until merged at vacuum or when gin_pending_list_limit exceeded. Bulk load: consider disabling fastupdate during load then re-enable + VACUUM.',
        explanation:'Pending list bloat slows searches scanning both main tree and pending. gin_clean_pending_list() manual merge. autovacuum triggers merge. COPY into jsonb table with GIN — pending list can grow large before vacuum.',
        production:'Bulk jsonb import 10M rows — queries slow until vacuum ran 2h later. Set gin_pending_list_limit=256MB and scheduled VACUUM after each batch; query performance stable during load.',
        followUps:['ALTER INDEX gin_fastupdate?','GIN vs BRIN for jsonb analytics?','autovacuum not merging GIN pending why?','REINDEX GIN after bulk load?'],
        mistakes:['Never vacuuming after bulk GIN insert','gin_fastupdate=off globally without understanding insert cost','Pending list limit too small causing frequent merges during OLTP','Assuming GIN maintenance-free'],
        seniorInsights:'Bulk jsonb + GIN playbook: load → VACUUM (or increase pending limit during load).',
        commands:['ALTER INDEX idx_gin SET (fastupdate = on);','VACUUM ANALYZE products;','SELECT * FROM pg_stat_user_indexes WHERE indexrelname = \'idx_gin\';'],
        bestPractices:['VACUUM after bulk loads on GIN-indexed tables','Tune gin_pending_list_limit for batch workloads','Monitor index scan latency during large ingests','Consider disabling fastupdate only for controlled bulk sessions'] }),
    q('pg-gin-index-3','gin-index','indexing.js','medium','Very Common','Production Support',
      'Implement full-text search with GIN tsvector indexes.',
      { interview:'to_tsvector(\'english\', body) converts text to lexemes; @@ match operator. CREATE INDEX USING gin(tsv). ts_rank for relevance ordering. Use plainto_tsquery or websearch_to_tsquery for user input. GiST alternative supports ranking but GIN faster lookup.',
        explanation:'Generated column or trigger maintains tsv column on INSERT/UPDATE. Configuration \'english\' stems words. phraseto_tsquery for exact phrases. GIN index on expression: CREATE INDEX ON docs USING gin(to_tsvector(\'english\', body)). Highlight via ts_headline.',
        production:'Blog search used ILIKE \'%keyword%\' — timeout on 2M posts. Added tsv GENERATED ALWAYS AS (to_tsvector(\'english\', coalesce(title,\'\') || \' \' || body)) STORED + GIN index; search p99 50ms.',
        followUps:['Weighted search ts_rank with setweight?','Update tsv on trigger vs generated column?','Multilingual tsconfig?','GiST vs GIN FTS trade-offs?'],
        mistakes:['ILIKE on large text instead of FTS','Not using appropriate text search config language','tsvector not updated on row change without trigger/generated','User input passed raw to to_tsquery — syntax errors'],
        seniorInsights:'Generated STORED tsv column (PG 12+) is cleaner than triggers for FTS maintenance.',
        commands:['ALTER TABLE docs ADD COLUMN tsv tsvector GENERATED ALWAYS AS (to_tsvector(\'english\', body)) STORED;','CREATE INDEX idx_docs_fts ON docs USING gin(tsv);','SELECT title, ts_rank(tsv, query) FROM docs, plainto_tsquery(\'english\', \'postgresql index\') query WHERE tsv @@ query ORDER BY ts_rank DESC LIMIT 20;'],
        bestPractices:['Use plainto_tsquery/websearch_to_tsquery for user search input','Generated column or trigger to keep tsvector fresh','GIN index on tsvector column not raw text','Choose language config matching content'] }),
    q('pg-gin-index-4','gin-index','indexing.js','hard','Common','Database Engineer',
      'Use pg_trgm GIN indexes for fuzzy and LIKE pattern search.',
      { interview:'pg_trgm extension breaks strings into trigrams; similarity() and % operator; GIN gin_trgm_ops supports LIKE/ILIKE %pattern% via index. Index size significant. set_limit() adjusts similarity threshold. Better than seq scan for autocomplete on names.',
        explanation:'CREATE INDEX ON users USING gin (name gin_trgm_ops). pg_trgm.similarity_threshold GUC. ILIKE \'%foo%\' can use trigram index unlike B-tree. Combine with LIMIT for autocomplete. Write overhead moderate vs jsonb GIN.',
        production:'Customer name autocomplete ILIKE caused seq scans. CREATE INDEX users_name_trgm ON customers USING gin (name gin_trgm_ops); autocomplete latency 200ms → 8ms for prefix/substring patterns.',
        followUps:['trgm vs B-tree prefix index for LIKE \'foo%\'?','Index on lower(name) vs gin_trgm?','Similarity vs word_similarity?','pg_trgm on JSON text fields?'],
        mistakes:['Trigram index on high-cardinality unique codes — no benefit','Very short strings (<3 chars) poor trigram selectivity','Not enabling pg_trgm extension in migration','Expecting trigram to fix typo tolerance without similarity op'],
        seniorInsights:'Trigram is the answer for ILIKE %x% when FTS stemming inappropriate — know operator class gin_trgm_ops.',
        commands:['CREATE EXTENSION pg_trgm;','CREATE INDEX customers_name_trgm ON customers USING gin (name gin_trgm_ops);','SELECT * FROM customers WHERE name ILIKE \'%smith%\' LIMIT 20;','SET pg_trgm.similarity_threshold = 0.3;'],
        bestPractices:['Use trigram for substring/autocomplete not exact match','Enable pg_trgm extension explicitly in migrations','Combine with LIMIT for UI autocomplete endpoints','Benchmark write impact on high-INSERT name columns'] }),
    q('pg-gin-index-5','gin-index','indexing.js','hard','Rare','DBA',
      'Size and tune GIN indexes on terabyte-scale jsonb document stores.',
      { interview:'GIN size often 30-70% of jsonb column size with jsonb_ops; jsonb_path_ops smaller. Partition table by time/hash to limit index size per partition. autovacuum aggressive on pending list. Consider jsonb subset columns for hot query paths instead of indexing entire blob.',
        explanation:'Extract hot keys to generated columns with targeted GIN. BRIN on created_at + GIN on partition. Monitoring pg_relation_size per partition index. REINDEX CONCURRENTLY per partition during rotation. TOAST compresses large jsonb — index includes toasted values.',
        production:'2TB events jsonb single GIN 800GB — autovacuum never caught pending on partition. Migrated to monthly partitions each with jsonb_path_ops GIN max 40GB; dropped monolithic index; ops manageable.',
        followUps:['Hash vs range partition for jsonb?','jsonb subset indexing expression?','GIN on partitioned table attach pattern?','Citus jsonb sharding?'],
        mistakes:['Single GIN on terabyte jsonb monolith','jsonb_ops when only @> needed — 2× size','No partition strategy with GIN write amplification','Ignoring TOAST bloat separate from GIN'],
        seniorInsights:'Partition + jsonb_path_ops is the terabyte jsonb answer — monolithic GIN does not scale operationally.',
        commands:['CREATE TABLE events (...) PARTITION BY RANGE (created_at);','CREATE INDEX ON events_2024_01 USING gin (payload jsonb_path_ops);','SELECT pg_size_pretty(sum(pg_relation_size(indexrelid))) FROM pg_stat_user_indexes WHERE indexrelname LIKE \'events%\';'],
        bestPractices:['Partition large jsonb tables before GIN index exceeds maintenance capacity','Prefer jsonb_path_ops for containment-only workloads','Extract frequently queried keys to indexed generated columns','REINDEX CONCURRENTLY per partition on rolling schedule'] }),
  ]},
  { topic: 'brin-index', file: 'indexing.js', questions: [
    q('pg-brin-index-1','brin-index','indexing.js','easy','Common','Database Engineer',
      'What is a BRIN index and when is it the right choice?',
      { interview:'BRIN (Block Range Index) stores min/max summary per page range — tiny index size. Ideal for naturally ordered data: timestamps, serial IDs, append-only logs. Equality/range queries scan relevant heap ranges only. Wrong for random-ordered columns where every range matches.',
        explanation:'pages_per_range default 128 — tune smaller for selective ranges. Index size KB vs GB for B-tree on same column. Bitmap scan combines BRIN with heap fetch. Correlation near 1.0 in pg_stats predicts BRIN success.',
        production:'500GB append-only metrics table — B-tree on ts was 12GB. BRIN on ts 48KB index; time-range queries still sub-second via range exclusion.',
        followUps:['BRIN vs B-tree size comparison?','pages_per_range tuning?','BRIN on partitioned table auto-create?','Can BRIN support UNIQUE?'],
        mistakes:['BRIN on UUID random PK','BRIN on frequently UPDATEd column breaking ordering','Expecting index-only scan from BRIN','pages_per_range too large missing selectivity'],
        seniorInsights:'Check pg_stats.correlation — >0.9 correlation + append-only = BRIN candidate.',
        commands:['CREATE INDEX idx_metrics_ts_brin ON metrics USING brin (ts);','SELECT attname, correlation FROM pg_stats WHERE tablename=\'metrics\' AND attname=\'ts\';','EXPLAIN SELECT * FROM metrics WHERE ts > now()-interval \'1 hour\';'],
        bestPractices:['Use BRIN on append-only time-series with high correlation','Check correlation statistic before creating BRIN','Prefer BRIN over B-tree for large historical scan-heavy tables','Combine BRIN with partitioning for retention management'] }),
    q('pg-brin-index-2','brin-index','indexing.js','medium','Common','DBA',
      'Tune BRIN pages_per_range and multi-column BRIN indexes.',
      { interview:'Smaller pages_per_range = finer granularity, larger index, better selectivity. Multi-column BRIN stores combined range per page range — useful when physical order correlates (ts + sensor_id in insert order). Not equivalent to composite B-tree — all columns share same range buckets.',
        explanation:'BRIN scan returns lossy page ranges — recheck heap filter required. Multi-column BRIN on (device_id, ts) when rows inserted device-by-device. ALTER INDEX ... SET (pages_per_range = 32). Summarize manually BRIN not needed — auto maintained on insert.',
        production:'BRIN pages_per_range=128 missed selective hourly queries — too many heap pages scanned. SET pages_per_range=32; index 3× larger still only 120KB; query 3× faster.',
        followUps:['BRIN summarize after bulk load?','BRIN on numeric vs timestamptz?','Combine BRIN with partial index?','BRIN deduplication?'],
        mistakes:['Multi-column BRIN when columns not physically correlated','Never tuning pages_per_range from default','BRIN as only index on random data — useless','Comparing BRIN size to B-tree expecting similar selectivity'],
        seniorInsights:'pages_per_range is the BRIN knob — explain trade-off with heap pages scanned metric in EXPLAIN.',
        commands:['CREATE INDEX idx_brin ON logs USING brin (device_id, ts) WITH (pages_per_range = 32);','ALTER INDEX idx_brin SET (pages_per_range = 64);','EXPLAIN (ANALYZE) SELECT * FROM logs WHERE ts BETWEEN $1 AND $2;'],
        bestPractices:['Benchmark pages_per_range on representative queries','Use multi-column BRIN only with physical correlation','Monitor heap blocks read in EXPLAIN ANALYZE','Revisit BRIN params after data ingestion pattern changes'] }),
    q('pg-brin-index-3','brin-index','indexing.js','medium','Very Common','Production Support',
      'Why might BRIN index scans return many false-positive heap pages?',
      { interview:'BRIN summarizes min/max per page range — if values within range spread across many ranges or correlation low, many ranges qualify. Lossy bitmap includes pages where only some rows match. High correlation and append-only insert pattern minimizes false positives.',
        explanation:'Updated rows breaking physical order degrade BRIN effectiveness — vacuum does not reorder heap. Cluster or partition by time maintains order. EXPLAIN shows Rows Removed by Filter high on BRIN scan. Re-cluster table or rebuild partition for order restoration.',
        production:'BRIN on created_at after mass UPDATE reshuffled rows — scan read 10× pages. New monthly partitions append-only restored BRIN efficiency; legacy partition got B-tree.',
        followUps:['CLUSTER vs pg_repack for BRIN order?','BRIN on partitioned append-only child?','When to drop BRIN and use B-tree?','BRIN autosummarize on partition attach?'],
        mistakes:['BRIN on heavily updated timestamp column','Ignoring Rows Removed by Filter in EXPLAIN','No correlation check before BRIN create','Single BRIN on table with mixed insert patterns'],
        seniorInsights:'BRIN degradation after UPDATE is classic — interview answer: BRIN assumes heap order matches index order.',
        commands:['EXPLAIN (ANALYZE, BUFFERS) SELECT count(*) FROM events WHERE created_at > $1;','SELECT correlation FROM pg_stats WHERE tablename=\'events\' AND attname=\'created_at\';','CLUSTER events USING idx_events_ts_btree; -- restore order if needed'],
        bestPractices:['Use BRIN primarily on append-only partitions','Monitor filter removal ratio in EXPLAIN ANALYZE','Migrate updated partitions from BRIN to B-tree','Validate correlation statistic periodically'] }),
    q('pg-brin-index-4','brin-index','indexing.js','hard','Common','Database Engineer',
      'Design BRIN + partitioning strategy for time-series telemetry data.',
      { interview:'Partition by time range (daily/monthly); BRIN on ts per partition — small indexes, detach old partitions for archival. B-tree on (device_id, ts) for point lookups if needed. Compression via pg_compress or columnar extension optional. Retention: DROP partition vs export to cold storage.',
        explanation:'Default partition catch-all monitored separately. BRIN autosummarize on new partitions. pg_partman automates creation. Query must include partition key for pruning. BRIN on parent partitioned table PG 11+ indexes all children.',
        production:'IoT 5TB telemetry: monthly partitions, BRIN ts 2MB total across 60 partitions vs 80GB B-tree attempt abandoned. Queries always include time bounds — partition pruning + BRIN optimal.',
        followUps:['BRIN index on partitioned table parent?','pg_partman BRIN template?','Cross-partition aggregate performance?','TimescaleDB vs native partition+BRIN?'],
        mistakes:['Queries without partition key — scans all partitions','BRIN on default partition receiving random backfill','No automation for partition creation','B-tree on every partition when BRIN suffices'],
        seniorInsights:'Time-series stack: partition prune → BRIN range scan → optional device B-tree for point queries.',
        commands:['CREATE TABLE metrics (ts timestamptz, device_id int, value float) PARTITION BY RANGE (ts);','CREATE INDEX ON metrics_2024_01 USING brin (ts);','EXPLAIN SELECT avg(value) FROM metrics WHERE ts > now()-interval \'1 day\';'],
        bestPractices:['Always filter on partition key in application queries','Automate partition lifecycle with pg_partman','Use BRIN per partition for append-only time ranges','Archive/detach old partitions instead of DELETE'] }),
    q('pg-brin-index-5','brin-index','indexing.js','hard','Rare','Cloud Engineer',
      'Compare BRIN vs B-tree vs Timescale hypertable indexing for cloud cost optimization.',
      { interview:'BRIN: minimal storage cost, good for scan-heavy analytics on ordered data. B-tree: higher storage/IOPS, needed for selective OLTP lookups. Timescale: compression + chunk policies reducing storage 90%+, B-tree on compressed chunks limited. Cloud cost = storage GB + IOPS + compute for autovacuum/index maintenance.',
        explanation:'Aurora/RDS storage grows with index size — BRIN saves real money on logs. Timescale continuous aggregates precompute rollups. BRIN maintenance near zero vs B-tree write amplification. Evaluate query mix: if 95% range aggregates on logs, BRIN wins.',
        production:'Cloud bill audit: 400GB B-tree indexes on log tables — migrated to BRIN + partition detach to S3 via aws_s3 extension. Storage cost -$1.2k/month with same query SLAs on aggregates.',
        followUps:['Aurora I/O-Optimized vs BRIN benefit?','S3 foreign table for cold logs?','Columnar compression PG extensions?','Index maintenance CPU cost BRIN vs B-tree?'],
        mistakes:['B-tree on every log column by default template','Ignoring index storage in cloud TCO','Timescale compression without query plan validation','BRIN on OLTP lookup path to save cost'],
        seniorInsights:'Cloud DBA interview: translate index choice to $/month — BRIN on logs is FinOps not just performance.',
        commands:['SELECT indexrelname, pg_size_pretty(pg_relation_size(indexrelid)) FROM pg_stat_user_indexes WHERE relname LIKE \'logs%\';','CREATE INDEX logs_brin ON logs USING brin (logged_at);'],
        bestPractices:['Model storage cost of indexes in cloud architecture reviews','Use BRIN for append-only log/analytics tables','Compress or archive old partitions to object storage','Match index strategy to query SLA not defaults'] }),
  ]},
  { topic: 'partitioning', file: 'indexing.js', questions: [
    q('pg-partitioning-1','partitioning','indexing.js','easy','Very Common','Database Engineer',
      'Explain declarative partitioning types in PostgreSQL: RANGE, LIST, and HASH.',
      { interview:'RANGE: time/ID ranges (most common). LIST: discrete values (region, status). HASH: uniform shard by hash mod. PARTITION BY creates parent; CREATE TABLE ... PARTITION OF attaches child. Inserts route to partition via bound check. UNIQUE/PK must include partition key.',
        explanation:'PG 10+ declarative replaces inheritance manual triggers. DEFAULT partition catches unmatched rows — monitor overflow. Sub-partitioning supported. pg_partition_tree shows hierarchy. Constraint exclusion prunes partitions at plan time.',
        production:'Orders table 800GB — partitioned monthly by created_at. Queries with date filter scan 1 partition not 800GB; maintenance VACUUM per partition parallelizable.',
        followUps:['PRIMARY KEY on partitioned table rules?','DEFAULT partition pitfalls?','Attach/detach PARTITION for archival?','Inherited vs declarative partitioning?'],
        mistakes:['UNIQUE index without partition key column','No DEFAULT partition — INSERT fails silently in app','Forgetting partition key in query — full scan all children','Manual inheritance triggers in new projects'],
        seniorInsights:'PK must include partition key — schema design constraint interviewers test.',
        commands:['CREATE TABLE orders (...) PARTITION BY RANGE (created_at);','CREATE TABLE orders_2024_01 PARTITION OF orders FOR VALUES FROM (\'2024-01-01\') TO (\'2024-02-01\');','SELECT * FROM pg_partition_tree(\'orders\');'],
        bestPractices:['Include partition key in PRIMARY KEY and UNIQUE constraints','Automate partition creation (pg_partman)','Always query with partition key filter when possible','Plan DEFAULT partition for overflow monitoring'] }),
    q('pg-partitioning-2','partitioning','indexing.js','medium','Common','DBA',
      'How does partition pruning work and why might it fail?',
      { interview:'Planner eliminates partitions whose bounds cannot match WHERE clause. Requires immutable partition key expression in predicate. Stable functions or wrong type coercion disable pruning. EXPLAIN shows Subplans Removed or Append with selected children only.',
        explanation:'enable_partition_pruning=on default. Constraint exclusion on CHECK bounds. Join pruning PG 11+ when partition key in join condition. prepare_threshold can cache generic plan missing pruning — plan_cache_mode=force_custom_plan for debugging. Static vs runtime pruning.',
        production:'Query WHERE created_at >= $1 failed pruning — app sent timestamptz param but column was timestamp without time zone. Cast mismatch fixed; partitions scanned dropped from 36 to 1.',
        followUps:['Runtime vs compile-time pruning?','Partition-wise join PG 11+?','Pruning with OR conditions across partitions?','Foreign key across partitioned table?'],
        mistakes:['Partition key type mismatch with parameter','WHERE date_trunc(\'month\', ts) preventing prune','Generic prepared plan scanning all partitions','Not checking EXPLAIN partition count after deploy'],
        seniorInsights:'Pruning failure #1: function wrapper on partition key — show EXPLAIN Append node count.',
        commands:['EXPLAIN SELECT count(*) FROM orders WHERE created_at >= \'2024-06-01\' AND created_at < \'2024-07-01\';','SET plan_cache_mode = force_custom_plan;','SHOW enable_partition_pruning;'],
        bestPractices:['Match partition key data type exactly in queries','Avoid functions on partition key in WHERE','Verify pruning in EXPLAIN after schema changes','Use pg_partman premake to avoid missing future partitions'] }),
    q('pg-partitioning-3','partitioning','indexing.js','medium','Very Common','Production Support',
      'Manage partition maintenance: CREATE, ATTACH, DETACH, and DROP safely.',
      { interview:'CREATE new partition before data arrives (pg_partman premake). DETACH CONCURRENTLY (PG 14+) removes partition without blocking reads/writes on parent. ATTACH requires validation scan unless WITHOUT VALIDATION on pre-validated data. DROP partition fast alternative to DELETE millions of rows.',
        explanation:'DETACH for archival to cold storage or DROP. ATTACH PARTITION for backfill historical data. Partition-level INDEX builds faster than monolith. VACUUM one partition at a time reduces lock blast radius.',
        production:'Retention policy: DETACH CONCURRENTLY orders_2022_01, export to S3 via COPY, DROP TABLE — 40M row delete avoided, completed in 4 minutes vs 6 hour DELETE lock risk.',
        followUps:['ATTACH CONCURRENTLY PG 14+?','Exchange partition pattern for bulk load?','Global index on partitioned PG version limits?','Replication of partition DDL?'],
        mistakes:['DROP partition without backup confirmation','ATTACH with wrong bound overlapping existing','DELETE millions instead of DROP partition','Missing premake — INSERT into nonexistent partition'],
        seniorInsights:'DETACH + DROP is retention at scale — never DELETE by date range on partitioned table.',
        commands:['ALTER TABLE orders DETACH PARTITION orders_2022_01 CONCURRENTLY;','DROP TABLE orders_2022_01;','SELECT partman.run_maintenance(\'public.orders\'); -- pg_partman'],
        bestPractices:['Automate premake partitions 3 months ahead','Use DETACH CONCURRENTLY for production archival','Backup before DROP partition','Document retention workflow in runbook'] }),
    q('pg-partitioning-4','partitioning','indexing.js','hard','Common','Database Engineer',
      'Implement partition-wise joins and aggregates for analytics performance.',
      { interview:'PG 11+ enable_partitionwise_join and enable_partitionwise_aggregate allow joining/aggr matching partitioned tables per partition — parallelizable. Requires compatible partition bounds and keys. Major win for large star-schema fact+dimension when dimension also partitioned or small.',
        explanation:'Planner creates Append of per-partition joins. enable_partitionwise_aggregate reduces memory for GROUP BY. Both default on in recent PG. EXPLAIN shows Partition-wise Join. Mismatch partition schemes disables optimization.',
        production:'Star query fact_sales partition by month, dim_customers small — partitionwise join reduced 12-partition join from 90s to 18s on PG 15.',
        followUps:['Sub-partition partitionwise?','Hash-hash partition join alignment?','When partitionwise disabled?','Parallel partition-wise join workers?'],
        mistakes:['Different partition bounds on join tables','Partitionwise expected without matching keys','Not enabling on PG 11+ defaults off upgraded systems','Oversized dimension forcing broadcast anyway'],
        seniorInsights:'Partition-wise join requires partition key alignment in join predicate — design fact/dim partition strategy together.',
        commands:['SET enable_partitionwise_join = on;','SET enable_partitionwise_aggregate = on;','EXPLAIN ANALYZE SELECT ... FROM fact JOIN dim ON ...;'],
        bestPractices:['Align partition schemes on frequently joined large tables','Verify partitionwise nodes in EXPLAIN for top analytics queries','Keep dimension tables small or co-partitioned','Upgrade PG to leverage partitionwise improvements'] }),
    q('pg-partitioning-5','partitioning','indexing.js','hard','Rare','DBA',
      'Migrate a large non-partitioned table to declarative partitioning with minimal downtime.',
      { interview:'Strategy: create new partitioned parent + partitions, COPY/pg_dump data into correct partitions OR INSERT SELECT batched, CREATE INDEX CONCURRENTLY per partition, brief cutover rename swap. pg_partman partition_data_time for migration helper. Logical replication can sync during migration.',
        explanation:'ALTER TABLE ... PARTITION BY not in-place for existing heap — requires copy. Dual-write period or logical rep catches delta. FK references must be recreated. Sequences shared. Application cutover at low traffic. Validate row counts per partition.',
        production:'400GB orders migration: created partitioned clone, pg_copy physical load per month batch over weekend, logical rep caught delta, 5-min rename swap Monday AM. Rollback plan kept old table 72h.',
        followUps:['Citus distribute from single node?','FK to partitioned table PG 12+?','Trigger-based vs copy migration?','Index creation order during migration?'],
        mistakes:['In-place ALTER expecting instant partition','No row count validation at cutover','Forgetting sequence setval sync','Cutover without lock on application writes'],
        seniorInsights:'Large table partition migration is a project — logical rep + swap is modern standard answer.',
        commands:['CREATE TABLE orders_new (...) PARTITION BY RANGE (created_at);','INSERT INTO orders_2024_06 SELECT * FROM orders WHERE created_at >= ...;','BEGIN; ALTER TABLE orders RENAME TO orders_old; ALTER TABLE orders_new RENAME TO orders; COMMIT;'],
        bestPractices:['Rehearse migration on clone with production volume','Use logical replication for delta sync during copy','Validate counts and checksums per partition at cutover','Keep rollback table until soak period completes'] }),
  ]},
  { topic: 'query-optimization', file: 'performance.js', questions: [
    q('pg-query-optimization-1','query-optimization','performance.js','easy','Very Common','Database Engineer',
      'Walk through systematic PostgreSQL query optimization using EXPLAIN ANALYZE.',
      { interview:'Capture query from pg_stat_statements. Run EXPLAIN (ANALYZE, BUFFERS, VERBOSE) — compare estimated vs actual rows. Identify seq scans on large tables, nested loops with high loops count, hash/sort spills to temp. Fix: indexes, stats, query rewrite, work_mem session tuning.',
        explanation:'Buffers: shared hit vs read shows cache effectiveness. Timing per node localizes cost. Rows Removed by Filter indicates index inefficiency. Planning time vs execution time — prepared statement caching. auto_explain in production for slow query capture.',
        production:'Top query 40% DB time — EXPLAIN showed Nested Loop 2M loops. Missing index on line_items.order_id. CREATE INDEX CONCURRENTLY; mean time 120ms → 4ms.',
        followUps:['BUFFERS shared read vs local?','When EXPLAIN ANALYZE modifies data?','Generic vs custom plan prepared statements?','pg_qualstats for predicate analysis?'],
        mistakes:['EXPLAIN without ANALYZE guessing at runtime cost','Fixing query in prod without testing on staging clone','Adding index before checking existing redundant indexes','Ignoring Rows Removed by Filter metric'],
        seniorInsights:'Optimization loop: pg_stat_statements → EXPLAIN ANALYZE → fix → reset stats → verify mean_time drop.',
        commands: ['CREATE EXTENSION pg_stat_statements;','EXPLAIN (ANALYZE, BUFFERS, VERBOSE) SELECT ...;','SELECT query, calls, mean_exec_time, rows FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 10;'],
        bestPractices:['Always use EXPLAIN (ANALYZE, BUFFERS) for investigation','Compare estimated vs actual rows at each plan node','Verify fix impact in pg_stat_statements after deploy','Enable auto_explain for queries exceeding threshold'] }),
    q('pg-query-optimization-2','query-optimization','performance.js','medium','Common','DBA',
      'Use pg_stat_statements for workload analysis and regression detection.',
      { interview:'pg_stat_statements normalizes queries tracking calls, total_time, mean_time, rows, shared_blks_read, temp_blks_written. queryid groups identical plans. Identify top total_exec_time consumers first — not just mean_time. Reset stats after optimization to measure delta.',
        explanation:'Requires shared_preload_libraries. track_io_timing adds IO wait. pg_stat_statements_info tracks reset timestamp. Compare snapshots exported to Prometheus. Hypothetical indexes via hypopg before CREATE. pg_store_plans saves plan history.',
        production:'Weekly pg_stat_statements export — detected new deploy query with temp_blks_written spike. work_mem bump for report role + query rewrite eliminated 50GB temp files daily.',
        followUps:['pg_stat_statements vs pg_stat_activity?','Query normalization limitations?','track_planning option PG 13+?','Reset stats safely in production?'],
        mistakes:['Optimizing high mean_time but low call count queries first','Not recording baseline before change','shared_preload_libraries missing after restart','Ignoring temp_blks_written leading indicator'],
        seniorInsights:'Rank by total_exec_time = mean × calls — the 50ms query called 10M times beats 5s query called 100 times.',
        commands:['SELECT query, calls, mean_exec_time, total_exec_time, shared_blks_read, temp_blks_written FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 20;','SELECT pg_stat_statements_reset();','SELECT * FROM pg_stat_statements_info;'],
        bestPractices:['Export pg_stat_statements metrics to monitoring weekly','Prioritize by total_exec_time not mean alone','Capture baseline before optimization changes','Enable track_io_timing for IO-bound analysis'] }),
    q('pg-query-optimization-3','query-optimization','performance.js','medium','Very Common','Production Support',
      'Identify and fix N+1 query patterns and ORM-generated inefficient SQL.',
      { interview:'N+1: loop fetching parent then child per row — shows as many identical queries in pg_stat_activity. Fix: JOIN, WHERE IN batch, ORM eager loading (select_related/prefetch). ORM issues: SELECT *, implicit casts, OFFSET pagination on large tables, lack of LIMIT on relations.',
        explanation:'pg_stat_statements high calls + low rows per call signals N+1. application_name tags help trace to service. Prepared statements may hide in ORM logs — use log_min_duration_statement. Keyset pagination preferred over OFFSET for deep pages.',
        production:'API p99 spike — pg_stat_statements showed 500 calls/sec SELECT * FROM comments WHERE post_id=$1. Django prefetch_related fix reduced to 2 queries per request; p99 800ms → 45ms.',
        followUps:['Lazy vs eager loading trade-offs?','WHERE IN vs JOIN performance?','Cursor-based pagination implementation?','ORM partial index utilization?'],
        mistakes:['Database index on FK without ORM eager load fix','OFFSET 100000 pagination on social feed','SELECT * returning large TOAST columns unnecessarily','Blaming PostgreSQL before checking ORM query log'],
        seniorInsights:'N+1 is app pattern — show pg_stat_statements calls metric as detection signal.',
        commands:['SELECT query, calls, rows/calls AS rows_per_call FROM pg_stat_statements WHERE query LIKE \'%comments%\' ORDER BY calls DESC;','EXPLAIN ANALYZE SELECT * FROM comments WHERE post_id = ANY($1::int[]);'],
        bestPractices:['Tag connections with application_name per service','Monitor queries with calls > 1000/min and rows/call < 5','Use batch loading or JOIN in ORM configuration','Prefer keyset pagination for large offsets'] }),
    q('pg-query-optimization-4','query-optimization','performance.js','hard','Common','Database Engineer',
      'Optimize JSONB queries and avoid sequential scans on document columns.',
      { interview:'Use GIN with jsonb_path_ops for @> containment. Expression indexes on ->> extracted fields for equality filters. jsonb_each for ad-hoc — not indexable. Select only needed keys not entire document. TOAST stores large jsonb — fetching full column expensive.',
        explanation:'CREATE INDEX ON t ((data->>\'status\')) for WHERE data->>\'status\' = \'active\'. statistics on expressions need ANALYZE. jsonb_populate_record for structured access. Avoid OR across many jsonb paths — separate indexed generated columns better.',
        production:'WHERE data @> \'{"type":"premium"}\' seq scanned — GIN jsonb_path_ops index + partial on active records. Combined with generated column status extracted for reporting filter.',
        followUps:['JSON_TABLE PG 17+ vs jsonb_each?','TOAST threshold tuning?','jsonb vs normalized schema trade-off?','Immutable function requirement for jsonb index?'],
        mistakes:['B-tree on entire jsonb column','data->key without GIN for containment','Returning full jsonb blob in list API','No statistics on expression index column'],
        seniorInsights:'Extract hot filter fields to generated STORED columns — cleaner than complex GIN for mixed workload.',
        commands:['CREATE INDEX idx_data_gin ON t USING gin (data jsonb_path_ops);','ALTER TABLE t ADD COLUMN status text GENERATED ALWAYS AS (data->>\'status\') STORED;','CREATE INDEX idx_status ON t (status);','EXPLAIN SELECT id FROM t WHERE data @> \'{"type":"premium"}\';'],
        bestPractices:['GIN for containment; B-tree/expression for equality on extracted fields','Minimize jsonb column width in SELECT lists','Use generated columns for frequently filtered keys','ANALYZE after adding jsonb indexes'] }),
    q('pg-query-optimization-5','query-optimization','performance.js','hard','Rare','Cloud Engineer',
      'Lead performance incident: database CPU 100% — structured triage approach.',
      { interview:'1) pg_stat_activity: active queries, wait_events. 2) pg_stat_statements: top total_time last reset. 3) Check replication lag, autovacuum, checkpoints concurrently. 4) EXPLAIN active query. 5) Mitigate: cancel query, pg_terminate_backend, statement_timeout, route read to replica. 6) Root fix: index, rewrite, scale.',
        explanation:'CPU 100% causes: missing index seq scans, parallel query storm, excessive connection count, autovacuum anti-wraparound, cryptographic functions in query, PL/pgSQL tight loops. RDS Performance Insights maps wait events. Not always query — check connection count and background workers.',
        production:'Black Friday CPU pegged — pg_stat_activity showed 200 identical unindexed facet search queries. Emergency CREATE INDEX CONCURRENTLY on products(category, brand); cancelled runaway reporting session; CPU 95% → 40% in 8 minutes.',
        followUps:['wait_event CPU vs IO vs Lock?','When to fail over vs fix in place?','Connection storm vs query storm differentiation?','PgBouncer queue during CPU saturation?'],
        mistakes:['Restart PostgreSQL as first action losing diagnostic state','Scaling CPU without identifying query root cause','Killing autovacuum during wraparound risk','No pg_stat_statements enabled pre-incident'],
        seniorInsights:'Incident command answer: observe → identify top query → mitigate → fix → postmortem with pg_stat_statements snapshot.',
        commands:['SELECT pid, now()-query_start AS dur, state, wait_event_type, wait_event, left(query,80) FROM pg_stat_activity WHERE state=\'active\';','SELECT pg_cancel_backend(pid);','SELECT query, total_exec_time FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 5;'],
        bestPractices:['Maintain pg_stat_statements always enabled','Runbook for CPU incidents with ordered diagnostic queries','Set statement_timeout globally with override role','Post-incident: index/query fix ticket from captured plans'] }),
  ]},
  { topic: 'backup-recovery', file: 'backupRecovery.js', questions: [
    q('pg-backup-recovery-1','backup-recovery','backupRecovery.js','easy','Very Common','DBA',
      'Compare PostgreSQL backup methods: pg_dump, pg_basebackup, and filesystem snapshots.',
      { interview:'pg_dump: logical, portable, slow restore large DBs, good for selective tables. pg_basebackup: physical consistent copy + WAL for PITR. Filesystem snapshot: fast but need pg_start_backup/pg_stop_backup or use pg_backup_start API to ensure consistency. pgBackRest/wal-g unify physical + WAL management.',
        explanation:'pg_dump -Fc custom format parallel restore. pg_basebackup requires replication connection or data dir access. Snapshots on cloud EBS without backup label risk inconsistent copy unless PostgreSQL aware. Continuous archiving enables PITR between backups.',
        production:'Nightly pg_dump -Fc for 50GB schema-only dev refresh; pgBackRest full weekly + incremental daily for 2TB production with 15-min WAL archive RPO.',
        followUps:['pg_dump parallel -j option?','Snapshot backup without pg_backup_start?','pg_dumpall vs pg_dump?','Cloud RDS snapshot vs logical export?'],
        mistakes:['Only pg_dump for 5TB production — RTO days','EBS snapshot without understanding crash consistency','No WAL archive with physical backup — cannot PITR','pg_dump during peak without snapshot isolation'],
        seniorInsights:'Answer matrix: logical for migration/small; physical+WAL for production DR with RPO/RTO SLAs.',
        commands:['pg_dump -Fc -f backup.dump mydb','pg_basebackup -D /backup/base -Fp -Xs -P','SELECT pg_backup_start(\'snapshot_label\', false); -- PG 15+','pgbackrest --stanza=main backup'],
        bestPractices:['Physical backup + WAL archive for production DR','Test restore quarterly measuring actual RTO','Separate backup retention from production disk','Automate backup verification (pg_verifybackup)'] }),
    q('pg-backup-recovery-2','backup-recovery','backupRecovery.js','medium','Common','Database Engineer',
      'Configure and validate pgBackRest or wal-g backup pipeline.',
      { interview:'pgBackRest: stanza config, full/differential/incremental, parallel backup/restore, encryption, S3/Azure/GCS repos. wal-g: delta backups, WAL push, simple S3. Both integrate archive_command. retention policies, backup scheduling via cron/k8s CronJob.',
        explanation:'pgBackRest manifest tracks checksums; pg_verifybackup validates. wal-g backup-push + wal-push. Point-in-time restore from base + WAL replay. Encryption at rest and in transit. Monitor last successful backup age alert.',
        production:'Migrated shell scripts to pgBackRest — backup window 4h → 45min with --process-max=8; restore test automated in CI weekly restoring to ephemeral instance.',
        followUps:['pgBackRest diff vs incr?','wal-g delta backup mechanics?','Backup from standby vs primary?','Encryption key rotation?'],
        mistakes:['No backup verification — corrupt backup discovered at DR','WAL archive and backup tool misconfigured paths','Single backup copy in same region','Retention too short for compliance requirement'],
        seniorInsights:'Name the tool but explain components: base backup + WAL chain + manifest + verify + restore drill.',
        commands:['pgbackrest --stanza=main --type=full backup','pgbackrest --stanza=main info','wal-g backup-push $PGDATA','pgbackrest --stanza=main verify'],
        bestPractices:['Automate backup verification after each run','Store backups in separate region/account','Document restore procedure with measured RTO','Monitor backup job success with alerting'] }),
    q('pg-backup-recovery-3','backup-recovery','backupRecovery.js','medium','Very Common','Production Support',
      'Perform full database restore from pg_dump custom format backup.',
      { interview:'pg_restore -d target_db -j 4 backup.dump restores selective or full. Create empty database first. --section=pre-data/data/post-data for staged restore. Ownership and privileges via --no-owner if cross-env. Extension versions must exist on target.',
        explanation:'Parallel restore -j speeds large restores. Single transaction --single-transaction for atomicity small DBs. Conflicts: existing objects — use --clean carefully. Sequences restored with setval. Large restore: tune maintenance_work_mem, disable triggers temporarily if needed.',
        production:'Restored staging from prod pg_dump -Fc over weekend — pg_restore -j 8 --no-owner --role=staging_app completed 180GB in 2.5h. Verified row counts per schema against source manifest.',
        followUps:['pg_restore vs psql plain SQL dump?','Restore single table from custom dump?','Cross-version pg_restore compatibility?','RDS restore from logical dump?'],
        mistakes:['Restoring into non-empty database without --clean plan','Missing extensions on target causing restore failure','Not disabling application connections during restore','Ignoring sequence setval mismatch post-restore'],
        seniorInsights:'Staging refresh runbook: drop/create DB, pg_restore parallel, ANALYZE, smoke tests.',
        commands:['createdb restore_target','pg_restore -d restore_target -j 8 --no-owner --role=app backup.dump','pg_restore -l backup.dump -- list contents','ANALYZE;'],
        bestPractices:['Test restore procedure on isolated instance regularly','Use parallel pg_restore for large databases','Validate row counts and application smoke tests post-restore','Document extension prerequisites on target server'] }),
    q('pg-backup-recovery-4','backup-recovery','backupRecovery.js','hard','Common','DBA',
      'Recover individual tables or schemas without full cluster restore.',
      { interview:'From pg_dump: pg_restore -t table_name or -n schema only. From physical backup: not granular — must restore whole cluster to temp instance, pg_dump table, import. Logical decoding or replication for ongoing selective sync. pg_copy for partial export if source still up.',
        explanation:'Postgres lacks native table-level PITR from physical backups. Workaround: restore backup to scratch instance, replay WAL to point, pg_dump -t, restore to prod. pg_dump --exclude-table for inverse. Foreign tables for federated access during recovery.',
        production:'Accidental TRUNCATE on config_table — full restore unacceptable. Restored last nightly pg_dump -t config_table to temp DB, diffed rows, INSERT missing rows back to prod in transaction. 12-minute recovery.',
        followUps:['pg_restore --table vs -t?','Point-in-time table recovery patterns?','Delay replica for oops protection?','pg_surgery extension danger?'],
        mistakes:['Attempting table extract from raw data files manually','No regular pg_dump with table-level granularity available','Restoring full 2TB for one table without scratch automation','TRUNCATE without delayed replica or audit log'],
        seniorInsights:'Table-level recovery needs logical backup or PITR-to-scratch — physical backup alone insufficient.',
        commands:['pg_restore -d prod -t config_table backup.dump','pg_dump -t config_table -Fc prod > config_table.dump','CREATE DATABASE scratch; pg_restore -d scratch full.backup; pg_dump -t config_table scratch'],
        bestPractices:['Maintain logical backups alongside physical for granular recovery','Automate scratch instance restore for table-level DR','Consider delayed standby for operator error protection','Audit destructive DDL/DML on critical tables'] }),
    q('pg-backup-recovery-5','backup-recovery','backupRecovery.js','hard','Rare','Cloud Engineer',
      'Design backup retention, compliance, and encryption for regulated PostgreSQL workloads.',
      { interview:'Retention: daily 30d, weekly 12w, monthly 7y per compliance. Immutable WORM storage for SOC2/HIPAA. Encryption: backup files AES-256, KMS-managed keys, TLS in transit. Access audit on backup bucket. Separate backup account from production AWS org.',
        explanation:'pgBackRest repo1-cipher-type=aes-256-cbc. wal-g GPG or SSE-KMS. Legal hold prevents deletion. Cross-region replication of backup bucket. Document RPO/RTO in compliance packet. pg_audit logs who restored when if instrumented.',
        production:'HIPAA Postgres: pgBackRest to S3 Object Lock COMPLIANCE mode 7yr, KMS CMK, backup in separate AWS account with break-glass procedure. Quarterly restore drill logged for auditors.',
        followUps:['RDS automated backup vs custom compliance?','Right to erasure vs backup retention conflict?','Backup access IAM policy pattern?','Air-gapped backup copy?'],
        mistakes:['Backups in same account/region as primary — ransomware risk','No immutability — attacker deletes backups','Encryption without key rotation procedure','Retention policy not matching legal requirements'],
        seniorInsights:'Regulated backup answer includes immutability + separate account + tested restore + audit trail.',
        commands:['# pgBackRest: repo1-s3-key, repo1-cipher-pass','aws s3api put-object-lock-configuration --bucket backups','pgbackrest --stanza=main info'],
        bestPractices:['Immutable backup storage for compliance workloads','Separate cloud account for backup repository','Encrypt backups with KMS and rotate keys','Log and audit every restore operation'] }),
  ]},
  { topic: 'pitr', file: 'backupRecovery.js', questions: [
    q('pg-pitr-1','pitr','backupRecovery.js','easy','Very Common','DBA',
      'Explain Point-in-Time Recovery (PITR) architecture in PostgreSQL.',
      { interview:'Base backup + continuous WAL archiving enables recovery to any timestamp/LSN between backup and latest WAL. recovery.signal file triggers recovery mode on startup. restore_command fetches archived WAL segments. recovery_target_time or recovery_target_lsn sets stop point.',
        explanation:'Archive mode on; archive_command copies WAL. Base backup labels start LSN in pg_backup_label. On restore: copy base, create recovery.signal, set postgresql.conf recovery params or postgresql.auto.conf. PostgreSQL replays WAL until target reached then promotes with pg_ctl promote if desired.',
        production:'Operator error DELETE without WHERE — PITR to 5 minutes before incident using morning base backup + WAL archive. RPO 2 minutes achieved. Total recovery 45 minutes for 500GB.',
        followUps:['recovery_target_action pause vs promote?','Timeline switch during PITR?','pg_combinebackup PG 17+?','PITR on replica vs primary restore?'],
        mistakes:['No WAL archive enabled believing snapshots sufficient','Wrong timezone in recovery_target_time','Missing WAL segment in archive — recovery stops','Promoting recovered instance without revoking old credentials'],
        seniorInsights:'PITR = base + WAL + target — draw timeline on whiteboard for interview.',
        commands:['# postgresql.auto.conf:\nrestore_command = \'cp /wal_archive/%f %p\'\nrecovery_target_time = \'2024-06-15 14:32:00 UTC\'\nrecovery_target_action = promote','touch $PGDATA/recovery.signal','pg_ctl start -D $PGDATA'],
        bestPractices:['Continuous WAL archiving to durable storage','Document recovery_target_time timezone convention UTC','Test PITR quarterly on clone','Verify WAL archive completeness with pg_archivecleanup monitoring'] }),
    q('pg-pitr-2','pitr','backupRecovery.js','medium','Common','Database Engineer',
      'Configure recovery_target options: time, LSN, name, and XID.',
      { interview:'recovery_target_time: human timestamp (timezone critical). recovery_target_lsn: exact WAL position from pg_walfile_name/pg_current_wal_lsn. recovery_target_name: restore point from pg_create_restore_point(). recovery_target_xid: transaction ID. recovery_target_inclusive controls boundary inclusivity.',
        explanation:'pg_create_restore_point(\'before_migration\') before risky DDL — named target for rollback. recovery_target_timeline for advanced timeline forks. pg_waldump finds LSN for incident time correlation. recovery_target_action=pause allows verification before promote.',
        production:'Before risky migration: SELECT pg_create_restore_point(\'pre_alter_orders\'); migration failed; PITR to named restore point — faster than calculating timestamp.',
        followUps:['recovery_target_timeline when needed?','Find LSN for timestamp without replay?','Promote after pause vs immediate?','PITR to standby vs new instance?'],
        mistakes:['Local timezone in recovery_target_time causing 5h error','No restore point before major migration','recovery_target_inclusive misunderstanding off-by-one','PITR without isolating from production network post-recover'],
        seniorInsights:'Named restore points are DBA best practice before migrations — mention pg_create_restore_point.',
        commands:['SELECT pg_create_restore_point(\'before_index_rebuild\');','SELECT pg_current_wal_lsn(), now();','# recovery_target_name = \'before_index_rebuild\'','pg_waldump -t | head'],
        bestPractices:['Create named restore points before risky operations','Always use UTC for recovery_target_time','Pause recovery to verify data before promote','Correlate incident time with pg_current_wal_lsn logs'] }),
    q('pg-pitr-3','pitr','backupRecovery.js','medium','Very Common','Production Support',
      'Troubleshoot PITR failure: missing WAL segment or recovery stops early.',
      { interview:'Recovery stops at first missing WAL — check pg_log for "could not open file". Verify archive completeness: pg_waldump on archived segments sequence. Gap from archive_command failure or retention too short. pgBackRest/wal-g inventory lists available WAL. recovery_target past available WAL fails.',
        explanation:'WAL segments 16MB named 000000010000000000000001. Timeline history must be continuous. restore_command must return zero on success. Partial segment copy corrupts recovery. Test restore_command manually: cp or aws s3 cp.',
        production:'PITR stopped at 14:35 — WAL segment 0000000100000000000000AB missing from S3. archive_command had failed during 14:30-14:40 window. Restored to 14:30 accepting 5 min data loss; backfilled from application logs.',
        followUps:['pg_wal_replay_resume PG 18+?','Rebuild missing WAL from replica?','wal-g wal-fetch during restore?','Partial write detection in archive?'],
        mistakes:['WAL retention shorter than max time between backup and incident','No monitoring of archive gaps','restore_command typo %f vs %p','Deleting WAL from archive per retention during active PITR need'],
        seniorInsights:'Archive gap detection should be proactive — compare pg_current_wal_lsn to last archived segment continuously.',
        commands:['SELECT * FROM pg_stat_archiver;','ls /wal_archive/ | tail','pg_waldump /wal_archive/0000000100000000000000AA','restore_command = \'aws s3 cp s3://bucket/wal/%f %p\''],
        bestPractices:['Monitor archive lag and gap alerts','Retain WAL beyond minimum RPO window','Test restore_command fetch manually before full PITR','Log archive failures with immediate paging'] }),
    q('pg-pitr-4','pitr','backupRecovery.js','hard','Common','Cloud Engineer',
      'Execute PITR on AWS RDS PostgreSQL vs self-managed EC2 PostgreSQL.',
      { interview:'RDS: restore to point in time creates NEW instance from automated backups + transaction logs — cannot PITR in-place. Self-managed: manual base + WAL to existing or new EC2. Aurora: PITR similar RDS with shared storage model faster. RTO longer for RDS PITR due to provisioning.',
        explanation:'RDS retention 1-35 days configurable. Cross-region PITR if cross-region backup enabled. Self-managed: pgBackRest restore to time on bare instance — more control, more ops burden. Document connection string switch for RDS PITR new endpoint.',
        production:'RDS prod PITR to T-10min created new instance rds-recovery-20240615; app cutover via Route53 after validation. RTO 35 min including instance create. Self-managed DR region used pgBackRest stanza restore in parallel.',
        followUps:['RDS vs Aurora PITR speed?','In-place RDS rollback impossible why?','Export RDS snapshot vs PITR?','Combine RDS PITR with DMS?'],
        mistakes:['Expecting in-place RDS rollback','PITR RDS instance in same subnet without security review','Not updating application secrets/endpoint after RDS PITR','RDS backup retention 1 day for compliance workload'],
        seniorInsights:'Cloud managed PITR always creates new instance — plan DNS/credential cutover in RTO.',
        commands:['aws rds restore-db-instance-to-point-in-time --source-db-instance-identifier prod --target-db-instance-identifier recovery --restore-time 2024-06-15T14:32:00Z','pgbackrest --stanza=main --type=time "--target=2024-06-15 14:32:00" restore'],
        bestPractices:['Document RDS PITR creates new instance with new endpoint','Set RDS backup retention to meet RPO requirements','Rehearse DNS cutover for RDS PITR recovery','Maintain self-managed DR copy if multi-cloud portability needed'] }),
    q('pg-pitr-5','pitr','backupRecovery.js','hard','Rare','DBA',
      'Calculate and communicate RPO/RTO for PITR capability to stakeholders.',
      { interview:'RPO: max acceptable data loss = WAL archive granularity + archive lag (e.g., 5 min async archive). RTO: time to restore base + replay WAL + validation + cutover. Document assumptions: team availability, runbook tested, network bandwidth for WAL fetch, instance provisioning time.',
        explanation:'RTO components: detect incident, decision, fetch base backup (TB hours), WAL replay (GB/min depends on IO), smoke test, DNS switch. RPO worse if archive breaks or sync rep not used. Tabletop exercises produce real numbers not guesses.',
        production:'Presented to exec: RPO 5 min (WAL archive), RTO 2h (2TB, last drill 1h 47m + 15m validation). Invested in pgBackRest parallel restore reducing RTO from 4h prior year.',
        followUps:['Sync rep RPO vs archive RPO stacking?','Incremental backup impact on RTO?','Legal max RPO vs technical RPO?','Chaos engineering for DR metrics?'],
        mistakes:['Claiming RPO zero without sync rep or quorum','RTO slideware never validated by drill','Ignoring application validation time in RTO','Archive lag not in RPO calculation'],
        seniorInsights:'Executives want numbers from last drill not theory — bring pgBackRest restore log timestamps.',
        commands:['pgbackrest --stanza=main info','# Document: last restore drill RTO=1h47m at 2TB','SELECT now() - last_archived_time AS archive_lag FROM pg_stat_archiver;'],
        bestPractices:['Measure RTO via quarterly restore drills','Include archive lag in RPO reporting','Update stakeholders after infrastructure changes','Separate OLTP RPO from analytics RPO tiers'] }),
  ]},
];
