/** PostgreSQL registry data — mvcc, wal, vacuum, autovacuum */
import { q } from './_postgresqlRegistryData.part1.mjs';

export const PART2 = [
  { topic: 'mvcc', file: 'mvcc.js', questions: [
    q('pg-mvcc-1','mvcc','mvcc.js','easy','Very Common','Database Engineer',
      'Explain PostgreSQL MVCC: xmin, xmax, and tuple visibility rules.',
      { interview:'Each row version carries xmin (inserting xact) and xmax (deleting/updating xact). Snapshots compare active xids to determine visibility. Readers never block writers; UPDATE creates new tuple version leaving dead row until vacuum. Transaction isolation uses snapshot export at statement or transaction start.',
        explanation:'Heap tuples store t_xmin/t_xmax in tuple header. CLOG (pg_xact) and commit timestamps track commit status. SnapshotTooOld can occur on long snapshots with aggressive vacuum settings. Repeatable Read and Serializable use same snapshot for transaction duration. HOT updates avoid index changes when updated columns are not indexed and page has space.',
        production:'Support ticket: duplicate key on unique index despite SELECT showing no row — uncommitted INSERT held lock; concurrent session saw invisible tuple. pg_locks showed waiting on RowExclusiveLock. Resolved by shortening idle transactions holding open xacts.',
        followUps:['What is HOT update and when does it fail?','How does pg_snapshot_xmin() relate to vacuum?','Difference between Read Committed and Repeatable Read visibility?','What causes xmin horizon to stall vacuum?'],
        mistakes:['Assuming DELETE frees space immediately without vacuum','Confusing MVCC with undo logs like Oracle','Long idle in transaction blocking vacuum on entire cluster','Not checking xmax for update conflicts in Serializable'],
        seniorInsights:'Interview gold: trace SELECT visibility for one row through concurrent UPDATE and COMMIT. Mention freeze xmin and wraparound — separate but related vacuum concern.',
        commands:['SELECT xmin, xmax, * FROM orders WHERE id = 1;','SELECT txid_current();','SELECT relname, n_dead_tup, last_vacuum FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10;','SELECT pg_current_snapshot();'],
        bestPractices:['Keep transactions short to limit dead tuple accumulation','Monitor n_dead_tup via pg_stat_user_tables','Use READ COMMITTED default unless app needs RR semantics','Alert on idle in transaction sessions > 5 minutes'] }),
    q('pg-mvcc-2','mvcc','mvcc.js','medium','Common','DBA',
      'How do transaction isolation levels affect locking and anomalies in PostgreSQL?',
      { interview:'Default READ COMMITTED takes new snapshot per statement — prevents dirty read but allows non-repeatable read. REPEATABLE READ prevents non-repeatable read; phantoms blocked differently than Oracle RR. SERIALIZABLE uses SSI detecting rw-conflicts with 40001 errors.',
        explanation:'RC: each statement sees rows committed before statement start. RR: snapshot at transaction start; concurrent updates to seen rows fail with serialization failure on write. Serializable tracks rw-dependencies. SELECT FOR UPDATE takes row locks regardless of isolation. Advisory locks are application-level.',
        production:'Payment service used RR but did not retry on 40001 — rare double-charge during flash sale. Added ORM retry on serialization_failure. pg_stat_database deadlocks unrelated — conflict was on primary write path.',
        followUps:['When does SELECT FOR UPDATE SKIP LOCKED help?','SSI predicate locking vs traditional 2PL?','How does deferrable READ ONLY avoid snapshot conflicts?','Lock modes for UPDATE vs DELETE?'],
        mistakes:['Using SERIALIZABLE globally without app retry logic','Expecting RR to prevent all phantoms without understanding PG RR','FOR UPDATE on non-indexed column causing seq scan + row lock storm','Mixing isolation levels in same connection pool without SET per transaction'],
        seniorInsights:'Most web apps are fine with READ COMMITTED + explicit locking for inventory. Serializable is for financial invariants — always pair with exponential backoff retry.',
        commands:['SHOW transaction_isolation;','BEGIN ISOLATION LEVEL SERIALIZABLE;','SELECT * FROM pg_locks WHERE NOT granted;','SELECT datname, deadlocks FROM pg_stat_database;'],
        bestPractices:['Document isolation level per service in architecture docs','Implement retry on SQLSTATE 40001 for Serializable','Use SELECT FOR UPDATE for explicit pessimistic paths','Monitor deadlocks via pg_stat_database and log_lock_waits'] }),
    q('pg-mvcc-3','mvcc','mvcc.js','medium','Very Common','Production Support',
      'What causes "could not serialize access due to concurrent update" and how do you resolve it?',
      { interview:'Error SQLSTATE 40001 in Serializable or when RR transaction re-reads row modified by concurrent commit. SSI detects dangerous structures between concurrent transactions. Resolution: application retry with backoff, reduce transaction scope, order lock acquisition consistently, or downgrade isolation where invariants allow.',
        explanation:'In RR, UPDATE/DELETE of row changed since snapshot raises 40001. In Serializable, rw-conflicts between concurrent read/write sets trigger rollback of one transaction. High conflict rate signals hot row contention — consider advisory lock per entity or queue serialization.',
        production:'Inventory decrement under Serializable caused 15% transaction failure rate during peak. Switched hot SKU path to SELECT FOR UPDATE in READ COMMITTED — conflicts dropped to near zero, latency predictable.',
        followUps:['Difference between deadlock and serialization failure?','How to log serialization failures?','Does advisory lock participate in SSI?','Impact of prepared statements on retry?'],
        mistakes:['Infinite retry without jitter causing thundering herd','Catching generic Exception instead of 40001 specifically','Using Serializable for read-heavy reporting','Not reducing transaction touch set on hot rows'],
        seniorInsights:'Measure conflict rate before choosing Serializable. Often explicit row lock + RC is simpler and faster than SSI rollback lottery.',
        commands:['SET log_lock_waits = on;','SELECT pg_advisory_xact_lock(hashtext(\'sku:123\'));','BEGIN ISOLATION LEVEL REPEATABLE READ;'],
        bestPractices:['Retry 40001 with exponential backoff capped at 3-5 attempts','Serialize hot row updates via FOR UPDATE or advisory locks','Keep Serializable transactions read-only when possible','Load test isolation choice under peak concurrency'] }),
    q('pg-mvcc-4','mvcc','mvcc.js','hard','Common','Database Engineer',
      'Explain HOT chains, line pointer redirection, and index bloat from non-HOT updates.',
      { interview:'HOT (Heap Only Tuple): when UPDATE does not change indexed columns and same page has free space, new row version stays on page with HOT chain via ctid redirect. Index entries still point to chain head — no new index tuples. Non-HOT UPDATE when indexed column changes or page full causes index bloat.',
        explanation:'HOT reduces index write amplification on frequently updated non-indexed columns. pg_stat_user_tables n_tup_hot_upd tracks HOT ratio. REINDEX needed when index bloat exceeds benefit. fillfactor < 100 reserves page space for HOT.',
        production:'User sessions table updated last_active every 30s on indexed user_id PK — HOT ratio 0%, indexes 3× table size. Dropped redundant index, SET fillfactor=80, moved last_active to side table. n_tup_hot_upd rose to 85%.',
        followUps:['How to detect HOT failure in pageinspect?','fillfactor trade-offs for insert-heavy tables?','BRIN and HOT interaction?','Does VACUUM FULL rebuild HOT chains?'],
        mistakes:['Indexing every column on high-update tables','fillfactor=100 on session/heartbeat tables','Ignoring n_tup_hot_upd metric','REINDEX CONCURRENTLY without fixing update pattern'],
        seniorInsights:'Schema design beats tuning: separate volatile columns to side table without indexes on hot path.',
        commands:['SELECT relname, n_tup_upd, n_tup_hot_upd FROM pg_stat_user_tables WHERE relname = \'sessions\';','ALTER TABLE sessions SET (fillfactor = 80);','SELECT indexrelname, pg_size_pretty(pg_relation_size(indexrelid)) FROM pg_stat_user_indexes WHERE relname = \'sessions\';'],
        bestPractices:['Monitor HOT update ratio on high-churn tables','Avoid indexing columns updated every request','Use fillfactor 70-90 on update-heavy heaps','Split volatile attributes to narrow side tables'] }),
    q('pg-mvcc-5','mvcc','mvcc.js','hard','Rare','DBA',
      'How does PostgreSQL handle transaction ID wraparound and freeze operations?',
      { interview:'XIDs are 32-bit; vacuum FREEZE marks old tuples frozen so they remain visible forever without xid comparison. autovacuum triggers anti-wraparound when relfrozenxid ages. Emergency autovacuum runs at high cost delay zero. Failure to freeze before limit causes shutdown to protect data integrity.',
        explanation:'pg_class.relfrozenxid tracks oldest unfrozen xid per relation. age(datfrozenxid) in pg_database shows cluster-wide risk. vacuum freeze updates relfrozenxid. multixact has separate wraparound via pg_multixact.',
        production:'Monitoring alert: datfrozenxid age 1.8B on 9-year-old cluster — emergency VACUUM FREEZE on largest tables during maintenance window. autovacuum_freeze_max_age lowered proactively post-incident.',
        followUps:['vacuum freeze vs vacuum full?','Impact of long-running transactions on freeze cutoff?','How do prepared transactions affect freeze?','Replication slots holding xmin preventing freeze?'],
        mistakes:['Disabling autovacuum on high-churn tables','Ignoring age(relfrozenxid) in monitoring','Assuming pg_repack eliminates wraparound risk without freeze','Replication slots holding xmin preventing freeze progress'],
        seniorInsights:'Wraparound is rare on modern autovacuum but catastrophic — include datfrozenxid age in every dashboard.',
        commands:['SELECT datname, age(datfrozenxid) FROM pg_database ORDER BY 2 DESC;','SELECT relname, age(relfrozenxid) FROM pg_class WHERE relkind = \'r\' ORDER BY 2 DESC LIMIT 10;','VACUUM (FREEZE, VERBOSE) large_table;','SELECT * FROM pg_prepared_xacts;'],
        bestPractices:['Alert datfrozenxid age > 500M','Never disable autovacuum globally','Resolve orphaned prepared transactions promptly','Include freeze progress in major maintenance runbooks'] }),
  ]},
  { topic: 'wal', file: 'mvcc.js', questions: [
    q('pg-wal-1','wal','mvcc.js','easy','Very Common','DBA',
      'What is PostgreSQL WAL and why is it critical for durability and recovery?',
      { interview:'Write-Ahead Log records all data changes before reaching data files — crash recovery replays WAL from last checkpoint. WAL enables PITR, streaming replication, and logical decoding. pg_wal stores 16MB segments; wal_level controls content (minimal, replica, logical).',
        explanation:'Every commit waits for WAL flush to disk (wal_sync_method, synchronous_commit). Checkpoint records consistent recovery start point. full_page_writes protects against partial page writes after crash. wal_compression reduces segment size. archive_command ships completed segments to durable storage.',
        production:'Primary disk full on pg_wal — 500GB WAL accumulated because archive_command failed silently. Replication slots held segments. Fixed IAM role, added alert on pg_wal directory size > 100GB.',
        followUps:['Difference between wal_level replica and logical?','What triggers checkpoint?','How does synchronous_commit=off affect RPO?','WAL vs heap write ordering?'],
        mistakes:['Placing pg_wal on slow network storage without testing','wal_level=minimal on replicas needing hot standby','Ignoring archive_command non-zero exit in logs','Manual rm on pg_wal files'],
        seniorInsights:'WAL is the spine of PostgreSQL HA — trace commit → WAL insert → flush → bgwriter dirty pages.',
        commands:['SELECT pg_current_wal_lsn();','SELECT * FROM pg_stat_wal;','SHOW wal_level;'],
        bestPractices:['Monitor pg_wal disk separately from data','Test archive_command recovery monthly','Set wal_level=replica minimum for HA','Alert on pg_stat_archiver failed_count'] }),
    q('pg-wal-2','wal','mvcc.js','medium','Common','Database Engineer',
      'Explain checkpoint tuning: max_wal_size, checkpoint_timeout, and checkpoint_completion_target.',
      { interview:'Checkpoints flush dirty buffers and create recovery starting point. max_wal_size triggers checkpoint when WAL generated exceeds threshold. checkpoint_timeout is time-based cap. checkpoint_completion_target spreads dirty writes over checkpoint interval reducing IO spikes.',
        explanation:'Default max_wal_size 1GB often too low for write-heavy workloads — frequent checkpoints increase WAL volume via full_page_writes. Raising max_wal_size to 4-8GB spreads checkpoints; pair with checkpoint_completion_target=0.9. pg_stat_bgwriter buffers_checkpoint reveals spike severity.',
        production:'Replica lag spiked every 5 min correlating with checkpoint. Raised max_wal_size from 1GB to 8GB, checkpoint_completion_target 0.9; spike IO dropped 60%, replay lag stabilized.',
        followUps:['Impact of checkpoint on replication lag?','What is immediate checkpoint vs scheduled?','How does full_page_writes interact with checkpoint frequency?','pg_checkpoint view in PG 15+?'],
        mistakes:['max_wal_size huge without recovery time analysis','checkpoint_completion_target=0 without spreading writes','Ignoring pg_stat_bgwriter after storage migration','Disabling full_page_writes to reduce WAL'],
        seniorInsights:'Checkpoint tuning is IO smoothing — graph buffers_checkpoint against replica lag.',
        commands:['SELECT * FROM pg_stat_bgwriter;', "SELECT name, setting FROM pg_settings WHERE name LIKE 'checkpoint%' OR name LIKE '%wal_size%';"],
        bestPractices:['Tune max_wal_size based on write throughput benchmarks','Use checkpoint_completion_target 0.9 on cloud disks','Monitor checkpoint duration after major tuning changes','Document expected recovery time with chosen WAL sizes'] }),
    q('pg-wal-3','wal','mvcc.js','medium','Very Common','Production Support',
      'How do you diagnose and fix WAL disk full conditions?',
      { interview:'WAL segments accumulate when archive_command fails, replication slots lag without consumption, or long pg_basebackup holds xmin. PostgreSQL stops accepting writes when pg_wal partition fills. Check pg_ls_waldir size, pg_replication_slots retained_wal, pg_stat_archiver, and standby replay lag.',
        explanation:'Each slot prevents removal of WAL until consumer advances confirmed_flush_lsn. inactive slot on dropped replica is classic leak. wal_keep_size retains extra WAL. max_slot_wal_keep_size limits retention per slot.',
        production:'Dev left replication slot "test_slot" after local replica deleted — 400GB WAL in 48h, primary read-only. Dropped slot; WAL recycled within hour.',
        followUps:['Difference between pg_current_wal_lsn and insert_lsn?','How does wal_keep_size differ from slot retention?','Can you relocate pg_wal to separate mount?','pg_wal_summary view usage?'],
        mistakes:['Creating slots without monitoring or TTL policy','Ignoring pg_stat_archiver.last_failed_time','Deleting WAL files manually to free space','No separate filesystem for pg_wal on write-heavy systems'],
        seniorInsights:'Runbook: WAL full → check slots → check archiver → check lagging standby → never rm WAL.',
        commands:['SELECT slot_name, active, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) AS retained FROM pg_replication_slots;','SELECT * FROM pg_stat_archiver;'],
        bestPractices:['Separate pg_wal mount with 20%+ headroom','Alert on replication slot inactive with retained WAL','Automate archive failure paging','Set max_slot_wal_keep_size to bound slot bloat'] }),
    q('pg-wal-4','wal','mvcc.js','hard','Common','Cloud Engineer',
      'Compare synchronous_commit settings and their impact on RPO and latency.',
      { interview:'synchronous_commit=on (default): commit waits for WAL flush — durable on single node. remote_write waits for standby to receive WAL; remote_apply waits for apply. off/local: commit returns after WAL written to buffer — faster but RPO window on crash.',
        explanation:'synchronous_standby_names controls which standbys count for quorum (FIRST n or ANY n). pg_stat_replication sync_state shows sync/async. Group commit batches multiple commits per WAL flush even with sync on.',
        production:'Analytics batch loader set synchronous_commit=local in session — 40% throughput gain acceptable for staging table truncated nightly. Production OLTP kept default on via role GUC.',
        followUps:['Quorum vs ANY in synchronous_standby_names?','Impact on logical replication?','Measuring commit latency?','Difference remote_write vs sync rep replay lag?'],
        mistakes:['Global synchronous_commit=off on financial OLTP','Expecting sync replica without synchronous_standby_names configured','Not testing failover RPO after sync policy change','Confusing remote_write with sync rep replay lag SLA'],
        seniorInsights:'Map business RPO to GUC: financial ledger = on + sync standby; clickstream buffer = local acceptable.',
        commands:['SHOW synchronous_commit;','SELECT application_name, sync_state, sync_priority FROM pg_stat_replication;', "SELECT name, setting FROM pg_settings WHERE name LIKE 'synchronous%';"],
        bestPractices:['Document RPO per workload and matching commit settings','Use sync standbys for zero-RPO failover targets','Never set synchronous_commit=off globally without review','Test primary crash recovery with chosen settings'] }),
    q('pg-wal-5','wal','mvcc.js','hard','Rare','DBA',
      'Design WAL archiving and monitoring for cross-region disaster recovery.',
      { interview:'Archive completed WAL via archive_command to S3/GCS with immutable versioning. Combine nightly pg_basebackup + continuous WAL for PITR. Monitor lag between pg_current_wal_lsn and last archived segment. DR restore: fetch base backup, replay WAL to target time via recovery.signal and restore_command.',
        explanation:'archive_mode=on, archive_command copies segments to object store. wal-g and pgBackRest automate base backup + WAL push. Cross-region: async replication for RPO minutes + WAL archive for RPO seconds on regional loss.',
        production:'Regional outage simulation: restored to DR region using wal-g backup 6h old + WAL replay to T-2min. RTO 90 min dominated by parallel restore of 2TB base.',
        followUps:['pg_combinebackup vs traditional restore?','How to validate WAL integrity before restore?','Impact of encryption on archive throughput?','recovery.signal vs recovery.conf PG 12+?'],
        mistakes:['Archive to same region/account as primary — loses DR value','No restore drills — discovered corrupt base backup at real DR','Missing timeline history files in archive','Underestimating WAL replay time in RTO calc'],
        seniorInsights:'DR architecture answer needs numbers: RPO from sync+archive, RTO from last restore drill.',
        commands:['SELECT * FROM pg_stat_archiver;','pgbackrest info','touch $PGDATA/recovery.signal;'],
        bestPractices:['Automate restore drills to secondary region quarterly','Store WAL in immutable object storage separate from primary','Monitor archive lag and failed_count continuously','Document timeline and target LSN recovery procedures'] }),
  ]},
  { topic: 'vacuum', file: 'mvcc.js', questions: [
    q('pg-vacuum-1','vacuum','mvcc.js','easy','Very Common','DBA',
      'What does VACUUM do in PostgreSQL and why is it not optional?',
      { interview:'VACUUM reclaims dead tuple space from UPDATE/DELETE, updates visibility map for index-only scans, advances freeze cutoff, and updates planner statistics (with ANALYZE option). It does not block normal reads/writes unlike VACUUM FULL which rewrites tables exclusively.',
        explanation:'Dead tuples remain until vacuum marks space reusable within pages. Visibility map bits enable index-only scans when all tuples on page visible. vacuum_cost_delay throttles IO. Manual VACUUM needed when autovacuum cannot keep up or before DDL requiring low bloat.',
        production:'Orders table 80GB with 40% dead tuples — sequential scans 10× slower. pg_stat_user_tables showed n_dead_tup=32M, last_autovacuum NULL for 2 weeks (autovacuum disabled on table). VACUUM ANALYZE orders; latency normalized.',
        followUps:['VACUUM vs VACUUM FULL vs pg_repack?','What is visibility map?','Does vacuum reclaim space to OS?','Impact of vacuum on replication slots xmin?'],
        mistakes:['Running VACUUM FULL on production without maintenance window','Disabling autovacuum on "critical" tables — opposite of intent','Expecting VACUUM to shrink disk file size to OS','Not vacuuming after massive DELETE before peak traffic'],
        seniorInsights:'Vacuum is garbage collection — treat n_dead_tup ratio as SLA metric. VACUUM FULL is last resort; pg_repack preferred for online rewrite.',
        commands:['VACUUM (VERBOSE, ANALYZE) orders;','SELECT relname, n_live_tup, n_dead_tup, round(100.0*n_dead_tup/nullif(n_live_tup+n_dead_tup,0),2) AS dead_pct FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 10;','SELECT * FROM pg_stat_progress_vacuum;'],
        bestPractices:['Never disable autovacuum globally or on high-churn tables','Monitor dead tuple ratio per table','Use pg_repack instead of VACUUM FULL when online shrink needed','Schedule manual VACUUM after bulk deletes'] }),
    q('pg-vacuum-2','vacuum','mvcc.js','medium','Common','Database Engineer',
      'Explain vacuum freeze, visibility map, and free space map (FSM).',
      { interview:'Freeze marks tuples with xmin older than vacuum_freeze_min_age as frozen — immune to xid wraparound comparison. Visibility map tracks all-visible and all-frozen pages enabling index-only scans and skipping freeze checks. FSM tracks free space within pages for INSERT/UPDATE placement.',
        explanation:'All-visible pages allow index-only scans without heap visit when visibility map bit set. FSM stored in separate fork; VACUUM updates FSM with reclaimable space. pg_visibility extension inspects map. Aggressive freeze during anti-wraparound vacuum can increase IO.',
        production:'Index-only scan never chosen on events table — visibility map never set because long-running reporting transaction held snapshot. pg_stat_activity showed 6h idle in transaction on read replica connection to primary. Killed session; next vacuum set all-visible bits; IO dropped 30%.',
        followUps:['How does vacuum_freeze_table_age trigger aggressive freeze?','Can FSM be corrupted and how to detect?','Index-only scan prerequisites?','Impact of fillfactor on FSM?'],
        mistakes:['Long snapshots preventing all-visible page marking','Ignoring index-only scan opportunities after vacuum','Assuming freeze eliminates need for regular vacuum','Not monitoring pg_stat_all_tables last_vacuum freeze stats'],
        seniorInsights:'Index-only scan is free performance when VM bits set — debug why vacuum cannot set them (long xact, lock).',
        commands:['CREATE EXTENSION pg_visibility;','SELECT * FROM pg_visibility_map(\'events\'::regclass) LIMIT 5;','EXPLAIN SELECT id FROM events WHERE created_at > now()-interval \'1 day\';'],
        bestPractices:['Kill or timeout idle in transaction sessions','Verify index-only scans on large indexed tables post-vacuum','Monitor wraparound age alongside regular vacuum','Use pg_stat_progress_vacuum during long runs'] }),
    q('pg-vacuum-3','vacuum','mvcc.js','medium','Very Common','Production Support',
      'When should you use VACUUM FULL versus pg_repack versus routine VACUUM?',
      { interview:'Routine VACUUM reclaims space within pages without exclusive lock — use continuously via autovacuum. VACUUM FULL rewrites entire table with ACCESS EXCLUSIVE lock — shrinks file to OS but blocks all access. pg_repack rewrites online using triggers/logs with brief lock at end.',
        explanation:'Bloat from non-HOT updates leaves pages underfilled — routine vacuum cannot compact pages, only reuse space. pg_repack needs primary key and free disk ~ table size. VACUUM FULL simpler but unacceptable downtime on large OLTP tables. pg_squeeze and pg_repack are alternatives.',
        production:'30GB table bloat after archive delete — VACUUM reduced dead tuples but file size unchanged at 30GB. pg_repack -t archive_events during low traffic; file shrunk to 8GB with 2-minute exclusive lock at swap.',
        followUps:['Does pg_repack work on partitioned tables?','REINDEX CONCURRENTLY vs vacuum for index bloat?','How to measure bloat without pgstattuple?','Cloud managed PG bloat options?'],
        mistakes:['VACUUM FULL on multi-TB table during business hours','pg_repack without disk space for copy','Routine vacuum expecting OS-level shrink','Ignoring toast table bloat separately'],
        seniorInsights:'Present decision tree: dead tuples → VACUUM; page density → pg_repack; emergency shrink + downtime OK → VACUUM FULL.',
        commands:['CREATE EXTENSION pgstattuple;','SELECT * FROM pgstattuple(\'archive_events\');','pg_repack -d appdb -t archive_events','VACUUM FULL VERBOSE archive_events; -- maintenance only'],
        bestPractices:['Prefer pg_repack for online bloat remediation','Measure bloat with pgstattuple before choosing tool','Ensure 2× table size free disk for repack','Schedule VACUUM FULL only with explicit downtime approval'] }),
    q('pg-vacuum-4','vacuum','mvcc.js','hard','Common','DBA',
      'How does vacuum interact with replication slots, hot standby, and conflict resolution?',
      { interview:'Vacuum on primary removes dead tuples still needed by standby queries — catalog_xmin held by slot or hot standby feedback prevents cleanup causing bloat. Standby max_standby_streaming_delay can cancel long queries conflicting with vacuum cleanup. Logical slots hold xmin until consumed.',
        explanation:'Replication slot pg_replication_slots.catalog_xmin shows oldest xmin slot needs. hot_standby_feedback sends standby xmin to primary delaying vacuum. Conflicts on standby: snapshot too old if vacuum removed rows standby query needs. Monitor pg_stat_database_conflicts on standby.',
        production:'Logical replication slot on CDC pipeline stalled 48h — primary orders table bloat 60GB. catalog_xmin frozen by unconsumed slot. Consumer caught up; VACUUM reclaimed space. Added max_slot_wal_keep_size and consumer lag alert.',
        followUps:['hot_standby_feedback trade-offs?','vacuum_defer_cleanup_age purpose?','Logical vs physical slot xmin behavior?','Canceling standby queries vs primary bloat?'],
        mistakes:['hot_standby_feedback=on without monitoring primary bloat','Orphan logical replication slots after consumer decommission','Ignoring pg_stat_database_conflicts on replicas','max_standby_streaming_delay=-1 allowing unlimited bloat'],
        seniorInsights:'CDC slots are vacuum enemies — treat consumer lag as primary storage incident. Cap slot retention and page on catalog_xmin age.',
        commands:['SELECT slot_name, catalog_xmin, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), confirmed_flush_lsn)) FROM pg_replication_slots;','SELECT * FROM pg_stat_database_conflicts WHERE datname = current_database();','SHOW hot_standby_feedback;'],
        bestPractices:['Monitor catalog_xmin age per replication slot','Set max_slot_wal_keep_size and consumer lag SLOs','Use hot_standby_feedback judiciously with bloat alerts','Drop unused slots immediately'] }),
    q('pg-vacuum-5','vacuum','mvcc.js','hard','Rare','Database Engineer',
      'Troubleshoot a table where vacuum never completes or constantly restarts.',
      { interview:'Check pg_stat_progress_vacuum for phase and dead tuples remaining. Causes: infinite update churn on same pages, lock conflicts, wraparound vacuum competing, very large table with high cost delay, or blocked by long transaction xmin horizon. pg_locks shows blocking.',
        explanation:'Vacuum cannot truncate line pointers if xmin horizon blocked by idle transaction or slot. Constant updates on same rows create churn — vacuum never catches up. Reduce autovacuum_vacuum_cost_delay or increase autovacuum_max_workers temporarily. Consider partitioning hot append-only tables.',
        production:'Heartbeat table updated every second — autovacuum ran continuously, never finishing, CPU 30% vacuum. Fixed by UNLOGGED side table for heartbeats + periodic merge, and fillfactor=50 on main table.',
        followUps:['What are vacuum phases in pg_stat_progress_vacuum?','autovacuum_work_mem impact on large tables?','Partitioning to isolate vacuum scope?','Deadlock during vacuum freeze?'],
        mistakes:['Increasing cost delay when vacuum cannot keep up — wrong direction','Not identifying update churn root cause','Killing vacuum thinking it helps — worsens bloat','Single monolithic table for high-frequency updates'],
        seniorInsights:'If vacuum always active on one table, schema is wrong — partition or offload volatile columns before tuning GUCs forever.',
        commands:['SELECT * FROM pg_stat_progress_vacuum;','SELECT pid, state, xact_start, query FROM pg_stat_activity WHERE state != \'idle\' ORDER BY xact_start LIMIT 10;','SELECT pg_blocking_pids(pid) FROM pg_stat_activity WHERE query LIKE \'%vacuum%\';'],
        bestPractices:['Architect away from single-row high-frequency update antipattern','Watch pg_stat_progress_vacuum during incidents','Resolve xmin horizon blockers before forcing vacuum','Partition largest churn tables'] }),
  ]},
  { topic: 'autovacuum', file: 'mvcc.js', questions: [
    q('pg-autovacuum-1','autovacuum','mvcc.js','easy','Very Common','DBA',
      'How does autovacuum decide when to vacuum and analyze a table?',
      { interview:'Autovacuum launcher forks workers when dead tuple count exceeds autovacuum_vacuum_scale_factor × reltuples + autovacuum_vacuum_threshold (similar formula for analyze). Anti-wraparound vacuum triggers regardless when relfrozenxid age exceeds autovacuum_freeze_max_age. Per-table settings via ALTER TABLE storage parameters override globals.',
        explanation:'Default scale factor 0.2 means 20% dead tuples before vacuum — too lazy for large tables (10M rows → 2M dead). Set autovacuum_vacuum_scale_factor=0.01 on hot tables. autovacuum_analyze_scale_factor controls stats refresh. pg_stat_user_tables last_autovacuum shows activity.',
        production:'10M row inventory table waited for 2M dead tuples before vacuum — caused periodic latency spikes. ALTER TABLE inventory SET (autovacuum_vacuum_scale_factor = 0.02, autovacuum_analyze_scale_factor = 0.01); spikes eliminated.',
        followUps:['How many autovacuum workers default?','autovacuum_vacuum_insert_scale_factor PG 13+?','Does autovacuum run during replication?','log_autovacuum_min_duration usage?'],
        mistakes:['Leaving default 0.2 scale factor on million-row OLTP tables','Disabling autovacuum globally via autovacuum=off','Not setting per-table params on append-heavy fact tables','Ignoring anti-wraparound vacuum in monitoring'],
        seniorInsights:'Formula interview answer: threshold + scale_factor × n_live_tup. Always give numeric example for 50M row table.',
        commands:['SELECT relname, reloptions FROM pg_class WHERE relname = \'inventory\';',"SELECT name, setting FROM pg_settings WHERE name LIKE 'autovacuum%';",'ALTER TABLE inventory SET (autovacuum_vacuum_scale_factor = 0.02);'],
        bestPractices:['Lower scale factor on large high-churn tables','Enable log_autovacuum_min_duration to log slow vacuums','Never disable autovacuum except brief debugging with ticket','Document per-table autovacuum overrides in schema'] }),
    q('pg-autovacuum-2','autovacuum','mvcc.js','medium','Common','Database Engineer',
      'Tune autovacuum for high-write OLTP workloads without starving the database.',
      { interview:'Increase autovacuum_max_workers (requires max_worker_processes headroom), reduce autovacuum_vacuum_cost_delay (or set to 0 for aggressive), raise autovacuum_vacuum_cost_limit, and set maintenance_work_mem higher for vacuum sort phases. Per-table scale factors more impactful than global knobs.',
        explanation:'Vacuum cost based on page reads/writes/delay; defaults throttle heavily on busy systems. autovacuum_naptime controls launcher frequency. Too aggressive autovacuum competes with OLTP IO — monitor pg_stat_bgwriter and disk latency. RDS Parameter groups expose same GUCs with limits.',
        production:'Flash sale write storm — dead tuples piled faster than autovacuum. Temporarily set autovacuum_vacuum_cost_delay=0 and autovacuum_max_workers=6 on primary; reverted post-event. Added per-table tuning on orders and order_items.',
        followUps:['maintenance_work_mem vs autovacuum_work_mem PG 16+?','IO concurrency and autovacuum on SSD?','Does autovacuum hold locks that block OLTP?','autovacuum worker per database limit?'],
        mistakes:['autovacuum_max_workers=10 without max_worker_processes increase','Permanent cost_delay=0 on IO-saturated disk','Tuning globals instead of per-table on one problematic relation','Ignoring autovacuum duration in logs'],
        seniorInsights:'Autovacuum tuning is table-specific first. Global aggression is for incidents only — revert and fix scale factors.',
        commands:['ALTER SYSTEM SET autovacuum_max_workers = 5;','ALTER SYSTEM SET autovacuum_vacuum_cost_delay = 2;', 'SELECT pg_reload_conf();','SELECT * FROM pg_stat_progress_vacuum;'],
        bestPractices:['Tune per-table before global GUC changes','Correlate autovacuum with disk IO metrics','Revert temporary aggressive settings post-incident','Size maintenance_work_mem for largest table vacuum needs'] }),
    q('pg-autovacuum-3','autovacuum','mvcc.js','medium','Very Common','Production Support',
      'Diagnose "autovacuum not keeping up" on a production cluster.',
      { interview:'Check pg_stat_user_tables n_dead_tup vs n_live_tup, last_autovacuum timestamps, pg_stat_progress_vacuum active workers, blocked xmin from pg_stat_activity and pg_replication_slots, and autovacuum settings. Compare vacuum rate to update/delete rate from pg_stat_user_tables n_tup_upd/n_tup_del.',
        explanation:'Common root causes: autovacuum disabled on table, scale factor too high, all workers busy on other tables, replication slot blocking cleanup, vacuum cost throttling, or table too large for naptime cycle. pg_stat_bgwriter and OS IO wait indicate resource starvation.',
        production:'Dashboard showed autovacuum workers always busy but events table n_dead_tup growing. Five workers vacuuming small dimension tables; events had no per-table tuning. Set storage params on events, increased max_workers to 4, dead ratio stabilized under 5%.',
        followUps:['How to prioritize which table to tune first?','pg_prewarm interaction with autovacuum?','Autovacuum on standby PG 13+?','toast table autovacuum separately?'],
        mistakes:['Adding indexes instead of fixing vacuum backlog','Manual VACUUM FULL as first response','Not checking replication slot catalog_xmin','Assuming more CPU fixes IO-bound vacuum'],
        seniorInsights:'Rank tables by n_dead_tup × seq_scan count from pg_stat_user_tables — highest impact first.',
        commands:['SELECT relname, n_dead_tup, n_live_tup, last_autovacuum, last_autoanalyze FROM pg_stat_user_tables ORDER BY n_dead_tup DESC LIMIT 15;','SELECT count(*) FROM pg_stat_progress_vacuum;','SELECT slot_name, catalog_xmin FROM pg_replication_slots;'],
        bestPractices:['Dashboard dead tuple ratio top 20 tables','Alert last_autovacuum > 24h on high-churn tables','Review slot xmin during vacuum incidents','Capacity plan autovacuum workers with table count'] }),
    q('pg-autovacuum-4','autovacuum','mvcc.js','hard','Common','DBA',
      'Explain anti-wraparound autovacuum and emergency vacuum behavior.',
      { interview:'When relfrozenxid age approaches autovacuum_freeze_max_age (default 200M), autovacuum triggers aggressive anti-wraparound vacuum with zero cost delay, even on large tables, to advance relfrozenxid. If age exceeds vacuum_freeze_table_age, vacuum marks table urgently. Catastrophic age forces shutdown.',
        explanation:'Anti-wraparound vacuum can IO-saturate disk and contend with OLTP. vacuum_freeze_min_age and vacuum_freeze_table_age control urgency. multixact has parallel autovacuum_multixact_freeze_max_age. Monitor age(relfrozenxid) proactively — do not wait for emergency.',
        production:'Alert at age 150M triggered planned VACUUM FREEZE on top 5 tables over weekend. Avoided emergency autovacuum during Monday peak that previously caused 40% latency increase.',
        followUps:['Difference vacuum_freeze_min_age vs autovacuum_freeze_max_age?','Can anti-wraparound be deferred?','Impact on logical replication during freeze vacuum?','pg_resetxlog never for wraparound — why?'],
        mistakes:['No datfrozenxid monitoring until emergency','Long prepared xacts blocking freeze','Assuming regular vacuum always advances relfrozenxid enough','Disabling autovacuum on large old tables'],
        seniorInsights:'Wraparound vacuum is the database saving itself — your job is never reaching it via proactive freeze monitoring.',
        commands:['SELECT relname, age(relfrozenxid) AS freeze_age FROM pg_class WHERE relkind=\'r\' ORDER BY 2 DESC LIMIT 10;','SELECT datname, age(datfrozenxid) FROM pg_database;','VACUUM (FREEZE) critical_table;'],
        bestPractices:['Alert relfrozenxid age at 50% of autovacuum_freeze_max_age','Schedule proactive freeze vacuums on largest tables','Clear prepared xacts and stale slots blocking freeze','Include wraparound metrics in weekly DBA review'] }),
    q('pg-autovacuum-5','autovacuum','mvcc.js','hard','Rare','Cloud Engineer',
      'Design autovacuum monitoring and alerting strategy for 500+ table RDS PostgreSQL fleet.',
      { interview:'Export pg_stat_user_tables metrics via postgres_exporter: n_dead_tup ratio, last_autovacuum age, autovacuum_count, table size. Alert thresholds per size tier. Track datfrozenxid age cluster-wide. Correlate with Performance Insights IO spikes and replication slot lag. Automate per-table tuning via Terraform postgrestablers.',
        explanation:'Fleet-wide: Prometheus recording rules for max dead ratio, tables without autovacuum in 7 days, freeze age max. RDS lacks pg_repack — plan table maintenance windows. Use pg_cron for off-peak VACUUM on known problem tables. CloudWatch alarms on FreeStorageSpace and ReplicationSlotDiskUsage.',
        production:'Implemented Datadog monitors on custom query max(dead_pct) by database — paged when >15% on any table >10GB. Reduced Sev2 incidents 70%. Per-table autovacuum params stored in schema migration repo.',
        followUps:['postgres_exporter autovacuum metrics?','RDS autovacuum limits by instance class?','Aurora vs RDS autovacuum differences?','Automating ALTER TABLE SET autovacuum via migration?'],
        mistakes:['Single global dead tuple threshold for 1KB vs 1TB tables','No freeze age monitoring on managed PG','Ignoring toast bloat in fleet dashboards','Alert fatigue without severity tiers by table criticality'],
        seniorInsights:'Fleet strategy: tier tables by size and business criticality — different thresholds and runbooks per tier.',
        commands:['SELECT relname, pg_size_pretty(pg_total_relation_size(relid)), n_dead_tup FROM pg_stat_user_tables WHERE pg_total_relation_size(relid) > 10737418240 ORDER BY n_dead_tup DESC;','SELECT datname, age(datfrozenxid) FROM pg_database;'],
        bestPractices:['Tiered alerting by table size and criticality','Automate autovacuum params in schema migrations','Weekly report top 10 bloated tables per database','Integrate slot lag with autovacuum dashboards'] }),
  ]},
];
