/** PostgreSQL registry data — replication + index-types */
import { q } from './_postgresqlRegistryData.part1.mjs';

export const PART3 = [
  { topic: 'streaming-replication', file: 'replication.js', questions: [
    q('pg-streaming-replication-1','streaming-replication','replication.js','easy','Very Common','DBA',
      'How does PostgreSQL streaming replication work between primary and standby?',
      { interview:'Standby connects to primary walsender process; primary streams WAL records as they are generated. Standby walreceiver writes to pg_wal and startup process replays via recovery. Synchronous mode waits for standby flush/apply per synchronous_standby_names. Replication uses physical WAL — byte-for-byte replica.',
        explanation:'Primary pg_stat_replication shows connected standbys, sent_lsn, write_lag, flush_lag, replay_lag. Standby hot_standby=on allows read queries during recovery. recovery_min_apply_delay can lag apply intentionally. Cascading replication: standby feeds downstream standbys.',
        production:'New standby provisioned via pg_basebackup -R -X stream -C -S standby1; slot ensured WAL retention during catch-up. pg_stat_replication replay_lag stabilized under 200ms after initial sync.',
        followUps:['Difference sent_lsn vs replay_lsn?','How to add standby without downtime?','Hot standby feedback purpose?','Cascading vs direct replication?'],
        mistakes:['No replication slot during pg_basebackup catch-up — WAL removed','promote standby without checking timeline divergence','Monitoring only flush_lag ignoring replay_lag on hot standby queries','max_wal_senders too low blocking new standbys'],
        seniorInsights:'Always create physical replication slot named per standby. replay_lag is what users feel on read replicas.',
        commands:['SELECT application_name, state, sync_state, sent_lsn, replay_lsn, replay_lag FROM pg_stat_replication;','pg_basebackup -h primary -D /var/lib/pgsql/standby -U replicator -Fp -Xs -P -R','SELECT pg_create_physical_replication_slot(\'standby1\');'],
        bestPractices:['Use replication slots for each standby','Monitor replay_lag not just connection state','Automate standby provisioning with pg_basebackup','Test promotion procedure quarterly'] }),
    q('pg-streaming-replication-2','streaming-replication','replication.js','medium','Common','Database Engineer',
      'Diagnose and reduce replication lag on a hot standby.',
      { interview:'Measure write_lag, flush_lag, replay_lag in pg_stat_replication. Causes: standby IO slower than primary WAL generation, long queries blocking recovery, insufficient wal_receiver/wal_writer, network bandwidth, or hot standby conflicts. Check pg_stat_database_conflicts and standby pg_is_in_recovery().',
        explanation:'Replay is single-threaded for WAL apply — CPU rarely bottleneck; IO and lock conflicts are. standby max_standby_streaming_delay cancels queries blocking recovery. wal_compression on primary reduces network. pg_wal_receiver_status on standby shows receive rate.',
        production:'Replica replay_lag climbed to 30s during primary checkpoint spikes. Standby on gp2 with low IOPS; migrated to io2 with 16k IOPS, added recovery_prefetch (PG 15), lag dropped to sub-second.',
        followUps:['recovery_prefetch and wal_decode in PG 15+?','Impact of large transactions on replay lag?','Parallel apply for logical vs physical?','Synchronous rep latency vs async lag?'],
        mistakes:['Read-heavy workload on standby without conflict monitoring','Standby disk tier lower than primary','Ignoring checkpoint-induced lag spikes','max_standby_streaming_delay=-1 forever'],
        seniorInsights:'Lag spikes at checkpoint = standby IO problem. Steady lag = WAL generation exceeds replay — IO or conflicts.',
        commands:['SELECT * FROM pg_stat_replication;','SELECT * FROM pg_stat_database_conflicts;','SELECT pg_is_in_recovery();','SHOW max_standby_streaming_delay;'],
        bestPractices:['Match or exceed primary storage IOPS on standbys','Monitor pg_stat_database_conflicts on replicas','Use dedicated replication network if cross-AZ','Set sensible max_standby_streaming_delay with alerting'] }),
    q('pg-streaming-replication-3','streaming-replication','replication.js','medium','Very Common','Production Support',
      'What are replication slots and why should every standby use one?',
      { interview:'Replication slots track consumer LSN on primary — WAL segments not recycled until consumed. Physical slots tied to standby restart_lsn; logical slots to confirmed_flush_lsn. pg_replication_slots shows retained WAL. Without slot, standby falling behind loses WAL and needs rebuild.',
        explanation:'pg_create_physical_replication_slot creates durable slot surviving restarts. inactive slot still retains WAL — operational hazard. max_replication_slots limits count. max_slot_wal_keep_size bounds disk risk per slot.',
        production:'Standby rebuild required after 4h network partition — no slot, WAL gone. Post-incident: mandatory slot per standby via Patroni config, alert on pg_wal_lsn_diff > 1GB.',
        followUps:['Drop slot safely when decommissioning standby?','Logical slot pgoutput vs wal2json?','Temporary vs permanent slots?','Slot sync with pg_basebackup -C?'],
        mistakes:['Orphan slots after failed experiments','Creating logical slots without consumer monitoring','max_replication_slots default too low for HA + CDC','Deleting slot while standby still running'],
        seniorInsights:'Slot = contract that primary keeps WAL for consumer. Orphan slot is a disk-fill time bomb.',
        commands:['SELECT * FROM pg_replication_slots;','SELECT pg_create_physical_replication_slot(\'replica1\', true);','SELECT pg_drop_replication_slot(\'old_slot\');','SELECT pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) FROM pg_replication_slots;'],
        bestPractices:['One named slot per standby and logical consumer','Alert inactive slots with retained WAL','Document slot ownership in infrastructure registry','Set max_slot_wal_keep_size as safety valve'] }),
    q('pg-streaming-replication-4','streaming-replication','replication.js','hard','Common','Cloud Engineer',
      'Configure synchronous replication with quorum for RPO zero across multiple AZs.',
      { interview:'synchronous_standby_names = \'FIRST 2 (sync1, sync2, sync3)\' requires two listed standbys to acknowledge commit. ANY 1 (...) allows any one of set. pg_stat_replication sync_state=sync on acknowledged standbys. Trade-off: commit latency = slowest sync standby RTT + flush time.',
        explanation:'Quorum protects against single AZ loss without blocking on one slow replica. priority in synchronous_standby_names orders preference. synchronous_commit=remote_apply strongest — waits apply not just flush. Cloud: cross-AZ latency 1-3ms adds to commit p99.',
        production:'Financial ledger required sync rep; FIRST 1 caused commits blocked when single AZ standby maintenance. Switched to FIRST 2 of 3 sync standbys — survived AZ outage with zero committed transaction loss.',
        followUps:['Failover when sync standby down — commits block?','synchronous_commit remote_write vs on?','Patroni synchronous_mode vs PostgreSQL native?','Aurora synchronous replica semantics?'],
        mistakes:['FIRST 1 with only one sync standby — no AZ redundancy','All standbys async — believing HA without RPO guarantee','Not testing commit latency impact before enabling sync','Forgetting to update synchronous_standby_names after topology change'],
        seniorInsights:'Quorum sync is the sweet spot for multi-AZ — explain FIRST 2 of 3 with commit latency math.',
        commands:["ALTER SYSTEM SET synchronous_standby_names = 'FIRST 2 (az1, az2, az3)';",'SELECT application_name, sync_state, sync_priority FROM pg_stat_replication;','SELECT pg_reload_conf();'],
        bestPractices:['Use quorum sync for multi-AZ RPO zero','Load test commit latency with sync enabled','Automate synchronous_standby_names updates in failover tooling','Monitor sync_state and commit latency p99'] }),
    q('pg-streaming-replication-5','streaming-replication','replication.js','hard','Rare','DBA',
      'Recover a standby that has fallen behind or has timeline divergence after promotion.',
      { interview:'If WAL missing: rebuild via pg_basebackup or pgBackRest restore. Timeline divergence after promote/failback: pg_rewind re-syncs diverged standby to new primary timeline using WAL overlap. pg_upgrade and pg_wal_replay_resume for controlled catch-up. Never manually edit pg_control without expert guidance.',
        explanation:'pg_rewind requires wal_log_hints or data_checksums enabled at init. Standby rejoins as replica after rewind + restart with primary_conninfo. Multiple promotions create timeline history files in pg_wal/archive. pg_switch_wal before promotion ensures clean segment boundary.',
        production:'Failed back to old primary after split-brain — timelines diverged. pg_rewind --target-pgdata=/var/lib/pgsql/data --source-server=connstr succeeded; rejoined as replica in 20 min vs 6h full rebuild.',
        followUps:['When pg_rewind fails?','pg_verifybackup role?','Rebuild vs rewind decision tree?','pg_resetwal danger scenarios?'],
        mistakes:['Manual copy of data directory without matching timeline','Skipping data_checksums then needing rewind later','Promoting multiple standbys without fencing old primary','pg_resetwal as first troubleshooting step'],
        seniorInsights:'Enable data_checksums + wal_log_hints at cluster birth — enables pg_rewind and corruption detection.',
        commands:['pg_rewind --target-pgdata=$PGDATA --source-server="host=primary dbname=postgres user=rewind"','pg_controldata $PGDATA | grep Timeline','pg_basebackup -h newprimary -D $PGDATA -Fp -Xs -P -R'],
        bestPractices:['Enable data_checksums on new clusters','Document rewind vs rebuild criteria in runbook','Fence old primary before any promotion','Test pg_rewind in staging after simulated split-brain'] }),
  ]},
  { topic: 'logical-replication', file: 'replication.js', questions: [
    q('pg-logical-replication-1','logical-replication','replication.js','easy','Very Common','Database Engineer',
      'What is logical replication and how does it differ from streaming replication?',
      { interview:'Logical replication decodes WAL to row-level changes via replication slot and publishes to subscriber via pgoutput plugin. Supports table-level publication, cross-version upgrade, and selective replication. Physical streaming replicates entire cluster byte-identical; logical allows heterogeneous targets and transformations.',
        explanation:'Publisher: CREATE PUBLICATION, wal_level=logical. Subscriber: CREATE SUBSCRIPTION connects to publisher slot. Apply workers insert/update/delete on subscriber. Initial sync copies existing data. Conflicts on subscriber possible with concurrent writes. pg_stat_subscription tracks apply lag.',
        production:'Migrating PG 13 → 16: logical replication publication on old primary, subscription on new cluster, cutover after lag zero — near-zero downtime vs pg_dump.',
        followUps:['wal_level logical WAL overhead?','Publication FOR ALL TABLES vs specific?','Bidirectional logical replication pitfalls?','DDL replication support PG 15+?'],
        mistakes:['wal_level not logical before enabling publication','No primary key on published table — UPDATE/DELETE cannot apply','Writing to subscriber tables also receiving replication — conflicts','Ignoring replication slot disk on publisher'],
        seniorInsights:'Logical rep is the modern upgrade path and CDC mechanism — know publication/subscription/slot triangle.',
        commands:['CREATE PUBLICATION orders_pub FOR TABLE orders, order_items;','CREATE SUBSCRIPTION orders_sub CONNECTION \'host=pub dbname=app\' PUBLICATION orders_pub;','SELECT * FROM pg_stat_subscription;'],
        bestPractices:['Ensure PRIMARY KEY on all published tables','Monitor publisher slot lag and retained WAL','Use logical rep for major version upgrades','Avoid concurrent writes on subscriber without conflict strategy'] }),
    q('pg-logical-replication-2','logical-replication','replication.js','medium','Common','DBA',
      'How do you handle logical replication conflicts and apply errors on the subscriber?',
      { interview:'Subscriber apply errors pause subscription — pg_stat_subscription shows worker state. Conflicts when subscriber modified same row: default uses ERROR and stops. Options: disable subscription, fix data, skip LSN with pg_replication_origin_advance (dangerous), or use conflict-free subscriber (read-only). PG 16+ improved conflict policies.',
        explanation:'Common errors: duplicate key, missing row for UPDATE, FK violations. subscriber_disabled stops apply. ALTER SUBSCRIPTION ... DISABLE/ENABLE. pg_logical_emit_message for custom signaling. Transformations via BEFORE triggers on subscriber risky.',
        production:'CDC subscriber had manual hotfix UPDATE conflicting with replication — subscription stopped 2h. Disabled subscription, reconciled 47 rows via diff script, resumed from pg_stat_subscription latest_lsn after verification.',
        followUps:['COPY vs INSERT for initial sync?','Replication identity FULL vs DEFAULT?','Filter rows in publication?','Logical decoding plugin comparison?'],
        mistakes:['Manual subscriber writes on replicated tables','Advancing LSN without understanding skipped transactions','No alerting on pg_stat_subscription worker errors','REPLICA IDENTITY FULL on wide tables — WAL bloat'],
        seniorInsights:'Subscriber is read-only unless you have explicit bidirectional design with conflict resolution.',
        commands:['ALTER SUBSCRIPTION orders_sub DISABLE;','SELECT subname, received_lsn, latest_end_lsn, last_msg_receipt_time FROM pg_stat_subscription;','ALTER SUBSCRIPTION orders_sub ENABLE;','ALTER TABLE orders REPLICA IDENTITY FULL; -- only if needed'],
        bestPractices:['Keep subscriber apply tables read-only for CDC','Alert on subscription worker not running','Document conflict reconciliation procedure','Use REPLICA IDENTITY DEFAULT unless UPDATE on non-PK columns'] }),
    q('pg-logical-replication-3','logical-replication','replication.js','medium','Very Common','Production Support',
      'Monitor logical replication lag and slot health on the publisher.',
      { interview:'pg_stat_replication for logical walsender shows sent_lsn; pg_replication_slots confirmed_flush_lsn vs pg_current_wal_lsn measures lag bytes. pg_stat_subscription on subscriber shows apply lag. inactive logical slot retains WAL indefinitely — monitor pg_wal_lsn_diff.',
        explanation:'Logical slots named in CREATE SUBSCRIPTION create_slot option. pg_stat_replication.application_name matches subscription. Consumer lag in Debezium/Kafka visible separately — DB slot lag is authoritative for WAL retention risk.',
        production:'Debezium connector paused weekend — logical slot retained 180GB WAL. Added alert: pg_wal_lsn_diff > 10GB on any logical slot. Consumer auto-restart policy added.',
        followUps:['pgoutput vs test_decoding?','Slot export snapshot for consistent CDC start?','Multiple subscriptions one publication?','Drop subscription slot cleanup?'],
        mistakes:['Logical slot without active consumer','Not naming slots — hard to trace ownership','Monitoring Kafka lag only not PG slot lag','max_replication_slots exhausted by orphaned logical slots'],
        seniorInsights:'CDC pipeline health starts at pg_replication_slots on publisher — Kafka lag is downstream.',
        commands:['SELECT slot_name, plugin, active, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), confirmed_flush_lsn)) AS lag FROM pg_replication_slots WHERE slot_type=\'logical\';','SELECT * FROM pg_stat_replication WHERE application_name LIKE \'sub_%\';'],
        bestPractices:['Tag slots with owner and consumer system in name','Page on slot lag bytes not just active=false','Drop subscription WITH (slot_name) on decommission','Capacity plan max_replication_slots for HA + CDC'] }),
    q('pg-logical-replication-4','logical-replication','replication.js','hard','Common','Database Engineer',
      'Perform zero-downtime major version upgrade using logical replication.',
      { interview:'Publisher on old version, subscriber on new: CREATE PUBLICATION on source, CREATE SUBSCRIPTION with copy_data=true on target. Wait sync lag zero. Stop writes briefly, verify counts, redirect apps to new cluster, drop old subscription. pglogical or native logical rep depending on version jump.',
        explanation:'Limitations: sequences not replicated — sync via pg_dump --data-only or setval. Large objects need separate handling. Extensions may differ between versions. DDL on PG 15+ can replicate via publication. Cutover window for final LSN catch-up typically seconds to minutes.',
        production:'PG 12→16 upgrade: logical rep to new RDS instance, pg_dump --data-only for sequences, 30-second write freeze at cutover, rollback plan kept old cluster read-only 48h.',
        followUps:['Sequence sync strategies?','Schema drift before cutover?','Filter publication for unsupported types?','Rollback if cutover fails?'],
        mistakes:['Forgetting sequence synchronization','Different extension versions on subscriber','Cutover without row count verification','Dropping old cluster before soak period'],
        seniorInsights:'Logical upgrade is standard for large DBs where pg_upgrade downtime unacceptable — rehearse twice.',
        commands:['CREATE PUBLICATION upgrade_pub FOR ALL IN SCHEMA public;','CREATE SUBSCRIPTION upgrade_sub CONNECTION \'...\' PUBLICATION upgrade_pub WITH (copy_data = true, create_slot = true);','SELECT pg_size_pretty(pg_wal_lsn_diff(received_lsn, latest_end_lsn)) FROM pg_stat_subscription;'],
        bestPractices:['Rehearse full upgrade on clone','Sync sequences explicitly at cutover','Verify row counts per table before switch','Keep old cluster available for rollback window'] }),
    q('pg-logical-replication-5','logical-replication','replication.js','hard','Rare','Cloud Engineer',
      'Design logical replication architecture for multi-region read replicas with selective table sync.',
      { interview:'Regional publisher in home region; subscribers in EU/APAC with publications filtered to regional-relevant tables. Avoid bidirectional unless using conflict-free CRDT patterns. Network: VPN/private link for replication connection. Slot per subscriber per region. RPO = replication lag; regional subscriber for read locality not DR alone.',
        explanation:'CREATE PUBLICATION pub_eu FOR TABLE eu_customers, eu_orders. Row filters PG 15+ WHERE clause in publication. Subscriber connection string with SSL. Cross-region lag higher — async by nature. Combine with physical WAL archive for regional DR.',
        production:'Global app replicated 200 tables to EU subscriber — unnecessary WAL and 45s lag. Split publications: global_read_pub (20 tables) per region; cut lag to 3s and halved slot WAL retention.',
        followUps:['Publication row filters PG 15+?','Security for replication connection cross-cloud?','Citus vs logical for sharding?','Subscriber connection failover?'],
        mistakes:['Replicating entire database cross-region unnecessarily','Bidirectional without conflict strategy','Public replication port on internet','Single subscription for unrelated SLA tiers'],
        seniorInsights:'Selective publication is performance and compliance — replicate only what region needs.',
        commands:['CREATE PUBLICATION eu_pub FOR TABLE customers, orders WITH (publish = \'insert,update,delete\');','CREATE SUBSCRIPTION eu_sub CONNECTION \'host=primary sslmode=require\' PUBLICATION eu_pub;'],
        bestPractices:['Filter publications to regional data needs','Use private networking for replication traffic','Separate slots and subscriptions per region','Combine logical reads with WAL DR for RPO'] }),
  ]},
  { topic: 'physical-replication', file: 'replication.js', questions: [
    q('pg-physical-replication-1','physical-replication','replication.js','easy','Very Common','DBA',
      'Explain physical (binary) replication and what it copies.',
      { interview:'Physical replication ships raw WAL bytes to standby replaying identical changes at page level. Entire cluster replicated — all databases, roles, tablespaces. Standby is block-level clone evolving with primary. Base backup + continuous WAL archive/stream completes replica.',
        explanation:'Requires wal_level=replica or logical. Standby recovery.conf/standby.signal configures primary_conninfo. hot_standby allows reads. Cannot replicate single database only — use logical for selective. pg_basebackup creates consistent snapshot using WAL.',
        production:'DR standby in secondary region initialized with pgBackRest backup + stream WAL; RPO 30s async. Quarterly promote test validates RTO.',
        followUps:['File-level vs block-level replication?','Tablespace replication paths?','Standby promotion steps?','pg_receivewal use case?'],
        mistakes:['Expecting selective DB replication with physical rep','wal_level=minimal on primary with standbys','Not testing promotion procedure','Different major PG version on standby without compatibility check'],
        seniorInsights:'Physical rep = full cluster clone. Interviewers ask when you would choose logical instead — selective tables, upgrades, CDC.',
        commands:['pg_basebackup -h primary -U repl -D /standby -Fp -Xs -P -R','SELECT pg_is_in_recovery();','SHOW wal_level;'],
        bestPractices:['wal_level=replica minimum for any standby','Automate base backup + replication setup','Test promotion regularly','Match major version on standbys'] }),
    q('pg-physical-replication-2','physical-replication','replication.js','medium','Common','Database Engineer',
      'What is timeline history and how does it affect failover?',
      { interview:'Each promotion increments timeline ID. WAL filenames encode timeline. History file records parent timeline and switchpoint LSN. Standby must follow new timeline after failover — pg_rewind or rebuild. pg_controldata shows current timeline.',
        explanation:'Failover: pg_ctl promote or trigger_file on standby. Old primary must be fenced — split-brain if still accepts writes. Patroni/etcd manages timeline and leader election. pg_waldump inspects WAL records across timelines.',
        production:'Manual promotion during outage forgot to fence old primary — split-brain 8 minutes until network isolation. Post-incident: Patroni with STONITH via cloud API disable old primary NIC.',
        followUps:['pg_ctl promote vs pg_promote()?','Timeline switch WAL record?','Failback procedure after false promotion?','etcd role in Patroni failover?'],
        mistakes:['Two primaries accepting writes simultaneously','Not updating application connection strings after promotion','Promoting lagging standby without acknowledging data loss','Ignoring timeline in WAL archive during PITR'],
        seniorInsights:'Timeline is PostgreSQL HA vocabulary — explain promotion creates new timeline branch.',
        commands:['pg_controldata $PGDATA | grep -E \'Timeline|checkpoint\'','pg_ctl promote -D $PGDATA','cat $PGDATA/pg_wal/*.history','patronictl failover'],
        bestPractices:['Automate failover with fencing (Patroni/k8s operator)','Never allow dual-primary writes','Update DNS/proxy on timeline change','Archive timeline history files with WAL'] }),
    q('pg-physical-replication-3','physical-replication','replication.js','medium','Very Common','Production Support',
      'Provision a new physical standby using pg_basebackup best practices.',
      { interview:'pg_basebackup -D target -Fp -Xs -P -R -C -S slotname from primary. -Xs streams WAL during backup for consistency. -R writes standby.signal and primary_conninfo. -C creates replication slot. Run during low IO if possible; parallel backup with -j for pgBackRest alternative.',
        explanation:'Backup takes base copy lock briefly at start checkpoint. Ensure enough disk on standby. recovery parameters in postgresql.auto.conf. Start standby without initdb — uses backup directory. Verify pg_stat_replication on primary shows connected standby.',
        production:'New replica added with pg_basebackup -j 4 via pgBackRest stanza — 800GB in 45 min vs 3h single-threaded. Slot prevented WAL loss during long backup.',
        followUps:['pg_basebackup vs pgBackRest vs wal-g?','Backup from replica allowed?','Encrypt base backup in transit?','Verify backup integrity before start?'],
        mistakes:['No replication slot during multi-hour basebackup','Starting standby without standby.signal in PG 12+','Insufficient disk for WAL accumulation during backup','Wrong primary_conninfo SSL settings'],
        seniorInsights:'Always -C -S slotname on pg_basebackup — textbook production answer.',
        commands:['pg_basebackup -h primary -U replicator -D /var/lib/pgsql/16/data -Fp -Xs -P -R -C -S replica2','pg_verifybackup /path/to/backup','SELECT * FROM pg_stat_replication;'],
        bestPractices:['Create replication slot during basebackup','Verify connectivity before cutover to standby','Use parallel backup tools for large datasets','Document replica provisioning in runbook'] }),
    q('pg-physical-replication-4','physical-replication','replication.js','hard','Common','Cloud Engineer',
      'Compare async vs sync physical replication for RPO/RTO in cloud deployments.',
      { interview:'Async: primary commits without waiting — RPO = last replicated WAL on failure (seconds to minutes). Sync: commit waits for standby persist — RPO zero for acknowledged commits. RTO depends on promotion automation — manual minutes, Patroni ~30-60s. Cross-region async common; sync usually same-region multi-AZ.',
        explanation:'Cloud RDS: Multi-AZ synchronous to standby in another AZ — RPO zero within region. Read replicas async — RPO > 0. Aurora storage replication different model — shared storage layer. Network partition with sync rep blocks commits if quorum lost.',
        production:'Chose same-region sync Multi-AZ for OLTP (RPO 0) + cross-region async read replica for DR (RPO 5 min acceptable). Documented data loss window for regional disaster explicitly.',
        followUps:['Aurora vs RDS Postgres replication model?','Quorum sync across 3 AZs?','RTO for manual vs automated promotion?','Synchronous rep and pgbouncer transaction pooling?'],
        mistakes:['Believing cross-region async replica gives RPO zero','No documented acceptable data loss for async DR','Sync rep across regions — commit latency unacceptable','Read replica promoted without measuring lag at failure time'],
        seniorInsights:'Draw RPO/RTO matrix: same-AZ sync, cross-AZ async, cross-region async — different numbers each.',
        commands:['SELECT application_name, sync_state, flush_lag, replay_lag FROM pg_stat_replication;','SHOW synchronous_standby_names;'],
        bestPractices:['Document RPO/RTO per replica tier explicitly','Same-region sync for zero RPO OLTP','Cross-region async for DR with tested promotion','Automate promotion to meet RTO SLO'] }),
    q('pg-physical-replication-5','physical-replication','replication.js','hard','Rare','DBA',
      'Troubleshoot a standby that cannot connect or stays in recovery not catching up.',
      { interview:'Check primary pg_hba for replication user, pg_stat_replication for connection attempts, standby postgresql.auto.conf primary_conninfo, network/firewall port 5432, replication slot existence, and pg_log on both sides. pg_is_in_recovery() true expected; pg_last_wal_receive_lsn vs pg_last_wal_replay_lsn on standby shows catch-up.',
        explanation:'Common failures: wrong repl user password, missing REPLICATION privilege, SSL mismatch, slot dropped while standby down, primary max_wal_senders exhausted, standby data directory from wrong timeline. walreceiver process absent in pg_stat_activity on standby.',
        production:'Standby stuck: primary_conninfo pointed to decommissioned ELB after failover. Updated auto.conf via Patroni, restarted standby — reconnected in 30s. Added Patroni DCS-managed conninfo to prevent drift.',
        followUps:['pg_hba replication keyword line format?','recovery_min_apply_delay misconfiguration?','Standby readonly queries blocking replay?','Reinit standby without full cluster rebuild?'],
        mistakes:['Replication user with LOGIN but not REPLICATION attribute','Firewall allows 5432 app but blocks standby IP','Manual auto.conf edits overwritten by Patroni','Deleting standby data dir partial files corrupt state'],
        seniorInsights:'Split troubleshooting: connection (hba, network, auth) vs catch-up (slot, lag, conflicts) — different symptoms.',
        commands:['# pg_hba.conf: host replication repl 10.0.0.0/16 scram-sha-256','SELECT rolreplication FROM pg_roles WHERE rolname=\'repl\';','SELECT pg_last_wal_receive_lsn(), pg_last_wal_replay_lsn();','grep primary_conninfo $PGDATA/postgresql.auto.conf'],
        bestPractices:['Automate conninfo management via Patroni/operator','Test replication auth from standby host before backup','Monitor walreceiver process on standby','Keep slot when standby intentionally stopped'] }),
  ]},
  { topic: 'index-types', file: 'indexing.js', questions: [
    q('pg-index-types-1','index-types','indexing.js','easy','Very Common','Database Engineer',
      'What index access methods does PostgreSQL support and when use each?',
      { interview:'B-tree default for equality and range. Hash for equality only (rare). GiST for geometric/full-text/generalized search. SP-GiST for non-balanced structures (quadtrees). GIN for inverted indexes (arrays, jsonb, fts). BRIN for very large naturally ordered tables. Bloom for multi-column equality (extension).',
        explanation:'Each AM implements consistent API for planner. B-tree handles <, <=, =, >=, > and ORDER BY. GIN larger but fast lookups on elements. BRIN tiny index size scanning heap ranges. Choose based on query operators and data shape — EXPLAIN shows Index Scan type.',
        production:'JSONB metadata queries used B-tree on expression — 2GB index, slow writes. Switched to GIN (jsonb_path_ops) — index 400MB, query 50ms vs 800ms.',
        followUps:['Can one column have multiple index types?','Default index type if not specified?','GiST vs GIN for full-text?','When is Hash index appropriate PG 10+?'],
        mistakes:['B-tree on JSONB containment @> queries','GIN on low-cardinality boolean column','BRIN on random-ordered UUID insert table','GiST when GIN would be faster for jsonb'],
        seniorInsights:'Operator class determines index usability — show query operator → index AM mapping.',
        commands:['SELECT amname FROM pg_am WHERE amtype = \'i\';','\\d orders — view index definitions','CREATE INDEX idx ON t USING gin (data jsonb_path_ops);'],
        bestPractices:['Match index AM to query operators in EXPLAIN','Prototype index type on staging with realistic data','Monitor index size vs query benefit in pg_stat_user_indexes','Document non-B-tree indexes in schema guide'] }),
    q('pg-index-types-2','index-types','indexing.js','medium','Common','DBA',
      'Explain partial, covering, and expression indexes.',
      { interview:'Partial index: WHERE clause limits indexed rows — smaller, faster for filtered queries. Covering index: INCLUDE columns enable index-only scan without heap visit for included cols. Expression index: indexes function result CREATE INDEX ON t ((lower(email))). All require matching query predicates exactly.',
        explanation:'Partial index ideal for sparse predicates — WHERE status = \'open\' on mostly-closed table. INCLUDE adds payload columns not in search key — PG 11+. Expression index for case-insensitive search lower(col). Unique partial indexes enforce conditional uniqueness.',
        production:'Unique email index on all rows failed for soft-deleted users with duplicate emails. CREATE UNIQUE INDEX users_email_active ON users (lower(email)) WHERE deleted_at IS NULL; solved constraint and halved index size.',
        followUps:['Partial index and UNIQUE constraint?','INCLUDE vs composite index trade-off?','Immutable function requirement for expression index?','Planner using partial index incorrectly?'],
        mistakes:['Partial index WHERE not matching query filter exactly','INCLUDE columns not in SELECT — no index-only benefit','Non-immutable function in expression index','Duplicate overlapping indexes wasting write overhead'],
        seniorInsights:'Partial indexes are underused — interview scenario: soft delete, status filters, active-only rows.',
        commands:['CREATE UNIQUE INDEX users_email_active ON users (lower(email)) WHERE deleted_at IS NULL;','CREATE INDEX orders_cover ON orders (customer_id) INCLUDE (total, created_at);','EXPLAIN SELECT total FROM orders WHERE customer_id = 1;'],
        bestPractices:['Use partial indexes for skewed filter predicates','INCLUDE columns frequently selected with key lookup','Ensure expression indexes use immutable functions','Drop redundant indexes after adding covering index'] }),
    q('pg-index-types-3','index-types','indexing.js','medium','Very Common','Production Support',
      'How do you identify unused or redundant indexes in production?',
      { interview:'pg_stat_user_indexes idx_scan = 0 since stats reset indicates unused (verify over weeks). pg_stat_statements + EXPLAIN for query coverage. Duplicate indexes: same leading columns — keep one. Index size vs scan count in pg_stat_user_indexes guides drop candidates.',
        explanation:'Reset stats after major release before judging. FK columns without index show up as seq scans on JOIN/DELETE parent. pg_repack/REINDEX before drop not needed for drop itself. CREATE INDEX CONCURRENTLY for new; DROP INDEX CONCURRENTLY to avoid blocking.',
        production:'Audit found 23 indexes with idx_scan=0 over 90 days — 15GB total. Dropped 18 after query log verification; write throughput on orders improved 12%.',
        followUps:['idx_tup_read vs idx_scan interpretation?','Drop index impact on constraint?','Hypothetical index testing PG?','Auto-explain for missing index detection?'],
        mistakes:['Dropping index after short stats window post-deploy','Removing FK-supporting index causing lock on parent DELETE','Dropping UNIQUE index backing constraint without replacement','Not checking replication lag impact of large DROP INDEX'],
        seniorInsights:'Present audit query joining pg_stat_user_indexes to pg_indexes with size — sorted by size where idx_scan=0.',
        commands:['SELECT schemaname, relname, indexrelname, idx_scan, pg_size_pretty(pg_relation_size(indexrelid)) AS size FROM pg_stat_user_indexes ORDER BY idx_scan ASC, pg_relation_size(indexrelid) DESC;','DROP INDEX CONCURRENTLY idx_unused;'],
        bestPractices:['Review unused indexes quarterly with 90-day stats','Keep indexes supporting FK and UNIQUE constraints','Drop CONCURRENTLY in production','Verify pg_stat_statements query plans after drop'] }),
    q('pg-index-types-4','index-types','indexing.js','hard','Common','Database Engineer',
      'Compare index-only scans, bitmap scans, and sequential scans in execution plans.',
      { interview:'Index-only scan: answers query from index if visibility map confirms all-visible pages — no heap fetch. Bitmap index scan: OR multiple indexes, sort TIDs, heap fetch in order — moderate selectivity. Seq scan: read all pages — wins when most rows needed or index random IO costly.',
        explanation:'Index-only requires INCLUDE or query columns all in index + VM bit. BitmapAnd combines predicates. Lossy bitmap pages skip exact TID if work_mem tight. increasing random_page_cost favors seq scan on SSD wrongly if left at 4.0 default.',
        production:'Dashboard query used Index Scan fetching heap every row — VM not set due to vacuum backlog. Fixed vacuum; plan became Index Only Scan — 70% IO reduction.',
        followUps:['When bitmap scan becomes lossy?','VM bit not set — root causes?','Covering index vs index-only scan?','Adjust random_page_cost for SSD?'],
        mistakes:['Adding INCLUDE without fixing vacuum for VM','Misreading Bitmap Heap Scan as problem when appropriate','Lowering random_page_cost to 0.1 without holistic testing','Expecting index-only on JSONB GIN without appropriate query shape'],
        seniorInsights:'Index-only scan failure → check visibility map and vacuum first, not index shape.',
        commands:['EXPLAIN (ANALYZE, BUFFERS) SELECT id, status FROM orders WHERE customer_id = 123;','SELECT * FROM pg_visibility_map(\'orders\'::regclass) LIMIT 1;','SET random_page_cost = 1.1; -- test SSD tuning session only'],
        bestPractices:['Maintain visibility map via healthy autovacuum','Design covering indexes for high-QPS lookups','Validate plan type after vacuum on large tables','Tune random_page_cost per storage type with benchmarks'] }),
    q('pg-index-types-5','index-types','indexing.js','hard','Rare','DBA',
      'Design indexing strategy for mixed OLTP and reporting on same PostgreSQL database.',
      { interview:'OLTP: narrow B-tree indexes on lookup/join keys, partial indexes for hot paths. Reporting: BRIN on time-series facts, GIN for search, consider covering indexes for top reports or offload to replica/columnar (Citus columnar, ClickHouse via FDW). Avoid over-indexing write-heavy OLTP tables — each index slows INSERT/UPDATE.',
        explanation:'Read replica for reporting isolates seq scans from OLTP. pg_stat_statements identifies reporting queries deserving dedicated indexes vs replica. CONCURRENTLY build indexes. Partitioning by time helps BRIN and detach old partitions. Materialized views with REFRESH CONCURRENTLY for dashboards.',
        production:'Reporting team added 8 indexes on orders OLTP table — write latency doubled. Moved reporting indexes to read replica only; OLTP kept 3 core indexes; materialized view refreshed nightly for CFO dashboard.',
        followUps:['Hypopg extension for what-if indexes?','Citus columnar for analytics?','Incremental materialized view PG 13+?','Index bloat from reporting index on OLTP?'],
        mistakes:['Same index set on primary and replica without need','Materialized view REFRESH blocking without CONCURRENTLY','GIN index on OLTP hot path killing write throughput','No query routing — reports hit primary'],
        seniorInsights:'Split OLTP vs reporting at connection pool level — different indexes allowed on replica.',
        commands:['CREATE INDEX CONCURRENTLY idx_orders_created ON orders (created_at);','CREATE MATERIALIZED VIEW mv_daily_sales AS SELECT ... WITH DATA;','REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_sales;'],
        bestPractices:['Route reporting queries to read replicas','Build reporting-specific indexes on replica when possible','Use materialized views for heavy aggregations','Review index count impact on write latency monthly'] }),
  ]},
];
