/** PostgreSQL registry question data — parts 1-2 (architecture through wal) */

function q(id, topic, file, difficulty, frequency, role, question, sections, command) {
  return { id, topic, file, difficulty, frequency, role, question, sections, command };
}

export const PART1 = [
  {
    label: 'architecture.js',
    topic: 'postgresql-architecture',
    file: 'architecture.js',
    questions: [
      q('pg-postgresql-architecture-1', 'postgresql-architecture', 'architecture.js', 'easy', 'Very Common', 'DBA',
        'Describe the PostgreSQL process architecture: postmaster, backends, and background workers.',
        {
          interview: 'PostgreSQL uses a postmaster parent that listens on port 5432 and forks a dedicated backend process per client connection. Background workers include checkpointer, WAL writer, autovacuum launcher/workers, stats collector, and optional logical replication apply workers. Shared memory holds shared_buffers, WAL buffers, lock tables, and proc arrays. Each session is an OS process — high connection counts require external pooling.',
          explanation: 'The postmaster manages startup, crash recovery, and child lifecycle. On connection it forks exec postgres backend which reads pg_hba.conf, authenticates, and attaches to shared memory. Background processes are postmaster children started at boot: bgwriter flushes dirty buffers, checkpointer writes checkpoint records to WAL, walwriter flushes WAL buffers, autovacuum launcher schedules workers, and archiver optionally ships WAL segments. Logical replication uses apply workers per subscription. This multi-process design avoids GIL-style contention but makes connection count a first-class capacity metric.',
          production: 'An e-commerce platform hit 800 direct connections during a deploy spike; each backend consumed ~10MB RSS and the OS started thrashing. pg_stat_activity showed 600 idle sessions from a misconfigured app pool. Fix: deploy PgBouncer in transaction mode, set max_connections=200, and alert on pg_stat_activity count > 150.',
          followUps: ['What happens to in-flight transactions when postmaster crashes?', 'How does max_connections interact with superuser_reserved_connections?', 'Difference between background writer and checkpointer?', 'When would you enable parallel workers vs connection pooling?'],
          mistakes: ['Setting max_connections to 2000 without pooling or RAM planning', 'Ignoring superuser_reserved_connections during incident response', 'Assuming thread-per-connection like some other databases', 'Killing postmaster with SIGKILL instead of SIGTERM during maintenance'],
          seniorInsights: 'Capacity planning starts with (max_connections × per-backend memory) + shared_buffers + wal_buffers + maintenance_work_mem ceiling for autovacuum workers. On managed RDS/Aurora, the connection limit is often the first hard ceiling before CPU. Monitor pg_stat_database numbackends and correlate with load average.',
          commands: ['SELECT pid, usename, application_name, state, wait_event_type, wait_event FROM pg_stat_activity;', "SELECT name, setting, unit FROM pg_settings WHERE name IN ('max_connections','superuser_reserved_connections','shared_buffers');"],
          bestPractices: ['Use PgBouncer or pgpool for app-facing connections', 'Set statement_timeout and idle_in_transaction_session_timeout', 'Label connections via application_name for troubleshooting', 'Reserve headroom below max_connections for admin and replication'],
        }),
      q('pg-postgresql-architecture-2', 'postgresql-architecture', 'architecture.js', 'medium', 'Common', 'Database Engineer',
        'How do tablespaces and on-disk storage layout affect PostgreSQL operations?',
        {
          interview: 'Tablespaces map database objects to filesystem directories via pg_tablespace. Default pg_default holds user data; pg_global holds shared catalogs. Separate tablespaces enable tiering hot tables on NVMe and cold archives on cheaper storage. Each table/index is stored as a relfilenode file under the tablespace path. Moving objects between tablespaces rewrites data and requires ACCESS EXCLUSIVE lock.',
          explanation: 'PostgreSQL stores heap and index files as segments (default 1GB) named by relfilenode OID. CREATE TABLESPACE requires an empty directory owned by postgres. ALTER TABLE SET TABLESPACE copies the entire relation — expensive on terabyte tables. WAL and pg_wal always live on the data directory unless redirected. Monitoring per-tablespace disk prevents WAL/data partition exhaustion. Cloud volumes attach cleanly as tablespace mount points.',
          production: 'A analytics team created TABLESPACE fast_nvme for a 2TB fact table but forgot to move indexes; sequential scans saturated the default EBS gp2 volume while NVMe sat idle. pg_table_size and du on $PGDATA/base confirmed misplacement. Scheduled maintenance: CREATE INDEX CONCURRENTLY on new tablespace, swap, drop old.',
          followUps: ['Can WAL live on a separate tablespace?', 'How does CREATE DATABASE specify tablespace?', 'Impact of tablespace on pg_basebackup paths?', 'Temp files and tablespace interaction during sorts?'],
          mistakes: ['Creating tablespace on NFS without testing fsync latency', 'Running ALTER TABLE SET TABLESPACE on production without lock timeout', 'Forgetting tablespace permissions after OS directory recreation', 'Mixing tablespaces across different filesystem block sizes without testing'],
          seniorInsights: 'Tablespaces are underused but valuable for IO isolation on bare metal. On Aurora/RDS you often cannot use custom tablespaces — plan tiering via read replicas or partitioning instead. Always document tablespace-to-mount mappings in runbooks.',
          commands: ['SELECT spcname, pg_tablespace_location(oid) FROM pg_tablespace;', "SELECT c.relname, pg_tablespace_location(c.reltablespace) FROM pg_class c WHERE c.relkind = 'r' AND c.relnamespace = 'public'::regnamespace LIMIT 20;"],
          bestPractices: ['Document mount points and IOPS provisioning per tablespace', 'Monitor disk usage per tablespace separately', 'Test fsync performance before production tablespace creation', 'Use partitioning before tablespace tiering for logical separation'],
        }),
      q('pg-postgresql-architecture-3', 'postgresql-architecture', 'architecture.js', 'medium', 'Very Common', 'Database Engineer',
        'Explain shared_buffers, local buffers, and the buffer pool replacement strategy.',
        {
          interview: 'shared_buffers is PostgreSQL\'s primary page cache in shared memory; all backends read/write 8KB pages through it. Backend-private local buffers cache temporary tables. The clock-sweep algorithm evicts dirty pages, delegating writes to bgwriter/checkpointer. effective_cache_size hints the planner about OS page cache. Too-small shared_buffers increases disk IO; too-large can starve OS cache on Linux.',
          explanation: 'Buffer tags identify (relfilenode, fork, block) tuples in the buffer pool. Pin/unpin reference counting prevents eviction during access. bgwriter scans dirty buffers proactively; checkpointer writes a checkpoint WAL record flushing dirty pages at checkpoint_completion_target intervals. pg_buffercache extension reveals which relations occupy buffers. On Linux, many DBAs set shared_buffers to 25% RAM and rely on OS cache for the rest.',
          production: 'After upgrading shared_buffers from 4GB to 32GB on a 64GB host, random read latency improved but checkpoint spikes doubled write IO, causing replica lag. pg_stat_bgwriter showed buffers_checkpoint spiking. Tuned checkpoint_completion_target=0.9 and max_wal_size=8GB to spread writes.',
          followUps: ['What does pg_buffercache show and when is it safe to query?', 'How does effective_cache_size affect EXPLAIN?', 'Difference between buffer hit ratio on index vs heap?', 'Impact of full_page_writes on buffer dirtying?'],
          mistakes: ['Setting shared_buffers > 40% RAM on Linux without testing', 'Ignoring checkpoint IO when tuning shared_buffers', 'Using pg_prewarm blindly on cold start without measuring benefit', 'Equating buffer cache hit ratio alone with query health'],
          seniorInsights: 'Hit ratio below 99% on OLTP is worth investigating but OLAP workloads legitimately scan cold data. Combine pg_stat_database blks_hit/blks_read with pg_stat_statements mean time. For RDS, shared_buffers is preset — tune work_mem and connection count instead.',
          commands: ["SELECT setting FROM pg_settings WHERE name IN ('shared_buffers','effective_cache_size','checkpoint_completion_target');", 'SELECT sum(heap_blks_hit) / nullif(sum(heap_blks_hit)+sum(heap_blks_read),0) AS heap_hit_ratio FROM pg_statio_user_tables;'],
          bestPractices: ['Benchmark before and after shared_buffers changes', 'Monitor checkpoint duration via pg_stat_bgwriter', 'Use pg_stat_statements for IO-heavy queries not captured by hit ratio', 'Restart required for shared_buffers changes — plan maintenance'],
        }),
      q('pg-postgresql-architecture-4', 'postgresql-architecture', 'architecture.js', 'easy', 'Very Common', 'Production Support',
        'What is the role of pg_hba.conf and how does authentication flow for a new connection?',
        {
          interview: 'pg_hba.conf defines which hosts/users/databases may connect and which auth method applies (scram-sha-256, cert, peer, md5). The postmaster reads it on startup and on SIGHUP reload. First matching rule wins. Client connection hits postmaster, which forks backend; backend evaluates pg_hba.conf before authentication completes.',
          explanation: 'Rules specify connection type (local, host, hostssl), database, user, address/CIDR, and method. scram-sha-256 is preferred over md5. peer/trust are for local socket connections on Linux. SSL rules use hostssl; client certs use clientcert=verify-full in pg_ident.conf mappings. pg_hba.conf errors prevent reload — always validate with pg_reload_conf() and check logs.',
          production: 'After a VPC subnet expansion, application pods got "no pg_hba.conf entry for host" errors. New pod CIDR 10.42.0.0/16 was missing from pg_hba.conf while 10.41.0.0/16 existed. Added hostssl rule, ran SELECT pg_reload_conf(), verified with psql from a canary pod.',
          followUps: ['How do you reload pg_hba.conf without restart?', 'Difference between scram-sha-256 and md5?', 'When to use pg_ident.conf?', 'How does RDS handle pg_hba equivalent?'],
          mistakes: ['Using trust on host entries in production', 'Forgetting hostssl vs host when requiring TLS', 'Rule order causing unintended deny — broader rules above specific ones', 'Not testing reload on staging before production SIGHUP'],
          seniorInsights: 'Automate pg_hba changes via Ansible/Puppet with version control. Pair with pg_stat_ssl to audit encrypted connections. For zero-trust, combine cert auth and short-lived credentials from Vault.',
          commands: ['SELECT pg_reload_conf();', 'SELECT a.pid, a.usename, s.ssl, a.client_addr FROM pg_stat_ssl s JOIN pg_stat_activity a USING (pid);', '# pg_hba.conf:\n# hostssl appdb appuser 10.42.0.0/16 scram-sha-256'],
          bestPractices: ['Version-control pg_hba.conf with infrastructure code', 'Use hostssl and scram-sha-256 for remote connections', 'Document rule order and test with psql from each subnet', 'Alert on authentication failure rate in PostgreSQL logs'],
        }),
      q('pg-postgresql-architecture-5', 'postgresql-architecture', 'architecture.js', 'hard', 'Common', 'Cloud Engineer',
        'Design PostgreSQL architecture for a multi-tenant SaaS with strict tenant isolation and 99.95% uptime.',
        {
          interview: 'Use schema-per-tenant or database-per-tenant depending on scale; database-per-tenant simplifies backup/restore per customer but increases connection overhead — pool per tenant via PgBouncer. Primary-replica streaming replication with Patroni/etcd for automatic failover. Separate read replicas for reporting. RLS as defense-in-depth for shared-schema models. PITR with WAL archiving to S3 for RPO < 5 min.',
          explanation: 'Architecture layers: Route53/GLB → PgBouncer (transaction mode) → Patroni-managed primary + 2 sync replicas in 3 AZs. Citus or sharding if single-tenant data exceeds 2TB. pg_audit for compliance. Connection limits per tenant via PgBouncer pool_size and database roles. Monitoring: pg_stat_replication lag, pg_stat_database conflicts, autovacuum backlog, connection saturation.',
          production: 'A HR SaaS with 400 tenants on shared schema suffered noisy-neighbor IO when one tenant ran full-table analytics. Migrated largest 20 tenants to dedicated databases with per-tenant PgBouncer pools; implemented RLS policies on shared schema for remaining tenants. Failover tested quarterly via Patroni switchover — RTO 45 seconds.',
          followUps: ['Schema vs database vs row-level isolation trade-offs?', 'How to handle cross-tenant reporting queries?', 'Connection pool sizing formula for multi-tenant?', 'Major version upgrade without downtime?'],
          mistakes: ['Single max_connections for all tenants without pool isolation', 'Skipping RLS on shared-schema multi-tenant', 'No tested failover runbook — manual promotion during outage', 'Autovacuum tuned globally ignoring per-tenant bloat variance'],
          seniorInsights: 'Tenant isolation is a product decision with ops cost. Database-per-tenant at 500+ tenants needs orchestration. Always measure blast radius: one tenant\'s VACUUM FULL should not block others — separate databases achieve this naturally.',
          commands: ['SELECT datname, numbackends FROM pg_stat_database ORDER BY numbackends DESC;', 'patronictl list', 'SELECT application_name, state, sync_state, replay_lag FROM pg_stat_replication;'],
          bestPractices: ['Automate failover drills quarterly', 'Per-tenant connection pools and statement timeouts', 'Archive WAL to durable object storage', 'Use pg_stat_statements tagged by application_name per tenant'],
        }),
    ],
  },
  {
    label: 'architecture.js',
    topic: 'query-planner',
    file: 'architecture.js',
    questions: [
      q('pg-query-planner-1', 'query-planner', 'architecture.js', 'easy', 'Very Common', 'Database Engineer',
        'How does the PostgreSQL query planner choose between sequential scan, index scan, and bitmap scan?',
        {
          interview: 'The planner estimates cost using statistics from pg_statistic/pg_stats: row counts, selectivity, correlation. Sequential scan wins for large fractions of the table. Index scan suits highly selective predicates. Bitmap index scan combines multiple indexes then heap fetch — good for moderate selectivity. enable_seqscan and random_page_cost influence choices but should not be toggled casually in production.',
          explanation: 'Cost units are abstract (seq_page_cost=1.0 default, random_page_cost=4.0). Planner compares paths: Seq Scan cost ≈ pages × seq_page_cost; Index Scan adds index pages + heap fetches × random_page_cost. Bitmap Heap Scan builds TID bitmap from one or more indexes before visiting heap — reduces random IO vs plain index scan on wide ranges. ANALYZE refreshes statistics; stale stats cause wrong row estimates and nested loop on large sets.',
          production: 'After bulk load of 50M rows without ANALYZE, a billing query switched from index scan to seq scan on a 200-row filter because n_distinct was stale. EXPLAIN showed estimated rows=1, actual=180000. Ran ANALYZE billing_events; plan reverted to Bitmap Index Scan, latency dropped from 12s to 80ms.',
          followUps: ['When does the planner pick Index Only Scan?', 'How does default_statistics_target affect estimates?', 'What is the difference between nested loop and hash join selection?', 'Impact of extended statistics (CREATE STATISTICS)?'],
          mistakes: ['Disabling seqscan globally to force index use', 'Not running ANALYZE after large COPY/DELETE', 'Ignoring correlation stats for multi-column filters', 'Assuming EXPLAIN without ANALYZE reflects production row counts'],
          seniorInsights: 'Always pair EXPLAIN (ANALYZE, BUFFERS) with pg_stat_statements. When estimates diverge 10× from actual, check stats freshness and consider increased statistics targets on skewed columns.',
          commands: ['EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM orders WHERE status = $1 AND created_at > $2;', 'SELECT schemaname, tablename, last_analyze, last_autoanalyze FROM pg_stat_user_tables WHERE relname = \'orders\';', 'SELECT attname, n_distinct, correlation FROM pg_stats WHERE tablename = \'orders\';'],
          bestPractices: ['Schedule ANALYZE after bulk loads via autovacuum or job', 'Use EXPLAIN (ANALYZE, BUFFERS) in staging with production-like data volumes', 'Create extended statistics for correlated columns', 'Avoid planner GUC hacks — fix stats and indexes first'],
        }),
      q('pg-query-planner-2', 'query-planner', 'architecture.js', 'medium', 'Very Common', 'Database Engineer',
        'Explain join algorithms in PostgreSQL: nested loop, hash join, and merge join.',
        {
          interview: 'Nested loop: for each outer row, probe inner — ideal when inner is index-backed and outer is small. Hash join: builds hash table on smaller input, probes larger — best for equi-joins without useful indexes on large sets. Merge join: both inputs sorted on join key — efficient for pre-sorted or index-ordered data. work_mem caps hash/sort memory; spills to disk if exceeded.',
          explanation: 'Planner picks join order and method via dynamic programming (GEQO for many tables). Hash join requires equality predicates; merge join needs sortable types and ordered inputs. Nested loop with materialize appears when inner is re-scanned. Parallel hash join (PG 9.6+) splits build/probe across workers. join_collapse_limit and from_collapse_limit affect subquery flattening. pg_stat_statements reveals join-heavy queries by total time.',
          production: 'A reporting query joining 4 tables used Hash Join with 2GB sort spill to disk — work_mem was 64MB. Increased work_mem to 256MB for the reporting role via SET LOCAL in a transaction block; query time fell from 45s to 6s. Monitored temp file usage via pg_stat_database temp_bytes.',
          followUps: ['When does PostgreSQL choose merge join over hash join?', 'How does parallel join interact with max_parallel_workers_per_gather?', 'What causes nested loop on 1M × 1M rows?', 'Semi-join and anti-join plan shapes?'],
          mistakes: ['Raising work_mem globally causing memory pressure under concurrency', 'Missing join column statistics causing hash on wrong inner table', 'Not indexing foreign key columns used in nested loops', 'Ignoring enable_hashjoin toggles left from old debugging sessions'],
          seniorInsights: 'Hash join spill is a smoking gun for work_mem tuning per workload class, not globally. For OLTP, nested loop + index is usually correct — hash on millions of rows signals missing index or bad stats.',
          commands: ['EXPLAIN (ANALYZE, BUFFERS, VERBOSE) SELECT ... FROM a JOIN b ON a.id = b.a_id;', "SELECT name, setting FROM pg_settings WHERE name IN ('work_mem','hash_mem_multiplier','enable_hashjoin');", 'SELECT query, temp_blks_written FROM pg_stat_statements ORDER BY temp_blks_written DESC LIMIT 10;'],
          bestPractices: ['Index foreign keys and high-cardinality join columns', 'Set role-specific work_mem for batch/reporting roles', 'Monitor temp file growth in pg_stat_database', 'Use pg_hint_plan only as last resort with documented reason'],
        }),
      q('pg-query-planner-3', 'query-planner', 'architecture.js', 'medium', 'Common', 'Production Support',
        'What role do pg_stats, histograms, and MCV lists play in selectivity estimation?',
        {
          interview: 'pg_stats stores per-column statistics: null_frac, avg_width, n_distinct, most_common_vals/freqs (MCV), and histogram_bounds for range queries. Selectivity of WHERE col = constant uses MCV if present; otherwise 1/n_distinct. Range predicates interpolate within histogram buckets. Correlated columns need CREATE STATISTICS ... n_distinct or functional dependencies.',
          explanation: 'ANALYZE samples rows (default 300 × default_statistics_target) to build stats. Higher default_statistics_target increases histogram resolution and MCV count — costs more ANALYZE time. Extended stats capture multivariate ndistinct and dependencies. Expression indexes require statistics on expressions. inherited tables aggregate child stats. autovacuum_analyze_scale_factor triggers re-analyze on change fraction.',
          production: 'Queries filtering status IN (\'pending\',\'processing\') AND region = \'eu-west\' underestimated rows because status and region were correlated — EU had 90% pending. CREATE STATISTICS stts (dependencies) ON status, region FROM orders; ANALYZE orders; plan switched from nested loop to hash join correctly.',
          followUps: ['How to inspect histogram buckets for a column?', 'When does the planner assume uniform distribution?', 'Impact of NULL fraction on index selectivity?', 'Stats on partitioned table parent vs partitions?'],
          mistakes: ['Increasing statistics target on every column without measuring ANALYZE duration', 'Ignoring correlation on composite filters', 'Not analyzing after CREATE INDEX CONCURRENTLY completes', 'Assuming n_distinct from sample is exact on small tables'],
          seniorInsights: 'For skewed columns (status, country_code), MCV lists are critical — a rare status value with wrong estimate causes catastrophic nested loops. Check pg_stats.most_common_vals before adding indexes.',
          commands: ['SELECT attname, null_frac, n_distinct, most_common_vals, most_common_freqs, histogram_bounds FROM pg_stats WHERE tablename = \'orders\' AND attname = \'status\';', 'CREATE STATISTICS orders_status_region (dependencies) ON status, region FROM orders;', 'ANALYZE VERBOSE orders;'],
          bestPractices: ['Target extended statistics at known correlated filter pairs', 'Review pg_stats after schema changes affecting query patterns', 'Tune autovacuum analyze thresholds on high-churn tables', 'Document statistics maintenance in migration runbooks'],
        }),
      q('pg-query-planner-4', 'query-planner', 'architecture.js', 'hard', 'Common', 'Database Engineer',
        'How does parallel query planning work and when should you enable or disable it?',
        {
          interview: 'Parallel query splits scan/join/aggregate across background workers when expected benefit exceeds parallel_setup_cost. GUCs: max_parallel_workers_per_gather, max_parallel_workers, min_parallel_table_scan_size, parallel_tuple_cost. Gather node collects partial results. Parallel unsafe functions or subtransactions block parallelism. Serial plans may beat parallel on small tables due to worker startup overhead.',
          explanation: 'Leader process coordinates workers; each worker scans a page range or hash partition. Parallel seq scan, parallel bitmap heap scan, parallel hash join, parallel aggregate (partial mode). max_worker_processes caps total background workers including autovacuum and logical replication. ALTER TABLE ... SET (parallel_workers = N) per table. EXPLAIN shows Workers Planned/Launched. RDS/Aurora expose parallel settings with instance-size limits.',
          production: 'OLTP dashboard queries on a 500GB table triggered parallel seq scans saturating CPU — 8 workers per query × 50 concurrent requests. Set parallel_workers=0 on hot OLTP tables via ALTER TABLE, raised min_parallel_table_scan_size to 1GB, reserved max_parallel_workers for nightly ETL role only.',
          followUps: ['Why might Workers Launched be less than Workers Planned?', 'Parallel query and replication slot interaction?', 'Can parallel workers increase lock contention?', 'parallel_leader_participation behavior?'],
          mistakes: ['Enabling parallelism on tiny OLTP tables causing worker churn', 'max_parallel_workers_per_gather=16 on 4-vCPU instance', 'Using parallel unsafe PL/pgSQL functions in SELECT list', 'Not checking parallel safety of custom C functions'],
          seniorInsights: 'Parallelism is for analytics and batch — default OLTP tables often benefit from parallel_workers=0. Watch pg_stat_activity wait_event ParallelBitmapScan when IO-bound. Combine with partition pruning for best wins.',
          commands: ["EXPLAIN (ANALYZE, BUFFERS) SELECT count(*) FROM events WHERE ts > now() - interval '7 days';", "SELECT relname, reloptions FROM pg_class WHERE relname = 'events';", "ALTER TABLE events SET (parallel_workers = 4);", "SELECT name, setting FROM pg_settings WHERE name LIKE '%parallel%';"],
          bestPractices: ['Disable parallel workers on latency-sensitive OLTP tables', 'Size max_parallel_workers to CPU cores minus headroom', 'Use parallel query for batch ETL windows only', 'Test parallel plans after major version upgrades'],
        }),
      q('pg-query-planner-5', 'query-planner', 'architecture.js', 'hard', 'Rare', 'DBA',
        'Diagnose and fix a plan regression after a PostgreSQL major version upgrade.',
        {
          interview: 'Compare EXPLAIN plans pre/post upgrade using pg_stat_statements queryid and normalized query text. Check release notes for planner changes (join order, partitionwise join, default cost constants). Verify statistics refreshed via pg_upgrade --analyze-in-stages. Consider pg_store_plans or saved golden plans. Rollback via pg_hint_plan temporarily while fixing root cause.',
          explanation: 'Common upgrade regressions: improved parallel defaults causing OLTP parallel scans; changed selectivity formulas; partitionwise aggregate now chosen incorrectly; extended statistics not migrated. pg_upgrade preserves data but stats may need rebuild. Compare auto_explain logs. Memoize nodes in PG 15 changed nested loop behavior. Test with same data volume — empty staging misleads.',
          production: 'Post PG 15 upgrade, checkout query latency 3× higher — EXPLAIN showed Memoize on nested loop with negative cache hit. Workaround: SET enable_memoize=off for app role until PG 15.2 fix. Long-term: index on (cart_id, sku_id) eliminated repeated probes; re-enabled memoize after patch.',
          followUps: ['What does pg_upgrade --analyze-in-stages do?', 'How to capture plans automatically with auto_explain?', 'When to use prepared statements vs generic plans?', 'Impact of plan_cache_mode on regressions?'],
          mistakes: ['Blaming hardware before comparing plans side-by-side', 'Skipping ANALYZE after pg_upgrade', 'Permanent enable_*=off without ticket to fix stats/index', 'Testing plan changes on empty tables'],
          seniorInsights: 'Maintain a golden query suite with saved EXPLAIN plans in CI. After upgrade, run EXPLAIN (ANALYZE) on top 20 pg_stat_statements by total_exec_time before opening traffic.',
          commands: ['SELECT query, calls, mean_exec_time, queryid FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 20;', "LOAD 'auto_explain'; SET auto_explain.log_analyze = true;", 'ANALYZE;', 'SELECT version();'],
          bestPractices: ['Run analyze-in-stages after pg_upgrade', 'Keep pre-upgrade pg_stat_statements export', 'Stage upgrade with replay traffic and plan diff', 'Document temporary GUC overrides with expiry dates'],
        }),
    ],
  },
];

export { q };
