/** Topics 12-17 + scenarios for snowflake content */
export function item(q, a, cmd) { return { q, a, cmd }; }

export const PART4_TOPICS = {
  'dynamic-tables': {
    easy: [
      item('What is a Snowflake dynamic table and how does it differ from a view?', 'Dynamic tables are materialized query results with automatic incremental refresh.\n• Defined by AS SELECT query like a view but Snowflake maintains physical storage.\n• TARGET_LAG specifies maximum staleness (e.g., 1 hour, downstream refresh triggers).\n• Refresh uses warehouse compute; dependency graph auto-orchestrates upstream-first refresh.\n• Unlike views, queries scan pre-materialized data—faster for heavy aggregations.\n• Unlike manual tables + tasks, no explicit MERGE/stream code required.\n\nUse dynamic tables for declarative pipeline layers replacing task chains.', 'CREATE DYNAMIC TABLE dt_active_users\n  TARGET_LAG = \'1 hour\'\n  WAREHOUSE = etl_wh AS\nSELECT user_id, last_login FROM users WHERE status = \'ACTIVE\';\n\nSELECT * FROM dt_active_users;'),
      item('Explain TARGET_LAG and how it controls refresh frequency.', 'TARGET_LAG is the maximum acceptable staleness for dynamic table data.\n• \'1 minute\', \'5 minutes\', \'1 hour\', \'DOWNSTREAM\' (refresh when downstream DT queried).\n• Snowflake schedules refreshes to keep data within lag SLA.\n• Shorter lag = more frequent refreshes = more credits.\n• DOWNSTREAM optimizes cost when table only needed on-demand by child DT.\n• Monitor refresh history for actual lag vs target.\n\nMatch TARGET_LAG to business SLA: hourly KPIs do not need 1-minute lag.', 'ALTER DYNAMIC TABLE dt_sales SET TARGET_LAG = \'30 minutes\';\n\nSELECT name, target_lag, scheduling_state\nFROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES());'),
      item('How do dynamic tables form dependency graphs?', 'Dynamic tables automatically detect upstream dependencies from query text.\n• DT gold references DT silver in SELECT—gold refresh waits for silver refresh.\n• Snowflake builds DAG and refreshes in topological order.\n• ALTER DYNAMIC TABLE ... REFRESH manually triggers refresh including dependencies.\n• Broken dependency (dropped source) suspends dynamic table.\n• SHOW DYNAMIC TABLES shows scheduling_state and last refresh time.\n\nReplaces manual task AFTER chains for SQL-only transforms.', 'CREATE DYNAMIC TABLE dt_silver TARGET_LAG = \'15 min\' WAREHOUSE = etl_wh AS\nSELECT * FROM bronze.raw_orders WHERE valid = TRUE;\n\nCREATE DYNAMIC TABLE dt_gold TARGET_LAG = \'30 min\' WAREHOUSE = etl_wh AS\nSELECT region, SUM(amount) FROM dt_silver GROUP BY 1;'),
      item('What warehouse is used for dynamic table refresh?', 'Dynamic tables require a warehouse for refresh compute—specified at creation.\n• WAREHOUSE = wh_name in CREATE DYNAMIC TABLE statement.\n• Same warehouse can serve multiple DTs—watch concurrency and queuing.\n• Refresh credits billed to specified warehouse in metering history.\n• ALTER DYNAMIC TABLE ... SET WAREHOUSE = new_wh to change.\n• Suspend dynamic table to stop refresh credits during maintenance.\n\nSize warehouse based on refresh QUERY_HISTORY bytes_scanned per DT.', 'CREATE DYNAMIC TABLE dt_kpis\n  TARGET_LAG = \'1 hour\'\n  WAREHOUSE = transform_wh AS\nSELECT order_date, COUNT(*) FROM orders GROUP BY 1;\n\nALTER DYNAMIC TABLE dt_kpis SET WAREHOUSE = transform_wh_large;'),
    ],
    medium: [
      item('How do you troubleshoot a dynamic table with refresh failures?', 'Refresh failures appear in DYNAMIC_TABLE_REFRESH_HISTORY with error messages.\n• Check scheduling_state: SUSPENDED, FAILED reasons in history view.\n• Common causes: warehouse suspended, privilege lost on base table, SQL error in definition.\n• ALTER DYNAMIC TABLE ... REFRESH for manual retry after fix.\n• Validate base table schema change did not break SELECT (new column dependency).\n• Warehouse too small causes timeout—upsize or increase STATEMENT_TIMEOUT.\n\nCompare error_message across refreshes for recurring vs transient failures.', 'SELECT name, state, error_message, refresh_start_time, refresh_end_time\nFROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY())\nWHERE state = \'FAILED\'\nORDER BY refresh_start_time DESC LIMIT 10;\n\nALTER DYNAMIC TABLE dt_kpis REFRESH;'),
      item('When should you choose dynamic tables over streams + tasks?', 'Selection depends on pipeline complexity and team preference for declarative vs imperative.\n• Dynamic tables: linear SQL transforms, clear lag SLA, reduced ops code.\n• Streams + tasks: complex MERGE logic, conditional branching, non-SQL steps, external calls.\n• Dynamic tables handle incremental refresh automatically; tasks give explicit control.\n• Migration path: prototype as DT, fall back to task if SQL limitations hit.\n• Cost compare: DT refresh credits vs task MERGE credits over 30 days.\n\nHybrid architectures use DT for silver/gold and tasks for ingestion triggers.', 'CREATE DYNAMIC TABLE dt_enriched TARGET_LAG = \'10 minutes\' WAREHOUSE = etl_wh AS\nSELECT o.*, c.segment FROM orders o JOIN customers c ON o.cust_id = c.id;\n\nSHOW DYNAMIC TABLES LIKE \'dt_enriched\';'),
      item('How do you suspend and resume dynamic table refreshes for maintenance?', 'Suspension stops scheduled refreshes without dropping the table.\n• ALTER DYNAMIC TABLE ... SUSPEND stops refresh scheduling.\n• RESUME re-enables per TARGET_LAG schedule.\n• Use during upstream schema migration or data backfill on base tables.\n• Downstream DTs may stall if upstream suspended—coordinate dependency chain.\n• Data remains queryable at last successful refresh state while suspended.\n\nMaintenance window: suspend gold first, then silver, then modify bronze.', 'ALTER DYNAMIC TABLE dt_gold SUSPEND;\nALTER DYNAMIC TABLE dt_silver SUSPEND;\n\n-- perform maintenance on base tables\n\nALTER DYNAMIC TABLE dt_silver RESUME;\nALTER DYNAMIC TABLE dt_gold RESUME;'),
      item('What are limitations of dynamic table SQL definitions?', 'Dynamic tables support subset of SQL—verify current docs for unsupported constructs.\n• Generally: SELECT, JOIN, aggregations, window functions within supported set.\n• Unsupported patterns may require views as intermediate or task-based load.\n• External tables, certain UDF types, and non-deterministic functions may be restricted.\n• Very complex multi-stage logic may be clearer as chained DTs than one giant query.\n• Test CREATE in dev before prod deployment.\n\nWhen blocked, create secure view + task MERGE as fallback pattern.', 'CREATE DYNAMIC TABLE dt_test TARGET_LAG = \'1 hour\' WAREHOUSE = etl_wh AS\nSELECT a.id, b.name FROM table_a a LEFT JOIN table_b b ON a.id = b.id;\n\nSELECT GET_DDL(\'DYNAMIC TABLE\', \'dt_test\');'),
    ],
    hard: [
      item('Design a medallion lakehouse using only dynamic tables with tiered TARGET_LAG.', 'All-dynamic-table medallion simplifies lineage and reduces task sprawl.\n• Bronze: DT from external table/stage with TARGET_LAG 5 min on landing data.\n• Silver: DT cleanses bronze with 15 min lag, JOIN to reference data.\n• Gold: DT aggregates silver with 1 hour lag for BI consumption.\n• Warehouse isolation: bronze_wh (small frequent), gold_wh (large hourly).\n• Monitoring: dashboard on refresh history lag vs target per layer.\n• Failure isolation: suspend gold only while fixing silver upstream.\n\nDocument dependency DAG exported from SHOW DYNAMIC TABLES and REFRESH_HISTORY.', 'CREATE DYNAMIC TABLE bronze_orders TARGET_LAG = \'5 minutes\' WAREHOUSE = ingest_wh AS\nSELECT * FROM @landing_stage/orders/;\n\nCREATE DYNAMIC TABLE gold_daily TARGET_LAG = \'1 hour\' WAREHOUSE = analytics_wh AS\nSELECT order_date, SUM(amount) FROM silver_orders GROUP BY 1;'),
      item('Optimize dynamic table refresh cost for a pipeline spending 40% of account credits.', 'DT cost optimization targets lag tuning, warehouse sizing, and query efficiency.\n• Increase TARGET_LAG where SLA allows—1 min → 15 min can cut refreshes 15×.\n• Use DOWNSTREAM lag for tables only consumed by other DTs.\n• Right-size refresh warehouse; separate heavy and light DTs to different warehouses.\n• Optimize underlying SELECT: prune columns, filter early, cluster base tables.\n• Suspend unused DTs discovered via ACCESS_HISTORY zero queries 30 days.\n\nPresent savings forecast: lag changes vs SLA impact per dashboard.', 'SELECT name, SUM(credits_used) AS refresh_credits\nFROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY\nWHERE start_time > DATEADD(day, -30, CURRENT_TIMESTAMP())\nGROUP BY 1 ORDER BY 2 DESC;\n\nALTER DYNAMIC TABLE dt_low_priority SET TARGET_LAG = \'4 hours\';'),
      item('Lead migration from 25-task stream MERGE pipeline to dynamic tables.', 'Migration requires parity validation and phased cutover.\n• Inventory task DAG; map each MERGE to equivalent DT SELECT.\n• Build DTs in parallel writing to _v2 tables; compare row counts and hashes.\n• Cutover: rename/swap tables, suspend old tasks, resume DTs.\n• Rollback plan: resume tasks, swap back if lag SLA missed in week one.\n• Train team on REFRESH_HISTORY monitoring replacing TASK_HISTORY.\n• Decommission streams after 14-day parallel run with zero discrepancies.\n\nExecutive summary: 70% less pipeline code, 15% credit reduction, same 15-min SLA.', 'CREATE DYNAMIC TABLE orders_silver_v2 TARGET_LAG = \'15 minutes\' WAREHOUSE = etl_wh AS\nSELECT * FROM bronze.orders WHERE _processed IS NOT NULL;\n\nALTER TASK legacy_merge SUSPEND;\nALTER TABLE orders_silver SWAP WITH orders_silver_v2;'),
      item('Explain refresh modes and incremental maintenance internals at a high level.', 'Understanding refresh internals helps debug lag and correctness issues.\n• Snowflake tracks changes on base objects to refresh DT incrementally when possible.\n• Full refresh fallback occurs when incremental not possible (certain DDL, definition change).\n• Definition change may require INITIALIZE or full rebuild depending on alteration.\n• Monitor refresh_type in history: incremental vs full.\n• Full refresh on large DT is expensive—schedule definition changes off-peak.\n\nInterview depth: incremental leverages micro-partition change tracking similar to streams conceptually.', 'SELECT name, refresh_action, refresh_start_time, refresh_end_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY\nWHERE name = \'DT_ORDERS\'\nORDER BY refresh_start_time DESC LIMIT 20;\n\nALTER DYNAMIC TABLE dt_orders REFRESH;'),
    ],
  },

  'snowpipe': {
    easy: [
      item('What is Snowpipe and how does it differ from COPY INTO?', 'Snowpipe is Snowflake\'s continuous auto-ingest service for cloud storage files.\n• COPY INTO: manual or scheduled batch load command you execute.\n• Snowpipe: event-driven—cloud storage notification triggers automatic ingest on file arrival.\n• Snowpipe uses compute credits per file loaded (serverless ingest mode).\n• Near-real-time latency (minutes) vs batch COPY on schedule.\n• PIPE object defines COPY logic; AUTO_INGEST = TRUE enables event notifications.\n\nUse Snowpipe for streaming landing zone; COPY for bulk historical backfill.', 'CREATE PIPE orders_pipe AUTO_INGEST = TRUE AS\nCOPY INTO orders FROM @landing_stage FILE_FORMAT = csv_format;\n\nSHOW PIPES;\n\nSELECT SYSTEM$PIPE_STATUS(\'orders_pipe\');'),
      item('How do you check Snowpipe load status and history?', 'Pipe monitoring uses system functions and load history views.\n• SYSTEM$PIPE_STATUS(pipe_name) returns execution state and pending file count.\n• COPY_HISTORY or LOAD_HISTORY shows files loaded, errors, row counts.\n• PIPE_USAGE_HISTORY in ACCOUNT_USAGE for billing and throughput.\n• Notification channel errors appear in pipe status when SQS/Event Grid misconfigured.\n• Alert on pending file backlog growth.\n\nDashboard: files/hour, error rate, avg latency file-arrival to loaded.', 'SELECT SYSTEM$PIPE_STATUS(\'sales.public.orders_pipe\');\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(\n  TABLE_NAME => \'ORDERS\',\n  START_TIME => DATEADD(hour, -24, CURRENT_TIMESTAMP())\n));\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY LIMIT 10;'),
      item('What cloud notifications does Snowpipe require for auto-ingest?', 'Auto-ingest depends on cloud provider event notifications to Snowflake SQS queue.\n• AWS: S3 event notification → SQS queue (Snowflake-provided) → pipe trigger.\n• Azure: Event Grid on blob storage; GCP: Pub/Sub notifications.\n• DESC PIPE shows notification_channel with SQS ARN to configure in S3.\n• Without notification, use ALTER PIPE ... REFRESH for manual polling mode.\n• Storage integration secures Snowflake access to stage without keys.\n\nSetup checklist: stage, integration, pipe, notification, test file upload.', 'DESC PIPE orders_pipe;\n\n-- Configure S3 event notification to SQS ARN from DESC PIPE output\n\nALTER PIPE orders_pipe REFRESH;'),
      item('Explain ON_ERROR options in Snowpipe COPY statements.', 'ON_ERROR controls pipe behavior when individual rows or files fail validation.\n• ON_ERROR = CONTINUE: skip bad rows, load good rows, log errors.\n• ON_ERROR = SKIP_FILE: skip entire file on any error.\n• ON_ERROR = ABORT_STATEMENT: fail file load on first error.\n• Production pipes often use CONTINUE + quarantine monitoring on rejected records.\n• VALIDATION_MODE not used in pipe—test format separately before pipe DDL.\n\nPair with FILE_FORMAT error handling options for malformed CSV.', 'CREATE PIPE events_pipe AUTO_INGEST = TRUE AS\nCOPY INTO events FROM @stage\nFILE_FORMAT = (TYPE = JSON)\nON_ERROR = \'CONTINUE\';\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(\n  TABLE_NAME => \'EVENTS\', START_TIME => DATEADD(hour, -1, CURRENT_TIMESTAMP())\n));'),
    ],
    medium: [
      item('How do you troubleshoot Snowpipe files stuck in pending state?', 'Pending files indicate notification or permission pipeline breakdown.\n• SYSTEM$PIPE_STATUS: pending_file_count > 0 with no progress.\n• Verify S3 event notification targets correct SQS; check IAM/SQS policy.\n• Storage integration ALLOWED_LOCATIONS includes file path.\n• File size zero or unsupported compression blocks ingest.\n• ALTER PIPE ... REFRESH forces poll—if works, notification path is broken.\n• Snowflake support for persistent pipe internal errors with pipe_id.\n\nRunbook: test with single file, trace notification → SQS → pipe metrics.', 'SELECT SYSTEM$PIPE_STATUS(\'orders_pipe\');\n\nALTER PIPE orders_pipe REFRESH;\n\nDESC INTEGRATION s3_integration;\n\nLIST @landing_stage;'),
      item('How does Snowpipe handle duplicate file loads?', 'Snowpipe provides load idempotency for duplicate file delivery.\n• Snowflake tracks loaded files by name and metadata—re-sending same file skipped.\n• File renamed but same content may load again—use path conventions with unique names.\n• PIPE with COPY options MATCH_BY_COLUMN_NAME for evolving Parquet schemas.\n• Exactly-once at file level; within-file duplicates need MERGE dedup downstream.\n• LIST @stage compared to COPY_HISTORY detects unloaded files.\n\nKafka landing: include offset in filename for uniqueness and ordering debug.', 'SELECT file_name, status, row_count, last_load_time\nFROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(\n  TABLE_NAME => \'ORDERS\',\n  START_TIME => DATEADD(day, -7, CURRENT_TIMESTAMP())\n))\nORDER BY last_load_time DESC;'),
      item('Compare Snowpipe with Snowpipe Streaming (Kafka API) for real-time ingest.', 'Two ingest modes serve different latency and source requirements.\n• Classic Snowpipe: files in cloud storage, minute-level latency, cheapest for batch micro-files.\n• Snowpipe Streaming: SDK/Kafka API direct insert, sub-second latency, per-row billing model.\n• Streaming for true real-time dashboards; classic pipe for log files dropped in S3.\n• Streaming does not require cloud storage notification setup.\n• Hybrid: streaming to bronze, pipe for bulk historical backfill.\n\nEvaluate monthly cost at expected TPS for each mode.', 'CREATE PIPE bulk_pipe AUTO_INGEST = TRUE AS COPY INTO events FROM @s3_stage;\n\n-- Snowpipe Streaming uses ingest SDK:\n-- INSERT INTO events SELECT PARSE_JSON($1) FROM VALUES (...);\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY;'),
      item('How do you secure Snowpipe access to external stages?', 'Security uses storage integration and least-privilege IAM—not embedded credentials.\n• STORAGE INTEGRATION with ALLOWED_LOCATIONS prefix restricts bucket paths.\n• IAM role trust policy allows Snowflake IAM user to assume role.\n• Pipe owner role needs USAGE on integration, stage, and INSERT on target table.\n• Separate integrations per environment (dev vs prod buckets).\n• Audit pipe DDL and stage changes in ACCESS_HISTORY.\n\nNever create external stage with ACCESS_KEY_ID in production.', 'CREATE STORAGE INTEGRATION prod_s3_int\n  STORAGE_PROVIDER = S3\n  ENABLED = TRUE\n  STORAGE_AWS_ROLE_ARN = \'arn:aws:iam::123:role/sf-prod\'\n  STORAGE_ALLOWED_LOCATIONS = (\'s3://prod-landing/\');\n\nGRANT USAGE ON INTEGRATION prod_s3_int TO ROLE pipe_admin;'),
    ],
    hard: [
      item('Design high-volume Snowpipe architecture for 1 million files per day.', 'Million-file/day ingest requires file batching, path partitioning, and error isolation.\n• Upstream aggregator batches small files to 100–250 MB Parquet before landing—reduces pipe overhead.\n• Hive-style paths: s3://bucket/yyyy/mm/dd/hh/ for partition alignment and debugging.\n• Multiple pipes per domain table to isolate failure blast radius.\n• Monitor PIPE_USAGE_HISTORY credits; file-per-row JSON is anti-pattern at scale.\n• Dead letter prefix for files failing COPY after N retries.\n• Auto-scaling: Snowflake manages pipe compute; focus on notification throughput.\n\nSLA: 95% files loaded within 5 minutes of landing.', 'CREATE PIPE events_pipe AUTO_INGEST = TRUE AS\nCOPY INTO events FROM @stage/events/\nFILE_FORMAT = (TYPE = PARQUET)\nPATTERN = \'.*[.]parquet\';\n\nSELECT COUNT(*), DATE_TRUNC(\'hour\', last_load_time)\nFROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME => \'EVENTS\', START_TIME => DATEADD(day, -1, CURRENT_TIMESTAMP())))\nGROUP BY 2;'),
      item('Lead incident where Snowpipe silently stopped loading for 12 hours.', 'Silent pipe failure causes data freshness SLA breach and downstream stale analytics.\n• Detect: freshness monitor on MAX(loaded_at); pipe pending count; stakeholder reports.\n• Triage: SYSTEM$PIPE_STATUS error field; AWS SQS depth; expired IAM role credentials on integration.\n• Mitigate: ALTER PIPE REFRESH; fix notification; backfill with COPY INTO for missed files.\n• Root cause: S3 event config removed during bucket policy change; or integration DISABLED.\n• Prevent: synthetic canary file every 15 min with alert if not in COPY_HISTORY within 30 min.\n\nCommunicate data gap window; replay downstream DT/tasks after backfill.', 'SELECT SYSTEM$PIPE_STATUS(\'critical_pipe\');\n\nCOPY INTO orders FROM @stage/missed_files/ FILE_FORMAT = parquet_fmt;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY\nWHERE pipe_name = \'CRITICAL_PIPE\'\nORDER BY start_time DESC LIMIT 50;'),
      item('Optimize Snowpipe cost while maintaining 5-minute data freshness SLA.', 'Pipe cost drivers are file count, file size, and transformation complexity in COPY.\n• Batch files upstream: 1000 tiny JSON → one Parquet saves 99% pipe invocations.\n• Load to narrow staging table; MERGE to prod via task—keep pipe COPY simple.\n• Compress with Snappy/Gzip Parquet; avoid CSV for large volumes.\n• FILE_FORMAT with STRIP_OUTER_ARRAY for JSON arrays reduces parse cost.\n• Review SNOWPIPE billing vs batch COPY if latency SLA allows 15-min batch window.\n\nROI: measure credits per million rows pipe vs COPY scheduled.', 'CREATE PIPE optimized_pipe AUTO_INGEST = TRUE AS\nCOPY INTO staging.events FROM @stage\nFILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY);\n\nSELECT SUM(credits_used), COUNT(*)\nFROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY\nWHERE start_time > DATEADD(day, -30, CURRENT_TIMESTAMP());'),
      item('Explain pipe error notifications and integration with incident management.', 'Proactive pipe alerting reduces mean time to detect ingest failures.\n• Snowflake notification integration: email, webhook, SNS, Pub/Sub on pipe error.\n• CREATE NOTIFICATION INTEGRATION + associate with pipe error events.\n• Custom task polls COPY_HISTORY for status = LOAD_FAILED in last 15 minutes.\n• PagerDuty via webhook payload with pipe name, file, error message.\n• Runbook links from alert to SYSTEM$PIPE_STATUS and DESC PIPE checklist.\n\nIntegrate with data observability platform (Monte Carlo, Elementary) for freshness SLAs.', 'CREATE NOTIFICATION INTEGRATION pipe_alerts\n  TYPE = WEBHOOK\n  ENABLED = TRUE\n  WEBHOOK_URL = \'https://hooks.pagerduty.com/integration/xxx/enqueue\';\n\n-- Associate via Snowflake alerts on pipe errors (account-level feature)\nSELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(\n  TABLE_NAME => \'ORDERS\', START_TIME => DATEADD(hour, -1, CURRENT_TIMESTAMP())\n))\nWHERE status = \'LOAD_FAILED\';'),
    ],
  },

  'time-travel': {
    easy: [
      item('What is Time Travel in Snowflake and what is it used for?', 'Time Travel query past states of tables without restoring backups.\n• Query historical data using AT(TIMESTAMP) or AT(OFFSET => seconds) or BEFORE(STATEMENT => id).\n• Undrop dropped tables, schemas, databases within retention window.\n• Investigate data issues: what did row look like yesterday before bad ETL?\n• Retention controlled by DATA_RETENTION_TIME_IN_DAYS (0–90 enterprise).\n• Time Travel storage billed separately in TABLE_STORAGE_METRICS.\n\nDefault retention often 1 day; increase for prod tables needing recovery window.', 'SELECT * FROM orders AT(OFFSET => -3600);\n\nSELECT * FROM orders AT(TIMESTAMP => \'2024-06-15 08:00:00\'::TIMESTAMP_LTZ);\n\nUNDROP TABLE orders;'),
      item('How do you set data retention time on a table?', 'DATA_RETENTION_TIME_IN_DAYS controls Time Travel window per table.\n• Default inherits from database or account parameter DATA_RETENTION_TIME_IN_DAYS.\n• ALTER TABLE ... SET DATA_RETENTION_TIME_IN_DAYS = N.\n• 0 disables Time Travel—use only for truly disposable staging data.\n• Maximum 90 days on Enterprise; 1 day Standard default.\n• Longer retention increases time_travel_bytes storage cost.\n\nAlign retention with recovery RPO: finance tables 30 days, staging 1 day.', 'ALTER TABLE prod.orders SET DATA_RETENTION_TIME_IN_DAYS = 30;\n\nSHOW PARAMETERS LIKE \'DATA_RETENTION_TIME_IN_DAYS\' IN TABLE prod.orders;\n\nSELECT table_name, retention_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLES\nWHERE table_name = \'ORDERS\';'),
      item('How do you undrop a accidentally dropped table?', 'UNDROP restores dropped table metadata and data within Time Travel retention.\n• UNDROP TABLE table_name; restores to schema context.\n• UNDROP DATABASE / SCHEMA for container recovery.\n• If object name reused after drop, UNDROP renames with suffix.\n• After retention expires, only Fail-safe may recover—contact support.\n• Verify grants intact after UNDROP; test SELECT immediately.\n\nPrevention: restrict DROP privilege; use soft-delete column pattern.', 'DROP TABLE prod.sales.orders_backup;\n\nUNDROP TABLE prod.sales.orders_backup;\n\nSELECT COUNT(*) FROM prod.sales.orders_backup;'),
      item('What is the difference between AT and BEFORE clauses?', 'Both query historical state but reference different points in time.\n• AT(TIMESTAMP => ...): state at exact wall-clock time.\n• AT(OFFSET => -N): N seconds before current time.\n• BEFORE(STATEMENT => \'query_id\'): state immediately before that statement executed.\n• BEFORE useful for debugging: find data before specific failed MERGE query_id.\n• Query_id from QUERY_HISTORY links to BEFORE for forensic analysis.\n\nBEFORE requires query_id that modified table—SELECT-only query_ids invalid.', 'SELECT * FROM orders BEFORE(STATEMENT => \'01b2c3d4-0001-abcd-0000-000000000001\');\n\nSELECT query_id, query_text, start_time\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE query_text ILIKE \'%MERGE%orders%\'\nORDER BY start_time DESC LIMIT 5;'),
    ],
    medium: [
      item('How do you investigate data corruption using Time Travel?', 'Time Travel forensic workflow isolates when corruption introduced.\n• Identify approximate corruption time from monitoring or user report.\n• Query AT timestamps bracketing incident comparing row counts and checksums.\n• BEFORE(STATEMENT) on suspected MERGE query_id shows exact pre-change state.\n• CREATE TABLE clean CLONE orders AT(TIMESTAMP => before_incident) for recovery.\n• SWAP or INSERT overwrite from clean clone after validation.\n\nDocument query_ids and timestamps in incident ticket for audit trail.', 'SELECT COUNT(*), SUM(amount) FROM orders AT(TIMESTAMP => \'2024-06-14 23:59:00\');\nSELECT COUNT(*), SUM(amount) FROM orders AT(TIMESTAMP => \'2024-06-15 01:00:00\');\n\nCREATE TABLE orders_recovery CLONE orders AT(TIMESTAMP => \'2024-06-14 23:59:00\');'),
      item('How does Time Travel retention affect streams and pipe consumption?', 'Streams depend on Time Travel to retain unconsumed change metadata.\n• Stream becomes stale when changes fall outside base table retention.\n• Extending retention on source table prevents stream staleness during pipeline outages.\n• Dropping table invalidates streams immediately regardless of retention.\n• Plan retention >= max expected pipeline downtime + safety margin.\n• SHOW STREAMS stale_after column guides retention sizing.\n\nIf pipeline may be down 72h, retention must exceed 72h on source.', 'ALTER TABLE source_orders SET DATA_RETENTION_TIME_IN_DAYS = 7;\n\nSHOW STREAMS ON TABLE source_orders;\n\nSELECT SYSTEM$STREAM_GET_TABLE_TIMESTAMP(\'orders_stream\');'),
      item('Compare CLONE AT timestamp vs Time Travel SELECT for recovery scenarios.', 'Both access historical data but serve different recovery mechanics.\n• SELECT AT: read-only query of historical rows; no new object created.\n• CREATE TABLE ... CLONE ... AT(TIMESTAMP): instant zero-copy snapshot as new table for manipulation.\n• CLONE for recovery: validate clone, then SWAP with corrupted prod table.\n• CLONE does not duplicate storage until modifications—fast and cheap.\n• SELECT AT for analysis only; CLONE AT for actionable recovery artifact.\n\nRecovery pattern: CLONE AT → validate → SWAP → drop bad table.', 'CREATE TABLE orders_fixed CLONE orders AT(TIMESTAMP => \'2024-06-14 12:00:00\');\n\nSELECT COUNT(*) FROM orders_fixed;\n\nALTER TABLE orders SWAP WITH orders_fixed;'),
      item('How do you manage Time Travel storage costs on high-churn tables?', 'High DML tables accumulate large time_travel_bytes quickly.\n• Reduce DATA_RETENTION_TIME_IN_DAYS on staging and scratch tables.\n• TRANSIENT tables: reduced retention, no Fail-safe—significant savings.\n• Batch DML instead of row-by-row updates to reduce version churn.\n• Monitor TABLE_STORAGE_METRICS time_travel_bytes weekly.\n• Archive historical versions to separate history table via SCD2 instead of relying on long Time Travel.\n\nProd fact tables: balance 7-day retention vs compliance requirement.', 'SELECT table_name,\n       time_travel_bytes/POWER(1024,3) AS tt_gb,\n       active_bytes/POWER(1024,3) AS active_gb\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nORDER BY time_travel_bytes DESC LIMIT 15;\n\nALTER TABLE staging.temp SET DATA_RETENTION_TIME_IN_DAYS = 1;'),
    ],
    hard: [
      item('Design retention policy across account for compliance (GDPR) and operational recovery.', 'Retention policy balances legal hold, right-to-erasure, and ops recovery.\n• Classification tags drive retention: PII tables 30-day TT, logs 7-day, staging 1-day.\n• GDPR erasure: DELETE + shorten retention; document that Time Travel copies purge after retention.\n• Legal hold: suspend DROP and extend retention on specific tables via ticket workflow.\n• Automated policy enforcement: task alerts tables with retention exceeding classification limit.\n• Fail-safe always 7 days—cannot disable; factor in compliance timelines.\n\nLegal review sign-off before account-wide retention parameter changes.', 'ALTER TABLE pii.customers SET DATA_RETENTION_TIME_IN_DAYS = 30;\n\nCREATE TAG retention_class ALLOWED_VALUES \'7D\',\'30D\',\'90D\';\nALTER TABLE pii.customers SET TAG retention_class = \'30D\';\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES WHERE tag_name = \'RETENTION_CLASS\';'),
      item('Recover production database after accidental DROP DATABASE by junior admin.', 'DROP DATABASE is catastrophic but recoverable within retention if acted quickly.\n• Immediate: UNDROP DATABASE prod; verify schemas and tables accessible.\n• If name conflict: UNDROP renames with _DROPPED suffix—rename after.\n• Assess downstream: tasks, streams, pipes may need recreation if invalidated.\n• If retention expired: open Snowflake support Fail-safe recovery ticket immediately.\n• Contain: revoke DROP DATABASE from role; enable object deletion protection if available.\n\nPostmortem: break-glass procedure, Terraform state prevents manual DROP, approval workflow.', 'UNDROP DATABASE prod;\n\nSHOW TABLES IN DATABASE prod;\n\nREVOKE DROP DATABASE ON ACCOUNT FROM ROLE junior_developer;'),
      item('Lead forensic analysis using QUERY_HISTORY and Time Travel for audit investigation.', 'Audit investigation reconstructs who changed what and when with evidence chain.\n• QUERY_HISTORY filters DML on sensitive table by user and time range.\n• BEFORE(STATEMENT => query_id) captures pre-change snapshot for each suspect query.\n• ACCESS_HISTORY corroborates object access by role.\n• Export evidence: row samples, query text, user, role, IP from LOGIN_HISTORY join.\n• Preserve query_ids immediately—retention on QUERY_HISTORY is limited (45 days account usage).\n\nDeliver audit package to compliance with immutable timestamped exports.', 'SELECT user_name, role_name, query_text, start_time, query_id\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_text ILIKE \'%customers%\' AND query_type = \'UPDATE\'\n  AND start_time BETWEEN \'2024-06-01\' AND \'2024-06-15\';\n\nSELECT * FROM customers BEFORE(STATEMENT => \'suspect-query-id\');'),
      item('Explain interaction between Time Travel, cloning, and replication for point-in-time consistency.', 'Point-in-time consistency across objects requires coordinated timestamp semantics.\n• CLONE AT(TIMESTAMP) gives consistent snapshot of single table at instant.\n• Multiple table recovery: use same AT timestamp; verify no cross-table transactions broke consistency.\n• Replicated database refresh lag means secondary not at same logical time as primary.\n• Failover to replica: point-in-time on secondary reflects last refresh not primary wall clock.\n• Document RPO: max data loss = replication lag + retention gap.\n\nFinancial close: CLONE all gold tables AT same TIMESTAMP for frozen reporting copy.', 'CREATE TABLE orders_close CLONE orders AT(TIMESTAMP => \'2024-06-30 23:59:59\');\nCREATE TABLE payments_close CLONE payments AT(TIMESTAMP => \'2024-06-30 23:59:59\');\n\nALTER DATABASE prod_replica REFRESH;'),
    ],
  },

  'fail-safe': {
    easy: [
      item('What is Fail-safe in Snowflake and how does it differ from Time Travel?', 'Fail-safe is Snowflake\'s disaster recovery storage after Time Travel expires.\n• Time Travel: user-accessible historical queries and UNDROP within retention (0–90 days).\n• Fail-safe: additional 7-day buffer only recoverable by Snowflake support—not directly queryable.\n• Fail-safe cannot be disabled on permanent tables; no customer control of duration.\n• Billed as failsafe_bytes in storage metrics—separate line item.\n• TRANSIENT tables skip Fail-safe entirely.\n\nUse Time Travel for self-service recovery; Fail-safe for catastrophic loss after retention lapse.', 'SELECT table_name, time_travel_bytes, failsafe_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE failsafe_bytes > 0\nORDER BY failsafe_bytes DESC LIMIT 10;'),
      item('Can users query or UNDROP data in Fail-safe period?', 'Fail-safe data is not directly accessible to customers.\n• No SQL syntax to query Fail-safe period data.\n• UNDROP fails if beyond Time Travel even if within Fail-safe.\n• Recovery requires Snowflake support ticket with table name, drop timestamp, account.\n• Support evaluates recoverability— not guaranteed in all scenarios.\n• Prevention critical: do not rely on Fail-safe as primary backup strategy.\n\nOperational backup: periodic CLONE to DR account or external export.', 'UNDROP TABLE critical_data;  -- fails if beyond Time Travel\n\n-- Contact Snowflake Support with:\nSELECT table_name, dropped_on\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLES\nWHERE table_name = \'CRITICAL_DATA\' AND deleted IS NOT NULL;'),
      item('How is Fail-safe storage billed?', 'Fail-safe contributes to total storage bill as failsafe_bytes.\n• Charged per TB/month similar to Time Travel storage rates.\n• Visible in TABLE_STORAGE_METRICS per table.\n• High-churn large tables accumulate significant failsafe_bytes briefly after Time Travel purge.\n• TRANSIENT tables avoid failsafe_bytes—cost saving for disposable data.\n• Cannot reduce failsafe duration—only reduce churn and retention to minimize volume.\n\nFinOps report: top tables by failsafe_bytes week over week.', 'SELECT SUM(failsafe_bytes)/POWER(1024,4) AS failsafe_tb\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;\n\nSELECT table_name, failsafe_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nORDER BY failsafe_bytes DESC LIMIT 10;'),
      item('Why do TRANSIENT tables not have Fail-safe protection?', 'TRANSIENT designation opts out of extended disaster recovery for cost savings.\n• TRANSIENT database or table: no Fail-safe, reduced Time Travel retention.\n• Suitable for rebuildable staging data with external source of truth.\n• Permanent tables always have 7-day Fail-safe after Time Travel—cannot opt out.\n• Compliance workloads requiring guaranteed recovery should never use TRANSIENT.\n• Explicit architectural choice: speed/cost vs recoverability.\n\nDocument in data catalog which layers are TRANSIENT and rebuild procedure.', 'CREATE TRANSIENT TABLE staging.tmp_load (id INT, data VARCHAR);\n\nSELECT table_name, table_type, retention_time\nFROM SNOWFLAKE.INFORMATION_SCHEMA.TABLES\nWHERE table_name = \'TMP_LOAD\';'),
    ],
    medium: [
      item('When should you open a Snowflake support case for Fail-safe recovery?', 'Support recovery is last resort when self-service Time Travel options exhausted.\n• Table dropped or corrupted beyond DATA_RETENTION_TIME_IN_DAYS.\n• Within 7 days after Time Travel data purged (Fail-safe window).\n• Gather: account locator, table FQN, drop timestamp (from TABLES view deleted column), incident description.\n• Recovery not guaranteed—depends on internal state; may take hours to days.\n• Parallel: rebuild from external backup if RTO cannot wait support SLA.\n\nRunbook escalation tree: UNDROP → CLONE AT → support ticket → rebuild from lake.', 'SELECT table_catalog, table_schema, table_name, deleted\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLES\nWHERE table_name = \'ORDERS\' AND deleted IS NOT NULL;\n\n-- Open support case with above metadata'),
      item('How do you design backup strategy beyond Fail-safe for critical tables?', 'Fail-safe alone insufficient for enterprise RPO/RTO requirements.\n• Periodic CLONE to DR account in secondary region—metadata instant, storage shared until change.\n• EXPORT to external stage (Parquet) scheduled via task for air-gapped backup.\n• Database replication to secondary account with scheduled REFRESH.\n• Third-party backup tools (Accurics, etc.) if policy requires.\n• Test restore quarterly: CLONE from DR or IMPORT from external stage.\n\n3-2-1 rule adapted: 3 copies, 2 regions, 1 external format export.', 'CREATE DATABASE dr_backup CLONE prod;\n\nCOPY INTO @backup_stage/orders/ FROM orders\nFILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY)\nHEADER = TRUE;\n\nALTER DATABASE prod_replica REFRESH;'),
      item('Explain storage lifecycle from active data through Time Travel to Fail-safe purge.', 'Data passes through distinct storage lifecycle phases automatically.\n• Active: current committed rows visible to queries.\n• Time Travel: historical versions retained per DATA_RETENTION_TIME_IN_DAYS after change/delete.\n• Fail-safe: 7 days after Time Travel expiry—internal disaster recovery only.\n• Permanent purge: after Fail-safe, data irrecoverable.\n• DROP TABLE: data enters Time Travel immediately; active_bytes zeroes.\n\nTimeline diagram in runbooks helps stakeholders understand recovery windows.', 'SELECT table_name, active_bytes, time_travel_bytes, failsafe_bytes,\n       retention_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_name = \'ORDERS\';'),
      item('How does dropping a large table impact Fail-safe storage temporarily?', 'Large dropped tables spike time_travel then failsafe_bytes before eventual purge.\n• DROP moves all active_bytes to time_travel_bytes immediately.\n• After retention: transitions toward failsafe_bytes for 7 days.\n• Account storage metric may jump noticeably—FinOps alert warranted.\n• UNDROP within retention avoids failsafe transition entirely.\n• Plan large table drops during budget review period with stakeholder notice.\n\nAlternative: TRUNCATE if goal is empty table not remove object metadata.', 'DROP TABLE legacy_huge_fact;\n\nSELECT SUM(storage_bytes) FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE\nWHERE usage_date >= CURRENT_DATE() - 7;\n\nUNDROP TABLE legacy_huge_fact;  -- if within retention'),
    ],
    hard: [
      item('Design enterprise data recovery framework with defined RPO/RTO per data tier.', 'Tiered recovery framework maps business criticality to technical controls.\n• Tier 1 (critical): 30-day Time Travel, cross-region replica, hourly external export, RTO 4h.\n• Tier 2 (important): 7-day retention, nightly CLONE to DR, RTO 24h.\n• Tier 3 (staging): TRANSIENT, 1-day retention, rebuild from source, RTO 72h.\n• Runbooks per tier with automated monitoring of retention compliance.\n• Annual DR drill: simulate drop, execute recovery, measure actual RTO.\n• Executive dashboard: % tables compliant with tier policy.\n\nAlign with BCP documentation and regulatory examination expectations.', 'CREATE TAG recovery_tier ALLOWED_VALUES \'T1\', \'T2\', \'T3\';\nALTER TABLE finance.ledger SET TAG recovery_tier = \'T1\';\nALTER TABLE finance.ledger SET DATA_RETENTION_TIME_IN_DAYS = 30;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES WHERE tag_name = \'RECOVERY_TIER\';'),
      item('Lead crisis management when Time Travel expired and Fail-safe is only hope.', 'Crisis protocol when self-service recovery window missed.\n• Hour 0: confirm drop timestamp; calculate Fail-safe deadline (retention expiry + 7 days).\n• Hour 1: open Sev-1 support ticket with complete metadata; parallel rebuild team activated.\n• Communicate to leadership: recovery uncertain; rebuild ETA as backup plan.\n• Preserve QUERY_HISTORY and audit logs before 45-day expiry for investigation.\n• Post-crisis: root cause (who dropped, why no retention), policy changes mandatory.\n\nNever promise support recovery certainty to business stakeholders.', 'SELECT table_name, deleted, retention_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLES\nWHERE table_schema = \'FINANCE\' AND deleted IS NOT NULL;\n\n-- Support ticket + parallel:\nCREATE TABLE ledger_rebuild AS SELECT * FROM @external_backup/ledger/;'),
      item('Compare Fail-safe recovery vs logical backup restore for compliance auditability.', 'Auditors evaluate recovery provability and process documentation.\n• Fail-safe: Snowflake-internal, opaque process, limited customer audit trail, uncertain timeline.\n• Logical backup (EXPORT Parquet to WORM storage): customer-controlled, provable restore tests, checksums.\n• Regulators often prefer demonstrable restore over vendor-opaque recovery.\n• Document every restore test with row-count reconciliation signed by data owner.\n• Fail-safe remains safety net—not primary compliance control.\n\nAudit evidence package: export logs, restore test results, retention policy tags.', 'COPY INTO @worm_backup/ledger/ FROM ledger\nFILE_FORMAT = (TYPE = PARQUET) OVERWRITE = TRUE;\n\nCREATE TABLE ledger_restore AS SELECT * FROM @worm_backup/ledger/;\n\nSELECT COUNT(*) FROM ledger UNION ALL SELECT COUNT(*) FROM ledger_restore;'),
      item('Model total storage cost including Fail-safe for high-churn fact table over 12 months.', 'Cost model projects active + time_travel + failsafe bytes from DML patterns.\n• Inputs: daily insert TB, update %, delete %, retention days.\n• Each UPDATE/DELETE creates new version in Time Travel until retention purge.\n• Model monthly failsafe spike when large purge events occur.\n• Sensitivity analysis: retention 7 vs 30 days on churn rate 20% daily updates.\n• Present CFO chart: cost vs retention trade-off curve.\n\nRecommendation: reduce churn via batch MERGE; shorten staging retention.', 'SELECT DATE_TRUNC(\'month\', usage_date) AS month,\n       AVG(storage_bytes)/POWER(1024,4) AS avg_tb\nFROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE\nGROUP BY 1 ORDER BY 1;\n\nSELECT table_name, active_bytes, time_travel_bytes, failsafe_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_name = \'FACT_EVENTS\';'),
    ],
  },

  'zero-copy-clone': {
    easy: [
      item('What is zero-copy clone in Snowflake?', 'Zero-copy clone creates instant copy of database, schema, or table without duplicating storage.\n• Clone shares underlying micro-partitions with source until diverging changes occur.\n• CREATE ... CLONE completes in seconds regardless of table size (terabytes).\n• Changes to clone or source create new partitions only for modified data (copy-on-write).\n• Used for dev/test environments, backups, experimentation, blue-green deploys.\n• CLONE can include AT(TIMESTAMP) for point-in-time clone.\n\nRevolutionary for data platform agility—no more multi-hour database copies.', 'CREATE DATABASE dev_db CLONE prod_db;\n\nCREATE TABLE orders_dev CLONE prod.sales.orders;\n\nSELECT COUNT(*) FROM dev_db.sales.orders;'),
      item('How does storage billing work for cloned objects?', 'Clones minimize storage cost through shared micro-partitions.\n• Initial clone: zero additional active_bytes—all partitions shared with source.\n• Storage grows only when clone or source modifies data—new partitions allocated to changer.\n• Dev environment that only reads prod clone costs nearly zero extra storage.\n• Heavy writes in dev clone accumulate independent active_bytes.\n• Monitor TABLE_STORAGE_METRICS on clones to detect unexpected divergence cost.\n\nFinOps win: refresh dev weekly via CLONE replaces stale full copy approach.', 'CREATE SCHEMA dev_test CLONE prod.sales;\n\nSELECT table_name, active_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_schema = \'DEV_TEST\';'),
      item('Can you clone at a specific point in time?', 'Time Travel integration allows historical clones.\n• CREATE TABLE new CLONE source AT(TIMESTAMP => ...).\n• AT(OFFSET => -seconds) also supported.\n• Useful for reproducing bug with yesterday\'s data in isolated clone schema.\n• Retention must cover requested timestamp or clone fails.\n• Cloned historical state diverges independently after creation.\n\nPattern: weekly automated task creates AT clone for regression test dataset.', 'CREATE TABLE orders_june15 CLONE orders\n  AT(TIMESTAMP => \'2024-06-15 00:00:00\'::TIMESTAMP_LTZ);\n\nSELECT COUNT(*) FROM orders_june15;'),
      item('What objects can be cloned in Snowflake?', 'Clone operation supported at database, schema, and table levels.\n• DATABASE CLONE includes schemas, tables, views, most objects within.\n• SCHEMA CLONE copies tables and views in schema.\n• TABLE CLONE copies single table data and structure.\n• Some objects not cloned: streams (recreate manually), tasks may need verification.\n• CLONE across databases requires appropriate privileges on source.\n\nAfter database clone: verify streams, pipes, tasks recreated or scripted.', 'CREATE DATABASE qa CLONE prod;\n\nSHOW TABLES IN DATABASE qa;\n\nSHOW STREAMS IN DATABASE qa;'),
    ],
    medium: [
      item('How do you use clone for blue-green table deployment?', 'Blue-green via SWAP enables zero-downtime table replacement.\n• Build new version: CREATE TABLE orders_green CLONE orders; modify green table with fixed ETL.\n• Validate green: row counts, checksums, sample queries.\n• Cutover: ALTER TABLE orders SWAP WITH orders_green; instant metadata pointer swap.\n• Rename if needed: ALTER TABLE orders_green RENAME TO orders after swap.\n• Rollback: SWAP back if green issues discovered quickly.\n\nUsers query orders throughout—SWAP is metadata operation invisible to SELECT.', 'CREATE TABLE orders_green CLONE orders;\n\nINSERT INTO orders_green SELECT * FROM staging_orders_fixed;\n\nALTER TABLE orders SWAP WITH orders_green;'),
      item('What privileges are required to clone production data to dev?', 'Clone requires read access to source and create on target.\n• CREATE DATABASE on account + USAGE on source database minimum.\n• Role-based pattern: PROD_READER role with SELECT on prod; DEV_ADMIN creates dev CLONE.\n• Consider data masking: clone copies raw PII—mask in dev via post-clone views or masking policies.\n• Some orgs block prod clone entirely; use sanitized subset CTAS instead.\n• Audit CLONE operations in QUERY_HISTORY and ACCESS_HISTORY.\n\nGovernance: automated weekly dev refresh with approved role only.', 'GRANT USAGE ON DATABASE prod TO ROLE dev_clone_svc;\nGRANT CREATE DATABASE ON ACCOUNT TO ROLE dev_clone_svc;\n\nCREATE OR REPLACE DATABASE dev CLONE prod;\n\nSELECT query_text, user_name FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_text ILIKE \'%CLONE%prod%\' ORDER BY start_time DESC LIMIT 5;'),
      item('How do clones interact with Time Travel and dropped source tables?', 'Clone independence from source has limits when source is dropped or modified.\n• DROP source table: clone retains shared partitions until clone modified or dropped.\n• UNDROP source does not affect existing clone.\n• Source Time Travel changes do not retroactively affect existing clone.\n• CLONE from dropped table within retention via UNDROP first then clone.\n• Long-lived dev clone from prod: refresh clone weekly to avoid stale data.\n\nDocument dev clone refresh SLA aligned with prod release cadence.', 'DROP TABLE prod.sandbox_test;\n\n-- Clone still queryable:\nSELECT COUNT(*) FROM dev.sandbox_test;\n\nCREATE OR REPLACE DATABASE dev CLONE prod;'),
      item('Troubleshoot CLONE failures due to permissions or missing objects.', 'Clone failures usually indicate privilege gaps or unsupported object types.\n• Error "does not exist or not authorized": missing USAGE on source database/schema.\n• Encrypted objects or policy restrictions may block clone in some configurations.\n• Verify source exists and not dropped beyond retention.\n• CLONE across accounts not supported directly—use replication or SHARE instead.\n• Check QUERY_HISTORY error_message for specific failure detail.\n\nTest: CLONE single small table before full database clone.', 'SHOW GRANTS TO ROLE dev_admin;\n\nCREATE TABLE test_clone CLONE prod.sales.small_table;\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE query_text ILIKE \'%CLONE%\' AND error_message IS NOT NULL\nORDER BY start_time DESC LIMIT 5;'),
    ],
    hard: [
      item('Design automated dev/staging refresh pipeline using zero-copy clone.', 'Automated refresh keeps lower environments current with minimal ops burden.\n• Weekly task: CREATE OR REPLACE DATABASE dev CLONE prod WITH GRANT OPTION OFF.\n• Post-clone: apply masking policies, revoke prod-sensitive grants, resize warehouses down.\n• Sanitization procedure on PII columns via UPDATE on clone (creates new partitions—acceptable in dev).\n• Notify developers in Slack on refresh completion with schema change summary.\n• Rollback: keep previous dev as dev_backup one day before REPLACE.\n\nIaC: Terraform snowflake_database resource with clone source parameter.', 'CREATE OR REPLACE TASK refresh_dev\n  WAREHOUSE = admin_wh\n  SCHEDULE = \'USING CRON 0 2 * * 0 UTC\'\n  AS CREATE OR REPLACE DATABASE dev CLONE prod;\n\nALTER TASK refresh_dev RESUME;\n\nCREATE OR REPLACE DATABASE dev_backup CLONE dev;'),
      item('Lead security review of prod-to-dev cloning with PII and SOC2 implications.', 'Prod clone to dev is common SOC2 audit finding if inadequately controlled.\n• Risk: developers access full prod PII in unsecured dev account.\n• Controls: masking policies auto-applied post-clone; dev account separate SSO group.\n• Alternative: clone only non-PII schemas; synthetic data generation for PII tables.\n• Log all clone operations; quarterly access review on dev post-refresh.\n• Data processing agreement: dev clone still subject to GDPR if EU PII.\n\nAuditor evidence: masking policy DDL, access review sign-offs, clone task audit log.', 'ALTER TABLE dev.customers MODIFY COLUMN ssn SET MASKING POLICY ssn_mask;\n\nREVOKE ROLE prod_admin FROM USER developer;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_text ILIKE \'%CREATE%DATABASE%dev%CLONE%\';'),
      item('Optimize clone-heavy workflow costing 20TB additional storage from dev divergence.', 'Storage creep occurs when many clones modify data independently.\n• Root cause: developers run UPDATE on full dev clone instead of subsets.\n• Policy: dev is read-mostly; writes only in personal schemas.\n• Weekly REPLACE DATABASE dev CLONE prod resets divergence—zero storage from old dev.\n• Personal sandboxes: CLONE single tables not full database.\n• Monitor active_bytes growth rate on dev vs prod ratio.\n\nTarget: dev storage <5% of prod via weekly refresh and write restrictions.', 'SELECT database_name, SUM(active_bytes)/POWER(1024,4) AS tb\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nGROUP BY 1 ORDER BY 2 DESC;\n\nCREATE OR REPLACE DATABASE dev CLONE prod;'),
      item('Compare zero-copy clone vs database replication for DR use cases.', 'Clone and replication serve different DR and environment provisioning needs.\n• Clone: point-in-time snapshot, same account, instant, no ongoing sync—manual refresh.\n• Replication: continuous cross-account/region sync, scheduled REFRESH, failover support.\n• DR: replication not clone—RPO requires automated refresh not weekly manual CLONE.\n• Dev refresh: clone ideal—cheap, fast, same-region.\n• Combine: replicate prod to DR account; CLONE from replica for DR testing without touching prod.\n\nDecision tree on slide: RPO < 1h → replication; dev env → clone.', 'ALTER DATABASE prod ENABLE REPLICATION TO ACCOUNTS dr_account;\n\nCREATE DATABASE prod_dr CLONE prod;  -- same-account snapshot only\n\nALTER DATABASE prod_replica REFRESH;'),
    ],
  },

  'data-sharing': {
    easy: [
      item('What is Secure Data Sharing in Snowflake?', 'Secure Data Sharing enables live read-only access to data across Snowflake accounts without copying.\n• Provider shares tables/views via SHARE object; consumer mounts as imported database.\n• No ETL duplication—consumer queries provider data in real time.\n• Provider controls exactly which objects and columns are shared.\n• Billing: consumer pays compute; provider pays storage.\n• Works cross-region and cross-cloud in supported configurations.\n\nRevolutionizes B2B data exchange vs SFTP file drops.', 'CREATE SHARE sales_share;\nGRANT USAGE ON DATABASE prod TO SHARE sales_share;\nGRANT SELECT ON TABLE prod.analytics.revenue TO SHARE sales_share;\n\nALTER SHARE sales_share ADD ACCOUNTS = consumer_account;'),
      item('How does a consumer access a shared database?', 'Consumer mounts share from provider as imported database in their account.\n• Provider runs ALTER SHARE ... ADD ACCOUNTS = consumer_org_account.\n• Consumer: CREATE DATABASE imported_db FROM SHARE provider_account.share_name.\n• Query like local tables: SELECT * FROM imported_db.analytics.revenue.\n• Consumer needs warehouse; provider data not copied.\n• SHOW GRANTS IMPORTED ON DATABASE shows share lineage.\n\nConsumer cannot see provider objects not explicitly granted to share.', 'CREATE DATABASE partner_data FROM SHARE provider_acct.sales_share;\n\nSELECT * FROM partner_data.analytics.revenue LIMIT 10;\n\nSHOW IMPORTED DATABASES;'),
      item('What is the difference between a share and a shared database?', 'Terminology distinguishes provider object vs consumer view.\n• SHARE: provider-side securable listing shared objects.\n• Shared database: consumer-side imported database from share.\n• One share can grant to multiple consumer accounts.\n• Consumer database name chosen by consumer independently of provider name.\n• Reader accounts: Snowflake-managed lightweight consumer without full account.\n\nProvider manages SHARE; consumers manage their imported database names.', 'SHOW SHARES;\n\nDESC SHARE sales_share;\n\nCREATE DATABASE acme_revenue FROM SHARE acme_org.revenue_share;'),
      item('Can consumers modify shared data?', 'Shared data is read-only for consumers by default.\n• Consumers can SELECT shared tables and create local views on shares.\n• INSERT/UPDATE/DELETE on provider data not permitted through share.\n• Consumers can combine shared data with local tables in queries.\n• Write-back requires separate API or reverse share pattern.\n• Secure views on provider side hide underlying columns from consumer.\n\nMulti-party collaboration uses listing/marketplace or dedicated write APIs.', 'SELECT s.region, l.local_factor\nFROM partner_share.analytics.revenue s\nJOIN local.ref_factors l ON s.region = l.region;\n\nSHOW GRANTS TO SHARE sales_share;'),
    ],
    medium: [
      item('How do you share secure views instead of base tables?', 'Secure views hide logic and columns while enabling controlled sharing.\n• CREATE SECURE VIEW with filtered/aggregated data; GRANT SELECT ON VIEW TO SHARE.\n• Secure keyword prevents consumers from viewing underlying base table definitions.\n• Row-level filters in view definition limit data exposure.\n• Do not share base table if view suffices—principle of least sharing.\n• Test consumer perspective in reader account before granting production consumer.\n\nSecure view required when sharing view (non-secure views cannot be shared).', 'CREATE SECURE VIEW analytics.revenue_masked AS\nSELECT region, product, amount  -- exclude customer_id\nFROM analytics.revenue WHERE amount > 0;\n\nGRANT SELECT ON VIEW analytics.revenue_masked TO SHARE sales_share;'),
      item('Troubleshoot "Object does not exist or not authorized" on shared database.', 'Share access errors involve provider grants and consumer mount steps.\n• Consumer: verify CREATE DATABASE FROM SHARE completed; SHOW DATABASES.\n• Provider: confirm ALTER SHARE ADD ACCOUNTS includes correct consumer account org+account.\n• Provider: USAGE on database, SELECT on tables granted TO SHARE.\n• Replication lag if share on replicated database not refreshed.\n• Consumer role needs USAGE on imported database and SELECT on shared schemas.\n\nProvider runs DESC SHARE to list grants; consumer runs SHOW GRANTS ON DATABASE.', 'DESC SHARE provider_acct.sales_share;\n\nSHOW GRANTS ON DATABASE partner_data;\n\nGRANT IMPORTED PRIVILEGES ON DATABASE partner_data TO ROLE analyst;'),
      item('How does data sharing work with Snowflake Marketplace listings?', 'Marketplace extends sharing to many consumers with monetization and discovery.\n• Provider creates listing from share; consumers request access via Marketplace UI.\n• Free or paid listings with Stripe integration for billing.\n• Data never leaves provider account; consumers query in place.\n• Automated legal terms acceptance tracked per consumer.\n• Private listings for specific consumer accounts without public discovery.\n\nEnterprise data products team manages listing lifecycle and SLA.', 'CREATE SHARE marketplace_kpi_share;\nGRANT SELECT ON TABLE prod.kpis.daily TO SHARE marketplace_kpi_share;\n\n-- Provider UI: Create Listing from share\n-- Consumer UI: Get Data -> create imported database'),
      item('Explain cross-region and cross-cloud data sharing considerations.', 'Sharing works across regions/clouds with latency and egress implications.\n• Provider and consumer accounts can be in different regions; queries cross network.\n• Latency higher for cross-region SELECT; consumers should aggregate locally if heavy.\n• Egress costs may apply on provider cloud side for cross-cloud sharing.\n• Replication can place share data closer to consumer region before sharing.\n• Verify account edition and region support matrix in Snowflake docs.\n\nArchitecture: replicate to EU, share from EU account to EU consumers for GDPR.', 'ALTER DATABASE eu_prod ENABLE REPLICATION TO ACCOUNTS eu_consumer_acct;\n\nCREATE SHARE eu_share;\nGRANT SELECT ON TABLE eu_prod.analytics.kpis TO SHARE eu_share;\n\nALTER SHARE eu_share ADD ACCOUNTS = eu_consumer_acct;'),
    ],
    hard: [
      item('Design multi-tenant data provider platform sharing datasets to 200 customers.', 'Provider platform scales sharing with automation and isolation.\n• Per-customer SHARE or secure view with tenant filter; automated provisioning via Terraform.\n• Naming: share_customer_{id} with SELECT on tenant-specific secure view.\n• Reader accounts for customers without Snowflake—lower friction onboarding.\n• Monitoring: ACCESS_HISTORY per share; alert on anomalous scan volume.\n• Offboarding: ALTER SHARE ... REMOVE ACCOUNTS; audit trail retention.\n• SLA: 99.9% share availability; incident comms to all consumers on outage.\n\nAutomate consumer onboarding API: validate contract → ADD ACCOUNTS → notify.', 'CREATE SECURE VIEW analytics.tenant_100_data AS\nSELECT * FROM analytics.all_data WHERE tenant_id = 100;\n\nCREATE SHARE share_tenant_100;\nGRANT SELECT ON VIEW analytics.tenant_100_data TO SHARE share_tenant_100;\n\nALTER SHARE share_tenant_100 ADD ACCOUNTS = tenant100_acct;'),
      item('Lead incident when provider accidentally shared PII table instead of masked view.', 'Data sharing misconfiguration is a potential data breach requiring immediate response.\n• Detect: consumer reports unexpected columns; or internal audit of DESC SHARE.\n• Contain: REVOKE SELECT ON TABLE pii_table FROM SHARE immediately.\n• Assess: ACCESS_HISTORY on provider for consumer query patterns downloading PII.\n• Notify: legal, affected consumers, potentially regulatory bodies per jurisdiction.\n• Fix: share only secure view; recreate consumer imported database.\n• Prevent: CI validation on share DDL; no direct table grants to shares in prod.\n\nPostmortem: mandatory security review on all new share grants.', 'REVOKE SELECT ON TABLE prod.raw.customers FROM SHARE external_share;\n\nGRANT SELECT ON VIEW prod.secure.customers_masked TO SHARE external_share;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY\nWHERE object_name = \'CUSTOMERS\' AND query_start_time > DATEADD(day, -7, CURRENT_TIMESTAMP());'),
      item('Compare data sharing vs COPY OUT for partner data delivery compliance.', 'Compliance teams evaluate data residency and audit requirements.\n• Sharing: data stays in provider account; consumer compute only; audit via ACCESS_HISTORY both sides.\n• COPY OUT: data physically copied to consumer cloud—residency transfer; DPA implications.\n• Some contracts prohibit data leaving provider account—sharing only option.\n• Others require consumer-owned copy for independence—scheduled EXPORT to consumer stage.\n• Hybrid: share for live queries; periodic EXPORT for consumer archival.\n\nLegal sign-off documents data flow diagram per delivery method.', 'COPY INTO @consumer_stage/partner_feed/ FROM secure_view\nFILE_FORMAT = (TYPE = PARQUET);\n\n-- vs live share:\nSELECT COUNT(*) FROM imported_partner.secure.daily_feed;'),
      item('Architect bi-directional analytics collaboration between parent and subsidiary accounts.', 'Bi-directional needs require two shares or centralized account model.\n• Snowflake sharing is one-directional per share.\n• Parent shares consolidated data down; subsidiary shares regional data up via separate share.\n• Alternatively: all data in parent account; subsidiaries get reader accounts or roles.\n• ETL in each account publishes to local share; consumers mount multiple imported databases.\n• Governance: data mesh with domain-owned shares and federated governance council.\n\nAvoid share loops; diagram data flows unambiguously for auditors.', 'CREATE SHARE subsidiary_apac_share;\nGRANT SELECT ON TABLE apac.regional.sales TO SHARE subsidiary_apac_share;\nALTER SHARE subsidiary_apac_share ADD ACCOUNTS = parent_hq_acct;\n\nCREATE DATABASE apac_data FROM SHARE subsidiary_apac.subsidiary_apac_share;'),
    ],
  },
};

export const SCENARIO_DATA = [
  {
    title: 'Warehouse Performance Issues',
    difficulty: 'easy',
    q: 'Users report dashboards timing out during business hours. What is your troubleshooting approach?',
    a: 'Warehouse performance issues during peak hours require systematic isolation of compute bottlenecks.\n• Confirm scope: which dashboards, warehouses, and time window; check if ETL and BI share same warehouse.\n• Immediate: identify running queries in QUERY_HISTORY with high total_elapsed_time and bytes_scanned.\n• Check WAREHOUSE_LOAD_HISTORY for avg_queued_load > 0 indicating concurrency saturation.\n• Short-term mitigation: enable multi-cluster scaling (increase MAX_CLUSTER_COUNT) or temporarily resize up one size.\n• Separate BI warehouse from ETL if shared; reschedule heavy batch jobs off-peak.\n• Communicate ETA to users; monitor queue clearing.\n\nRoot cause candidates: undersized warehouse, long-running queries blocking slots, missing clustering causing full scans.',
    cmd: 'SELECT warehouse_name, avg_running, avg_queued_load, avg_blocked\nFROM TABLE(INFORMATION_SCHEMA.WAREHOUSE_LOAD_HISTORY(\n  DATE_RANGE_START => DATEADD(hour, -4, CURRENT_TIMESTAMP())\n));\n\nSELECT query_id, user_name, total_elapsed_time, bytes_scanned, query_text\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE execution_status = \'RUNNING\' OR start_time > DATEADD(hour, -2, CURRENT_TIMESTAMP())\nORDER BY total_elapsed_time DESC LIMIT 15;\n\nALTER WAREHOUSE bi_wh SET MAX_CLUSTER_COUNT = 4;',
  },
  {
    title: 'Query Optimization Regression',
    difficulty: 'easy',
    q: 'A critical report went from 30 seconds to 12 minutes after a deployment. How do you investigate?',
    a: 'Query regression after deployment points to SQL change, data volume shift, or statistics drift.\n• Get query_id before and after from QUERY_HISTORY filtered by query_tag or user.\n• Compare partitions_scanned, partitions_total, bytes_scanned between versions.\n• Diff query text: new JOIN, removed filter, SELECT *, function on filter column.\n• Check if deployment included bulk load degrading clustering depth.\n• Test fix: rewrite SQL with sargable predicates; USE_CACHED_RESULT=FALSE for fair benchmark.\n• Rollback deployment if deadline critical while optimizing.\n\nDocument findings: root cause query change, fix PR, validation metrics post-fix.',
    cmd: 'SELECT query_id, query_text, partitions_scanned, partitions_total,\n       bytes_scanned, total_elapsed_time, start_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_text ILIKE \'%daily_revenue%\'\n  AND start_time > DATEADD(day, -3, CURRENT_TIMESTAMP())\nORDER BY start_time DESC;\n\nALTER SESSION SET USE_CACHED_RESULT = FALSE;\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ANALYTICS.DAILY_REVENUE\', \'(ORDER_DATE)\');',
  },
  {
    title: 'Cost Control Alert',
    difficulty: 'easy',
    q: 'FinOps alerts that daily credit usage exceeded threshold by 200%. What steps do you take?',
    a: 'Credit spike triage balances immediate spend control with production stability.\n• Identify top warehouses by credits in WAREHOUSE_METERING_HISTORY today vs 7-day baseline.\n• Check for warehouses running 24/7 without AUTO_SUSPEND; new oversized warehouse created.\n• QUERY_HISTORY: top bytes_scanned queries and new query patterns.\n• Snowpipe and automatic clustering history for unexpected background spend.\n• Immediate: suspend non-critical warehouses; enable resource monitor SUSPEND on dev.\n• Communicate with engineering leads before suspending prod ETL warehouses.\n\nFollow-up: IaC review, tagging compliance, weekly credit dashboard.',
    cmd: 'SELECT warehouse_name, SUM(credits_used) AS credits_today\nFROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY\nWHERE start_time >= DATE_TRUNC(\'day\', CURRENT_TIMESTAMP())\nGROUP BY 1 ORDER BY 2 DESC;\n\nSELECT user_name, SUM(credits_used_compute) AS credits\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE start_time >= DATE_TRUNC(\'day\', CURRENT_TIMESTAMP())\nGROUP BY 1 ORDER BY 2 DESC LIMIT 10;\n\nALTER WAREHOUSE dev_wh SET AUTO_SUSPEND = 60;',
  },
  {
    title: 'Data Sharing Access Denied',
    difficulty: 'easy',
    q: 'A partner cannot query your shared dataset and reports authorization errors. How do you resolve?',
    a: 'Share access failures require coordinated provider and consumer debugging.\n• Provider: DESC SHARE — verify SELECT grants on tables/views and USAGE on database schema.\n• Confirm ALTER SHARE ADD ACCOUNTS used correct consumer organization and account name.\n• Consumer: verify imported database exists via SHOW DATABASES or SHOW IMPORTED DATABASES.\n• Consumer: GRANT IMPORTED PRIVILEGES on database to partner role; role must be active.\n• Check if shared object was dropped/recreated — may need re-grant TO SHARE.\n• Test with provider-created reader account mimicking consumer.\n\nResolution SLA: 4-hour partner onboarding with documented checklist.',
    cmd: 'DESC SHARE partner_share;\n\nSHOW GRANTS TO SHARE partner_share;\n\n-- Consumer account:\nSHOW GRANTS ON DATABASE imported_partner_data;\n\nGRANT IMPORTED PRIVILEGES ON DATABASE imported_partner_data TO ROLE partner_analyst;',
  },
  {
    title: 'Snowpipe Ingestion Failure',
    difficulty: 'easy',
    q: 'Files are landing in S3 but the target table has not received new rows for 2 hours. What do you check?',
    a: 'Snowpipe stall diagnosis traces the notification-to-load pipeline end to end.\n• SYSTEM$PIPE_STATUS(pipe): pending_file_count, executionState, error messages.\n• COPY_HISTORY: recent LOAD_FAILED entries with first_error_message.\n• AWS: S3 event notification → SQS queue per DESC PIPE notification_channel.\n• Storage integration: ALLOWED_LOCATIONS covers file prefix; IAM role trust intact.\n• Test: ALTER PIPE ... REFRESH for manual poll — if works, notification path broken.\n• Backfill missed files: COPY INTO from stage path after fix.\n\nPrevent recurrence: synthetic file canary with alert on missing COPY_HISTORY entry.',
    cmd: 'SELECT SYSTEM$PIPE_STATUS(\'sales.public.events_pipe\');\n\nSELECT file_name, status, first_error_message, last_load_time\nFROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(\n  TABLE_NAME => \'EVENTS\',\n  START_TIME => DATEADD(hour, -4, CURRENT_TIMESTAMP())\n));\n\nALTER PIPE events_pipe REFRESH;\n\nDESC INTEGRATION s3_landing_int;',
  },
  {
    title: 'Warehouse Auto-Suspend Loop',
    difficulty: 'easy',
    q: 'A warehouse suspends and resumes every few minutes causing query delays. What is happening and how do you fix it?',
    a: 'Auto-suspend thrashing occurs when background activity repeatedly wakes the warehouse.\n• Identify keep-alive queries: SHOW WAREHOUSES; check running queries in QUERY_HISTORY every few minutes.\n• Common culprits: monitoring tool polling, task with 1-minute schedule, stream-triggered task, BI tool connection test.\n• AUTO_SUSPEND too aggressive (60s) with periodic job every 90s causes suspend/resume cycle.\n• Fix: increase AUTO_SUSPEND above job interval; move monitoring to serverless tasks or separate tiny warehouse.\n• Consolidate scheduled jobs to run sequentially in one wake window.\n\nMeasure: warehouse uptime % should drop after fix; credits should decrease.',
    cmd: 'SHOW WAREHOUSES LIKE \'etl_wh\';\n\nSELECT query_text, start_time, user_name, role_name\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE warehouse_name = \'ETL_WH\'\n  AND start_time > DATEADD(hour, -2, CURRENT_TIMESTAMP())\nORDER BY start_time;\n\nALTER WAREHOUSE etl_wh SET AUTO_SUSPEND = 600;',
  },
  {
    title: 'Clustering Not Improving Pruning',
    difficulty: 'easy',
    q: 'You added CLUSTER BY but queries still scan 90% of partitions. What went wrong and how do you fix it?',
    a: 'Clustering not helping usually means wrong key, unsorted loads, or insufficient recluster time.\n• Verify clustering depth via SYSTEM$CLUSTERING_INFORMATION — depth >4 means poor clustering.\n• Confirm query filters use clustering columns directly without functions.\n• Check if bulk unsorted load happened after CLUSTER BY — depth degrades until recluster completes.\n• Wrong key: queries filter on region but clustered on date — mismatch.\n• Fix: correct clustering key to match filters; pre-sort COPY loads; wait for automatic recluster or CTAS sorted rebuild.\n• Validate: partitions_scanned/partitions_total should drop below 20% for selective queries.',
    cmd: 'SELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_DATE)\');\n\nSELECT query_id, partitions_scanned, partitions_total, query_text\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE query_text ILIKE \'%orders%\'\nORDER BY start_time DESC LIMIT 5;\n\nALTER TABLE orders CLUSTER BY (order_date, region);',
  },
  {
    title: 'Task Chain Not Executing',
    difficulty: 'medium',
    q: 'Your root task shows SUCCEEDED but downstream child tasks never ran overnight. How do you debug?',
    a: 'Task DAG failures involve resume state, dependency graph, and conditional triggers.\n• SHOW TASKS: verify child tasks state = started (resumed), not suspended.\n• TASK_HISTORY for root and children: check state, error_message, scheduled_time gaps.\n• Resume order issue: children must be resumed bottom-up after creation.\n• Child may have WHEN SYSTEM$STREAM_HAS_DATA false despite parent success.\n• Graph version mismatch after DDL change — re-resume all tasks in DAG.\n• Warehouse suspended on child task prevents execution.\n\nFix: ALTER TASK child RESUME; verify predecessor name in AFTER clause matches parent exactly.',
    cmd: 'SHOW TASKS IN SCHEMA etl;\n\nSELECT name, state, scheduled_time, completed_time, error_message\nFROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(\n  SCHEDULED_TIME_RANGE_START => DATEADD(day, -1, CURRENT_TIMESTAMP())\n))\nORDER BY scheduled_time DESC;\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => \'ROOT_ETL\'));\n\nALTER TASK child_transform RESUME;',
  },
  {
    title: 'Stream Stale Offset',
    difficulty: 'medium',
    q: 'A CDC stream is marked stale and the pipeline missed changes for 48 hours. What is your recovery plan?',
    a: 'Stale stream is a pipeline outage requiring full recovery assessment.\n• Confirm: SHOW STREAMS — stale=true; compare stale_after with task failure timeline.\n• Root cause: task failed longer than source table DATA_RETENTION_TIME_IN_DAYS.\n• Assess downstream: how many changes missed; target table may be inconsistent.\n• Recovery: extend retention temporarily; full table resync via MERGE from source or CLONE+SWAP.\n• Recreate stream: CREATE OR REPLACE STREAM ... SHOW_INITIAL_ROWS=TRUE for baseline.\n• Resume task; validate row counts and checksums against source.\n\nPrevent: alert on task failure within 1 hour; retention >= 2x max expected outage.',
    cmd: 'SHOW STREAMS LIKE \'orders_stream\';\n\nALTER TABLE source_orders SET DATA_RETENTION_TIME_IN_DAYS = 14;\n\nCREATE OR REPLACE STREAM orders_stream ON TABLE source_orders SHOW_INITIAL_ROWS = TRUE;\n\nMERGE INTO target_orders t USING source_orders s ON t.id = s.id\nWHEN MATCHED THEN UPDATE SET t.* = s.* WHEN NOT MATCHED THEN INSERT ...;\n\nALTER TASK cdc_merge RESUME;',
  },
  {
    title: 'Dynamic Table Refresh Lag',
    difficulty: 'medium',
    q: 'A dynamic table TARGET_LAG is 15 minutes but actual lag reached 2 hours. How do you troubleshoot?',
    a: 'Dynamic table lag exceeding TARGET_LAG indicates refresh failures or resource constraints.\n• DYNAMIC_TABLE_REFRESH_HISTORY: failed refreshes, error_message, duration trends.\n• scheduling_state SUSPENDED or warehouse suspended blocks refresh.\n• Upstream base table heavy DML forces expensive incremental/full refresh.\n• Warehouse too small: refresh query spilling or timing out.\n• Dependency chain: upstream DT lag cascades to downstream.\n• Mitigate: upsize warehouse, fix SQL error, suspend non-critical DTs, manual ALTER DYNAMIC TABLE REFRESH.\n\nSLA restore: prioritize critical DT; communicate staleness to BI consumers.',
    cmd: 'SELECT name, target_lag, scheduling_state, last_refresh\nFROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLES())\nWHERE name = \'DT_DAILY_KPIS\';\n\nSELECT state, error_message, refresh_start_time, refresh_end_time\nFROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY())\nWHERE name = \'DT_DAILY_KPIS\'\nORDER BY refresh_start_time DESC LIMIT 10;\n\nALTER DYNAMIC TABLE dt_daily_kpis SET WAREHOUSE = transform_wh_large;\nALTER DYNAMIC TABLE dt_daily_kpis REFRESH;',
  },
  {
    title: 'Time Travel Query Too Slow',
    difficulty: 'medium',
    q: 'Forensic queries using AT(TIMESTAMP) on a 5TB table timeout. How do you retrieve historical data efficiently?',
    a: 'Time Travel queries scan historical micro-partitions—same pruning rules apply but more versions exist.\n• Narrow time window: AT(TIMESTAMP) closest to needed moment vs wide range scan.\n• Add selective filters on clustered columns even with AT clause.\n• CREATE TABLE forensic_sample CLONE source AT(TIMESTAMP => ...) — then query clone with limits.\n• Use BEFORE(STATEMENT => query_id) for precise point before known bad MERGE.\n• Temporarily upsize warehouse for forensic window; set STATEMENT_TIMEOUT higher.\n• For repeated forensics: export daily snapshots via task to history tables.\n\nAvoid SELECT * AT on 5TB; sample with LIMIT or aggregate checksums first.',
    cmd: 'CREATE TABLE orders_forensic CLONE orders\n  AT(TIMESTAMP => \'2024-06-15 10:00:00\'::TIMESTAMP_LTZ);\n\nSELECT COUNT(*), SUM(amount) FROM orders_forensic\nWHERE order_date >= \'2024-06-01\';\n\nALTER WAREHOUSE forensic_wh SET WAREHOUSE_SIZE = \'X-LARGE\';\n\nSELECT * FROM orders AT(OFFSET => -7200) WHERE order_id = 12345;',
  },
  {
    title: 'Fail Safe Recovery Request',
    difficulty: 'medium',
    q: 'A critical table was dropped 10 days ago; Time Travel expired. What are your options?',
    a: 'Post-Time Travel recovery enters Fail-safe and external backup territory.\n• Calculate: drop date + retention + 7-day Fail-safe window — are we still inside Fail-safe?\n• If yes: immediately open Snowflake Sev-1 support ticket with account, table FQN, exact drop timestamp from ACCOUNT_USAGE.TABLES deleted column.\n• Parallel: initiate rebuild from external backup (EXPORT stage, replication replica, data lake).\n• If Fail-safe expired: support cannot recover; full rebuild only path.\n• Communicate to business: RPO breach; estimated rebuild timeline.\n• Post-incident: increase retention, restrict DROP privileges, implement external backup task.\n\nNever delay support ticket while attempting rebuild—run both tracks.',
    cmd: 'SELECT table_catalog, table_schema, table_name, deleted, retention_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLES\nWHERE table_name = \'CRITICAL_LEDGER\';\n\nCOPY INTO critical_ledger FROM @backup_stage/ledger/\nFILE_FORMAT = (TYPE = PARQUET);\n\n-- Open Snowflake support case with metadata above',
  },
  {
    title: 'Zero Copy Clone Permission Issue',
    difficulty: 'medium',
    q: 'Developers cannot refresh dev environment via CLONE prod. Error says not authorized. How do you resolve?',
    a: 'Clone authorization requires explicit grants on source and target creation privileges.\n• Required: USAGE on source database/schemas; CREATE DATABASE on account for CLONE prod.\n• Pattern: dedicated dev_clone_svc role with minimal prod read + CREATE DATABASE.\n• Masking: after clone, apply masking policies — clone copies raw data.\n• If policy blocks: check database roles, future grants, managed access schemas.\n• Terraform service account executes clone task weekly with EXECUTE AS OWNER.\n• Audit: QUERY_HISTORY for failed CLONE attempts and grant changes.\n\nSelf-service portal: developers request refresh ticket triggering automated clone task.',
    cmd: 'SHOW GRANTS TO ROLE dev_clone_svc;\n\nGRANT USAGE ON DATABASE prod TO ROLE dev_clone_svc;\nGRANT CREATE DATABASE ON ACCOUNT TO ROLE dev_clone_svc;\n\nCREATE OR REPLACE DATABASE dev CLONE prod;\n\nSELECT query_text, error_message, user_name\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_text ILIKE \'%CLONE%\' AND error_message IS NOT NULL\nORDER BY start_time DESC LIMIT 5;',
  },
  {
    title: 'RBAC Role Hierarchy Conflict',
    difficulty: 'medium',
    q: 'A user has conflicting privileges from multiple roles causing unexpected WRITE access. How do you untangle this?',
    a: 'Privilege conflicts arise from role inheritance and secondary roles enabling unintended access.\n• SELECT CURRENT_ROLE(), CURRENT_SECONDARY_ROLES(); check if SECONDARY ROLES ALL enabled.\n• SHOW GRANTS TO USER; SHOW GRANTS OF ROLE for each granted role tracing inheritance.\n• Identify conflicting WRITE grant from inherited role vs intended READ-only role.\n• Fix: REVOKE excessive grant; restructure hierarchy so READ and WRITE roles separate without overlap.\n• Use SET DEFAULT_SECONDARY_ROLES = () if secondary roles not needed.\n• Managed access schemas prevent discretionary grants compounding confusion.\n\nDocument role matrix; quarterly access certification per user.',
    cmd: 'SHOW GRANTS TO USER jane_doe;\n\nSHOW GRANTS OF ROLE analyst;\n\nSELECT CURRENT_ROLE(), CURRENT_AVAILABLE_ROLES(), CURRENT_SECONDARY_ROLES();\n\nREVOKE INSERT, UPDATE, DELETE ON TABLE prod.sales.orders FROM ROLE analyst;\n\nALTER USER jane_doe SET DEFAULT_SECONDARY_ROLES = ();',
  },
  {
    title: 'Credit Spike Investigation',
    difficulty: 'hard',
    q: 'Monthly credits doubled with no traffic increase reported. Lead a forensic investigation.',
    a: 'Unexplained credit doubling requires comprehensive usage decomposition across all metered services.\n• Compare WAREHOUSE_METERING_HISTORY month-over-month by warehouse and day.\n• QUERY_HISTORY: new heavy queries, bytes_scanned outliers, new users or service accounts.\n• AUTOMATIC_CLUSTERING_HISTORY and PIPE_USAGE_HISTORY for background services.\n• DYNAMIC_TABLE_REFRESH_HISTORY for new DT pipelines.\n• Search optimization and materialized view maintenance costs.\n• Organizational: new team onboarded, clone refresh writing heavily in dev, forgotten Large warehouse.\n• Deliver executive summary with top 3 root causes, credits per cause, remediation owners.\n\nImplement: daily credit anomaly detection alert >20% from 14-day median.',
    cmd: 'SELECT DATE_TRUNC(\'week\', start_time) AS week,\n       SUM(credits_used) AS credits\nFROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY\nWHERE start_time >= DATEADD(month, -3, CURRENT_TIMESTAMP())\nGROUP BY 1 ORDER BY 1;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY\nWHERE start_time >= DATEADD(month, -1, CURRENT_TIMESTAMP())\nORDER BY credits_used DESC LIMIT 20;\n\nSELECT SUM(credits_used) FROM SNOWFLAKE.ACCOUNT_USAGE.PIPE_USAGE_HISTORY\nWHERE start_time >= DATEADD(month, -1, CURRENT_TIMESTAMP());',
  },
  {
    title: 'Micro Partition Skew',
    difficulty: 'hard',
    q: 'One query on a billion-row table has a single task running 10x longer than peers. Diagnose and fix.',
    a: 'Single-task straggler indicates micro-partition skew on join or aggregation key.\n• Query profile: one executor processes disproportionate partition bytes.\n• Skew cause: NULL join key, default value concentration, or monotonic hot key (popular user_id).\n• Check SYSTEM$CLUSTERING_INFORMATION for high overlap on skewed column.\n• Fixes: salt hot key (join on key||salt bucket), pre-filter NULLs, separate hot key processing branch.\n• Recluster on composite key including hash bucket.\n• For MERGE: batch by key range to distribute work.\n\nValidate fix: query profile shows even task duration distribution across workers.',
    cmd: 'SELECT user_id, COUNT(*) FROM events GROUP BY 1 ORDER BY 2 DESC LIMIT 10;\n\nALTER TABLE events CLUSTER BY (HASH_BUCKET, event_date);\n\n-- Salted join pattern:\nSELECT * FROM fact f JOIN dim d\n  ON f.user_id = d.user_id AND f.salt_bucket = d.salt_bucket;\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'EVENTS\', \'(HASH_BUCKET, EVENT_DATE)\');',
  },
  {
    title: 'External Stage Auth Failure',
    difficulty: 'hard',
    q: 'COPY INTO and Snowpipe fail with "Access Denied" on S3 external stage. Walk through resolution.',
    a: 'External stage auth failures trace storage integration IAM trust chain.\n• DESC INTEGRATION: note STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID for IAM role trust.\n• AWS IAM role trust policy must allow Snowflake IAM user with external ID condition.\n• Role policy: s3:GetObject, s3:ListBucket on ALLOWED_LOCATIONS prefix only.\n• Recent AWS change: role policy modified, external ID rotated, integration DISABLED.\n• DESC STAGE: verify STORAGE_INTEGRATION referenced, URL matches ALLOWED_LOCATIONS.\n• Test: LIST @stage; small COPY with VALIDATION_MODE.\n\nDocument working IAM policy template in runbook; Terraform both integration and AWS role.',
    cmd: 'DESC INTEGRATION s3_prod_int;\n\nDESC STAGE landing_stage;\n\nLIST @landing_stage;\n\nCOPY INTO test_load FROM @landing_stage/sample.parquet\nFILE_FORMAT = (TYPE = PARQUET) VALIDATION_MODE = \'RETURN_ERRORS\';\n\nALTER STORAGE INTEGRATION s3_prod_int SET ENABLED = TRUE;',
  },
  {
    title: 'Materialized View Staleness',
    difficulty: 'hard',
    q: 'Dashboards using a materialized view show data 6 hours behind despite active base table loads. Fix it.',
    a: 'Materialized view staleness occurs when refresh lags behind base table change rate.\n• SHOW MATERIALIZED VIEWS: check refresh mode, last refresh time.\n• MATERIALIZED_VIEW_REFRESH_HISTORY: failures, duration, suspended state.\n• High DML on base table overwhelms incremental refresh—consider Dynamic Table with TARGET_LAG.\n• Manual: ALTER MATERIALIZED VIEW ... REFRESH; verify query rewrite routes to MV.\n• Base table structural change may break MV requiring recreate.\n• Warehouse for refresh suspended or too small.\n\nLong-term: migrate to Dynamic Table if MV limitations hit; schedule off-peak full refresh if needed.',
    cmd: 'SHOW MATERIALIZED VIEWS LIKE \'MV_DAILY_SALES\';\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.MATERIALIZED_VIEW_REFRESH_HISTORY())\nWHERE name = \'MV_DAILY_SALES\'\nORDER BY refresh_start_time DESC LIMIT 10;\n\nALTER MATERIALIZED VIEW mv_daily_sales REFRESH;\n\nSELECT * FROM mv_daily_sales LIMIT 5;',
  },
  {
    title: 'Cross-Region Replication Lag',
    difficulty: 'hard',
    q: 'DR replica is 8 hours behind primary. Business requires RPO under 1 hour. What do you do?',
    a: 'Replication lag beyond RPO is a DR program failure requiring immediate escalation.\n• DATABASE_REPLICATION_USAGE_HISTORY: refresh lag trend, failures, bytes transferred.\n• Root causes: primary heavy DML outpacing refresh schedule, refresh task failure, network throttling.\n• Immediate: manual ALTER DATABASE replica REFRESH; increase refresh frequency via task.\n• Primary: reduce bulk DML batch size; schedule large loads after replication window.\n• Consider account-level replication vs per-database if many databases lag.\n• If chronic: resize replication service or split hot tables to dedicated replication group.\n\nReport RPO breach to risk committee; DR drill failure until lag consistently <1h for 30 days.',
    cmd: 'SHOW REPLICATION DATABASES;\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.DATABASE_REPLICATION_USAGE_HISTORY(\n  DATE_RANGE_START => DATEADD(day, -7, CURRENT_TIMESTAMP())\n));\n\nALTER DATABASE prod_replica REFRESH;\n\nCREATE TASK replicate_refresh\n  WAREHOUSE = admin_wh\n  SCHEDULE = \'USING CRON 0 * * * * UTC\'\n  AS ALTER DATABASE prod_replica REFRESH;',
  },
  {
    title: 'Account Usage Query Timeout',
    difficulty: 'hard',
    q: 'Your monitoring queries against ACCOUNT_USAGE.QUERY_HISTORY timeout after 120 seconds. Optimize them.',
    a: 'ACCOUNT_USAGE views are large; naive scans timeout without proper filtering and warehousing.\n• Use dedicated monitoring warehouse size Large+ for ACCOUNT_USAGE queries.\n• Always filter start_time range—never full table scan without date predicate.\n• Select only needed columns; avoid SELECT * on QUERY_HISTORY.\n• Use QUERY_HISTORY BY SESSION (INFORMATION_SCHEMA) for recent session queries instead.\n• Materialize daily aggregates via task into internal monitoring tables for dashboards.\n• Consider SNOWFLAKE database INFORMATION_SCHEMA alternatives for real-time small scope.\n\nPattern: CREATE TABLE monitoring.daily_query_stats AS daily rollup task; dashboards query rollup.',
    cmd: 'ALTER WAREHOUSE monitoring_wh SET WAREHOUSE_SIZE = \'LARGE\';\n\nSELECT warehouse_name, COUNT(*) AS query_count,\n       AVG(total_elapsed_time) AS avg_ms\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE start_time >= DATEADD(day, -1, CURRENT_TIMESTAMP())\n  AND execution_status = \'SUCCESS\'\nGROUP BY 1;\n\nCREATE TABLE monitoring.daily_stats AS\nSELECT DATE_TRUNC(\'day\', start_time) AS day,\n       warehouse_name, SUM(credits_used_cloud_services + credits_used_compute_storage) AS credits\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())\nGROUP BY 1, 2;',
  },
];
