/** Topics 8-12 for snowflake content */
export function item(q, a, cmd) { return { q, a, cmd }; }

export const PART3 = {
  'security': {
    easy: [
      item('What are the main security layers in Snowflake?', 'Snowflake security is defense-in-depth across network, identity, access, and encryption.\n• Network policies restrict IP ranges allowed to connect to the account.\n• Authentication via password, SSO/SAML, OAuth, key pair for service accounts.\n• Authorization via RBAC roles granting privileges on securable objects.\n• Encryption at rest (AES-256) and in transit (TLS); optional Tri-Secret Secure for customer keys.\n• Audit via LOGIN_HISTORY, QUERY_HISTORY, and ACCESS_HISTORY in ACCOUNT_USAGE.\n\nInterview framing: Snowflake is shared responsibility—customer manages RBAC and network; platform manages infrastructure.', 'SHOW PARAMETERS LIKE \'REQUIRE_STORAGE_INTEGRATION_FOR_STAGE_CREATION\' IN ACCOUNT;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY\nORDER BY EVENT_TIMESTAMP DESC LIMIT 10;'),
      item('How does Snowflake encrypt data at rest and in transit?', 'Encryption is enabled by default with no customer configuration required for standard deployments.\n• In transit: all client connections use TLS 1.2+.\n• At rest: all micro-partitions encrypted with AES-256; keys managed by Snowflake key hierarchy.\n• Internal stage and table storage use same encryption model on cloud object storage.\n• Tri-Secret Secure / CMK: customer holds master key in cloud KMS for regulatory control.\n• End-to-end encryption for external stages via encrypted files before upload optional.\n\nCompliance answers reference SOC 2, HIPAA eligibility, and regional deployment options.', 'SHOW PARAMETERS LIKE \'CLIENT_ENCRYPTION_KEY_SIZE\' IN ACCOUNT;\n\nALTER ACCOUNT SET REQUIRE_STORAGE_INTEGRATION_FOR_STAGE_CREATION = TRUE;'),
      item('What is multi-factor authentication and how is it enforced in Snowflake?', 'MFA adds a second verification factor beyond password for human users.\n• Supported: Duo push, TOTP authenticator apps, WebAuthn/FIDO2 hardware keys.\n• ACCOUNTADMIN can set MFA_REQUIRED policy for roles or account-wide.\n• Service accounts should use key-pair auth instead of password+MFA.\n• SSO via IdP may delegate MFA to corporate Okta/Azure AD.\n• LOGIN_HISTORY shows FIRST_AUTHENTICATION_FACTOR and SECOND_AUTHENTICATION_FACTOR status.\n\nBest practice: MFA mandatory for all human users with ACCOUNTADMIN or SECURITYADMIN roles.', 'ALTER ACCOUNT SET MFA_REQUIRED = TRUE;\n\nSELECT USER_NAME, EVENT_TYPE, FIRST_AUTHENTICATION_FACTOR,\n       SECOND_AUTHENTICATION_FACTOR\nFROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY\nWHERE EVENT_TIMESTAMP > DATEADD(day, -7, CURRENT_TIMESTAMP());'),
      item('Explain private connectivity options for Snowflake (PrivateLink, Private Service Connect).', 'Private connectivity keeps Snowflake traffic off the public internet.\n• AWS PrivateLink: VPC endpoint to Snowflake service; DNS resolves to private IP.\n• Azure Private Link and GCP Private Service Connect provide equivalent patterns.\n• Benefits: data exfiltration risk reduction, compliance with network segmentation policies.\n• Setup requires cloud admin coordination and Snowflake support/account team for some regions.\n• Client drivers connect via private URL; same SQL interface.\n\nDocument split-tunnel VPN vs PrivateLink for corporate network architecture reviews.', 'SHOW PARAMETERS LIKE \'ENABLE_INTERNAL_STAGES_PRIVATELINK\' IN ACCOUNT;\n\n-- Connection string uses account.privatelink.snowflakecomputing.com\nSELECT SYSTEM$GET_PRIVATELINK_CONFIG();'),
    ],
    medium: [
      item('How do you implement network policies for IP allowlisting?', 'Network policies control which IP addresses can connect to Snowflake users or the entire account.\n• CREATE NETWORK POLICY with ALLOWED_IP_LIST and BLOCKED_IP_LIST.\n• Apply to account: ALTER ACCOUNT SET NETWORK_POLICY = policy_name.\n• Per-user override possible for contractors with different IP ranges.\n• Always include corporate egress IPs and CI/CD runner IPs before enforcing.\n• Lockout risk: test with secondary admin session before applying account-wide policy.\n\nCombine with SSO and short-lived service account keys for defense in depth.', 'CREATE NETWORK POLICY corp_access\n  ALLOWED_IP_LIST = (\'203.0.113.0/24\', \'198.51.100.50\')\n  BLOCKED_IP_LIST = (\'0.0.0.0/0\')\n  COMMENT = \'Corporate VPN and office egress\';\n\nALTER ACCOUNT SET NETWORK_POLICY = corp_access;'),
      item('What is row access policy and when do you use it?', 'Row access policies filter which rows a query returns based on session context.\n• CREATE ROW ACCESS POLICY with predicate using CURRENT_ROLE(), CURRENT_USER(), or session context.\n• Attach to table: ALTER TABLE ... ADD ROW ACCESS POLICY policy ON (column).\n• Use for multi-tenant data in shared tables without separate tables per tenant.\n• Complements column masking for cell-level security.\n• Test thoroughly: policy bugs cause data leaks or empty result sets.\n\nCommon pattern: tenant_id column filtered by SESSION context set at login.', 'CREATE ROW ACCESS POLICY tenant_filter AS (tenant_id VARCHAR) RETURNS BOOLEAN ->\n  tenant_id = CURRENT_SESSION()->>\'tenant_id\' OR IS_ROLE_IN_SESSION(\'ADMIN\');\n\nALTER TABLE shared_data ADD ROW ACCESS POLICY tenant_filter ON (tenant_id);\n\nSELECT * FROM shared_data; -- returns only tenant rows'),
      item('How do column masking policies protect sensitive data?', 'Masking policies dynamically transform column values at query time based on role.\n• CREATE MASKING POLICY with CASE on IS_ROLE_IN_SESSION for different mask levels.\n• Attach: ALTER TABLE ... MODIFY COLUMN ... SET MASKING POLICY policy.\n• Analysts see hashed/masked SSN; privileged roles see plaintext.\n• Masking applies at read time—underlying storage unchanged.\n• Combine with secure views for additional abstraction layer.\n\nRegulatory use: PCI, HIPAA columns masked by default; break-glass role for full access with audit.', 'CREATE MASKING POLICY ssn_mask AS (val VARCHAR) RETURNS VARCHAR ->\n  CASE WHEN IS_ROLE_IN_SESSION(\'PII_READER\') THEN val\n       ELSE \'***-**-\' || RIGHT(val, 4) END;\n\nALTER TABLE customers MODIFY COLUMN ssn SET MASKING POLICY ssn_mask;\n\nSELECT ssn FROM customers;'),
      item('How do you audit user activity and detect anomalous access patterns?', 'Security monitoring leverages ACCOUNT_USAGE views and SIEM integration.\n• LOGIN_HISTORY: failed logins, new IP addresses, MFA bypass attempts.\n• QUERY_HISTORY: bulk SELECT on sensitive tables by unusual roles.\n• ACCESS_HISTORY: object access patterns over time.\n• Alert: first-time access to PII tables, queries outside business hours, large result downloads.\n• Ship logs to Splunk/Datadog via Snowflake Data Sharing or external stage export.\n\nRun monthly access review: users with ACCOUNTADMIN, stale users not logged in 90 days.', 'SELECT user_name, client_ip, reported_client_type, event_type\nFROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY\nWHERE event_type = \'LOGIN\'\n  AND event_timestamp > DATEADD(day, -1, CURRENT_TIMESTAMP());\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY\nWHERE object_name = \'CUSTOMERS\'\nORDER BY query_start_time DESC LIMIT 20;'),
    ],
    hard: [
      item('Design a zero-trust security model for Snowflake in a regulated financial institution.', 'Zero-trust in Snowflake eliminates implicit trust based on network location alone.\n• PrivateLink only—no public endpoint; network policy deny-by-default.\n• SSO with step-up MFA for privileged roles; no shared service passwords.\n• RBAC least privilege: functional roles, no direct grants to users, quarterly access reviews.\n• Row/column policies on all PII tables; secure views as only consumer interface.\n• Immutable audit logs exported to WORM storage; alerting on policy DDL changes.\n• Separation of duties: SECURITYADMIN cannot read data; DATA_ADMIN cannot change network policy.\n\nMap controls to SOC2/CCAR requirements with evidence collection automation.', 'CREATE NETWORK POLICY zero_trust ALLOWED_IP_LIST = (\'10.0.0.0/8\');\nALTER ACCOUNT SET NETWORK_POLICY = zero_trust;\n\nCREATE ROW ACCESS POLICY region_policy AS (region VARCHAR) RETURNS BOOLEAN ->\n  region = CURRENT_SESSION()->>\'authorized_region\';\n\nGRANT ROLE data_reader TO USER analyst WITHOUT ADMIN OPTION;'),
      item('Lead incident response for suspected credential compromise of a service account.', 'Service account compromise requires immediate containment and forensic analysis.\n• Detect: anomalous queries from service account IP, unusual data volume export, login from new geography.\n• Contain: ALTER USER ... SET DISABLED = TRUE; rotate key pair immediately.\n• Revoke and re-grant minimal privileges after scope review.\n• Forensics: QUERY_HISTORY and ACCESS_HISTORY for exfiltration scope; preserve query_ids.\n• Eradicate: new RSA key pair, update secrets manager, invalidate old public key on user.\n• Prevent: key rotation policy 90 days, network policy on service user, query tag monitoring.\n\nRegulatory notification if PII accessed—document timeline within 72 hours.', 'ALTER USER etl_svc SET RSA_PUBLIC_KEY = \'MIIBIjAN...\';\n\nALTER USER etl_svc SET DISABLED = TRUE;\n\nSELECT query_text, bytes_scanned, start_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE user_name = \'ETL_SVC\'\n  AND start_time > DATEADD(day, -3, CURRENT_TIMESTAMP())\nORDER BY bytes_scanned DESC;'),
      item('How do you implement data classification and tag-based access policies at scale?', 'Classification tags drive automated policy application across thousands of objects.\n• Tag objects: ALTER TABLE ... SET TAG data_classification = \'PII\'.\n• Tag-based masking: masking policy references SYSTEM$GET_TAG on column.\n• OBJECT_DEPENDENCIES and TAG_REFERENCES audit tag propagation.\n• Terraform/Snowflake provider applies tags consistently in IaC.\n• Governance workflow: data steward tags at creation; policy auto-attaches via stored procedure.\n\nScale challenge: retroactive tagging sprint on legacy tables before policy enforcement date.', 'CREATE TAG data_classification ALLOWED_VALUES \'PUBLIC\', \'INTERNAL\', \'PII\', \'RESTRICTED\';\n\nALTER TABLE customers SET TAG data_classification = \'PII\';\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES\nWHERE tag_name = \'DATA_CLASSIFICATION\';'),
      item('Compare security implications of external functions vs native SQL for data processing.', 'External functions call external APIs (Lambda, Azure Functions) with security trade-offs.\n• Data leaves Snowflake boundary to external endpoint—network and compliance review required.\n• API integration uses secrets in API integration object—not embedded in function DDL.\n• Latency and availability depend on external service SLA.\n• Native SQL UDFs/Java UDFs keep data in Snowflake trust boundary.\n• Use external functions only when capability unavailable natively (ML API, geocoding).\n\nDocument data flow diagram for security review board approval.', 'CREATE API INTEGRATION ext_api\n  API_PROVIDER = aws_api_gateway\n  API_AWS_ROLE_ARN = \'arn:aws:iam::123:role/snowflake_api\'\n  ENABLED = TRUE;\n\nCREATE EXTERNAL FUNCTION geocode(v VARCHAR)\n  RETURNS VARIANT\n  API_INTEGRATION = ext_api\n  AS \'https://api.example.com/geocode\';'),
    ],
  },

  'rbac': {
    easy: [
      item('Explain Snowflake\'s role-based access control model.', 'Snowflake RBAC grants privileges to roles, which are assigned to users.\n• Securables: databases, schemas, tables, warehouses, integrations, etc.\n• Privileges: SELECT, INSERT, CREATE TABLE, USAGE, OWNERSHIP, etc.\n• Users activate roles per session: USE ROLE role_name; one primary role default.\n• Roles can inherit from other roles via GRANT ROLE child TO ROLE parent.\n• ACCOUNTADMIN is top-level—minimize direct assignment to humans.\n\nPrinciple of least privilege: grant minimum needed privilege on specific objects.', 'SHOW ROLES;\nSHOW GRANTS TO ROLE analyst;\nSHOW GRANTS TO USER jane_doe;\n\nUSE ROLE analyst;\nSELECT CURRENT_ROLE(), CURRENT_AVAILABLE_ROLES();'),
      item('What is the difference between USAGE and SELECT privileges?', 'Different privilege types govern different capabilities on different object types.\n• USAGE on database/schema: allows referencing objects inside—required before table access.\n• SELECT on table/view: allows reading rows (subject to row access policies).\n• USAGE on warehouse: allows running queries on that compute resource.\n• CREATE TABLE on schema: allows DDL for new tables in schema.\n• Missing USAGE on database causes "does not exist or not authorized" even with SELECT on table.\n\nGrant order: USAGE on DB → USAGE on SCHEMA → SELECT on TABLE.', 'GRANT USAGE ON DATABASE prod TO ROLE analyst;\nGRANT USAGE ON SCHEMA prod.sales TO ROLE analyst;\nGRANT SELECT ON TABLE prod.sales.orders TO ROLE analyst;\n\nSHOW GRANTS TO ROLE analyst;'),
      item('How do you grant a role to a user?', 'Role assignment connects users to privilege bundles.\n• GRANT ROLE role_name TO USER user_name.\n• User\'s DEFAULT_ROLE set on login if multiple roles granted.\n• SECONDARY ROLES: ALL enables all granted roles simultaneously in session.\n• ADMIN OPTION on grant allows user to re-grant role to others—use sparingly.\n• REVOKE ROLE removes access without deleting user.\n\nOnboarding checklist: grant role, set default warehouse, verify with SHOW GRANTS.', 'GRANT ROLE data_analyst TO USER jane_doe;\nALTER USER jane_doe SET DEFAULT_ROLE = data_analyst DEFAULT_WAREHOUSE = bi_wh;\n\nGRANT ROLE etl_developer TO ROLE data_engineer;'),
      item('What are system-defined roles in Snowflake?', 'Snowflake provides built-in roles with predefined capabilities.\n• ACCOUNTADMIN: full account control—users, roles, billing, all objects.\n• SECURITYADMIN: manage users, roles, grants—cannot read arbitrary data.\n• USERADMIN: create users and roles—cannot grant on data objects.\n• SYSADMIN: create warehouses and databases—typical for data platform team.\n• PUBLIC: automatically granted to all users—revoke dangerous default grants.\n\nCustom functional roles (ANALYST, ETL_ROLE) should hold actual data access—not ACCOUNTADMIN.', 'SHOW ROLES LIKE \'%ADMIN%\';\n\nREVOKE CREATE DATABASE ON ACCOUNT FROM ROLE PUBLIC;\n\nGRANT ROLE sysadmin TO ROLE custom_platform_admin;'),
    ],
    medium: [
      item('How do you design a role hierarchy for a data platform team?', 'Role hierarchy mirrors organizational functions with inheritance reducing grant sprawl.\n• Base roles: RAW_READER, RAW_LOADER, CURATED_READER, CURATED_WRITER per medallion layer.\n• Functional roles: DATA_ENGINEER inherits RAW_LOADER + CURATED_WRITER; ANALYST inherits CURATED_READER.\n• Environment roles: DEV_ENGINEER vs PROD_ENGINEER—prod write restricted.\n• Warehouse USAGE granted at functional role level.\n• Avoid role explosion: max 2–3 inheritance levels; document in data governance wiki.\n\nReview quarterly: SHOW GRANTS OF ROLE to find unused inherited privileges.', 'CREATE ROLE curated_reader;\nGRANT USAGE ON DATABASE prod TO ROLE curated_reader;\nGRANT USAGE ON SCHEMA prod.gold TO ROLE curated_reader;\nGRANT SELECT ON ALL TABLES IN SCHEMA prod.gold TO ROLE curated_reader;\nGRANT SELECT ON FUTURE TABLES IN SCHEMA prod.gold TO ROLE curated_reader;\n\nGRANT ROLE curated_reader TO ROLE bi_analyst;'),
      item('What are future grants and why are they important?', 'Future grants apply privileges to objects created after the grant statement.\n• GRANT SELECT ON FUTURE TABLES IN SCHEMA prod.gold TO ROLE analyst.\n• Without future grants, new tables invisible to role until manual GRANT.\n• FUTURE grants exist for tables, views, stages, functions, etc.\n• OWNERSHIP transfer may reset grant behavior—verify after ownership changes.\n• Managed access schemas centralize future grant management.\n\nETL automation creates tables nightly—future grants prevent daily access tickets.', 'GRANT SELECT ON FUTURE TABLES IN SCHEMA prod.silver TO ROLE analyst;\nGRANT SELECT ON FUTURE VIEWS IN SCHEMA prod.gold TO ROLE bi_tool;\n\nSHOW FUTURE GRANTS TO ROLE analyst;'),
      item('How do you troubleshoot "Insufficient privileges" errors?', 'Privilege errors require tracing grant chain from user to object.\n• Confirm active role: SELECT CURRENT_ROLE(); user may need USE ROLE.\n• SHOW GRANTS TO ROLE current_role for object privilege.\n• Check parent role inheritance: SHOW GRANTS OF ROLE child_role.\n• USAGE required on database and schema before table SELECT.\n• Row access policy may filter all rows—looks like empty table not privilege error.\n• USE SECONDARY ROLES ALL if privilege spread across roles.\n\nSimulate: USE ROLE target_role as SECURITYADMIN to reproduce issue.', 'USE ROLE analyst;\nSELECT CURRENT_ROLE(), CURRENT_AVAILABLE_ROLES();\n\nSHOW GRANTS TO ROLE analyst;\nSHOW GRANTS ON TABLE prod.sales.orders;\n\nSHOW GRANTS TO USER jane_doe;'),
      item('Explain OWNERSHIP privilege and transfer implications.', 'OWNERSHIP is the highest privilege on an object—implies all other privileges.\n• Object creator typically becomes owner automatically.\n• GRANT OWNERSHIP TO ROLE x COPY CURRENT GRANTS transfers control preserving grants.\n• GRANT OWNERSHIP ... REVOKE CURRENT GRANTS removes existing grants on transfer.\n• Only owner (or ACCOUNTADMIN) can DROP or ALTER object.\n• Centralized ownership model: platform role owns all prod objects; creators use service role.\n\nTerraform manages ownership to prevent individual users owning production tables.', 'GRANT OWNERSHIP ON TABLE prod.sales.orders TO ROLE schema_admin COPY CURRENT GRANTS;\n\nSHOW GRANTS ON TABLE prod.sales.orders;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES\nWHERE name = \'ORDERS\' AND granted_on = \'TABLE\';'),
    ],
    hard: [
      item('Design RBAC for a Snowflake account with 500 users and SOX compliance requirements.', 'SOX-compliant RBAC enforces segregation of duties and auditable access changes.\n• No direct data access for users with deployment privileges.\n• CHANGE_MANAGEMENT role can deploy tasks/procedures but not SELECT prod financial tables.\n• FINANCE_READER read-only on gold finance schema; no WRITE anywhere.\n• All grants via Terraform PR with approval; no manual ACCOUNTADMIN in prod.\n• Quarterly access certification: managers attest SHOW GRANTS TO USER reports.\n• Break-glass ACCOUNTADMIN: named individuals, MFA, session logged to SIEM.\n\nEvidence package: grant change tickets, LOGIN_HISTORY, ACCESS_HISTORY for auditors.', 'CREATE ROLE finance_reader;\nGRANT USAGE ON DATABASE prod TO ROLE finance_reader;\nGRANT USAGE ON SCHEMA prod.finance TO ROLE finance_reader;\nGRANT SELECT ON ALL TABLES IN SCHEMA prod.finance TO ROLE finance_reader;\n\nREVOKE ROLE sysadmin FROM USER contractor_1;'),
      item('How would you migrate from user-level grants to role-based model on legacy account?', 'Legacy accounts often have direct grants to users causing governance debt.\n• Inventory: SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS full export.\n• Design target role matrix mapping old grants to functional roles.\n• Create roles, grant privileges, GRANT ROLE to user, verify access.\n• REVOKE direct grants from users once role verified.\n• Communicate change window; risk of brief access gap if misconfigured.\n• Automate drift detection: alert on new direct user grants.\n\nPhased by department: finance week 1, engineering week 2—rollback plan per phase.', 'SELECT grantee_name, privilege, granted_on, name\nFROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS\nORDER BY grantee_name;\n\nREVOKE SELECT ON TABLE prod.sales.orders FROM USER legacy_user;\nGRANT ROLE sales_analyst TO USER legacy_user;'),
      item('Lead incident where PUBLIC role had unintended CREATE INTEGRATION privilege.', 'Over-privileged PUBLIC role is a critical security vulnerability affecting all users.\n• Detect: security scan or auditor finding SHOW GRANTS TO ROLE PUBLIC.\n• Impact: any user could create external stages pointing to attacker buckets—data exfil risk.\n• Fix: REVOKE dangerous privileges from PUBLIC immediately.\n• Audit: ACCESS_HISTORY and QUERY_HISTORY for unauthorized integration/stage creation.\n• Root cause: bootstrap script granted overly broad privileges.\n• Prevent: CIS benchmark alignment, grant hardening in Terraform, deny-list monitor on PUBLIC grants.\n\nExecutive briefing: no evidence of exploitation vs confirmed exfiltration scope.', 'SHOW GRANTS TO ROLE PUBLIC;\n\nREVOKE CREATE INTEGRATION ON ACCOUNT FROM ROLE PUBLIC;\nREVOKE CREATE STAGE ON ACCOUNT FROM ROLE PUBLIC;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.INTEGRATIONS\nWHERE created_on > DATEADD(day, -90, CURRENT_TIMESTAMP());'),
      item('Explain differences between RBAC and Discretionary Access Control in Snowflake context.', 'Snowflake primarily uses RBAC but object owners have discretionary grant ability.\n• RBAC: central role grants managed by SECURITYADMIN/platform team.\n• DAC element: object owner can GRANT privileges on owned objects unless managed access schema.\n• Managed access schemas disable owner discretionary grants—owner approves via centralized model.\n• Enterprise standard: managed access on prod gold; discretionary allowed on dev sandboxes.\n• Conflict resolution: OWNERSHIP transfer to service role eliminates individual discretion in prod.\n\nArchitecture decision record should specify which schemas use managed access.', 'CREATE SCHEMA prod.gold WITH MANAGED ACCESS;\nALTER SCHEMA prod.gold ENABLE MANAGED ACCESS;\n\n-- Owner cannot independently GRANT SELECT to new user\nSHOW MANAGED ACCESS SCHEMAS;'),
    ],
  },

  'streams': {
    easy: [
      item('What is a Snowflake stream and what problem does it solve?', 'A stream is a change tracking object that records DML changes on a table.\n• Stream captures INSERT, UPDATE, DELETE metadata as rows in the stream object.\n• Enables incremental processing: consume only changed rows since last consumption.\n• Used with tasks for CDC pipelines without external tools like Debezium.\n• Stream data is not separate storage—it is metadata pointer to changed rows in base table.\n• Must be consumed (queried with DML or INSERT) to advance stream offset.\n\nPattern: stream on source table → task MERGEs changes into target.', 'CREATE STREAM orders_stream ON TABLE orders;\n\nSELECT * FROM orders_stream;\n\nSHOW STREAMS IN SCHEMA sales;'),
      item('Explain INSERT-only vs standard (default) stream types.', 'Stream type determines which DML operations are tracked.\n• Standard stream (default): tracks INSERT, UPDATE, DELETE with METADATA$ACTION column.\n• INSERT-only stream: tracks only new rows—lighter weight for append-only sources.\n• APPEND_ONLY table stream option for tables that never update/delete.\n• Choose INSERT-only when source is immutable event log.\n• Standard required when MERGE updates/deletes must propagate to downstream.\n\nWrong stream type causes missed deletes in slowly-changing dimension pipelines.', 'CREATE STREAM events_insert_only ON TABLE events APPEND_ONLY = TRUE;\n\nCREATE STREAM customers_std ON TABLE customers;\n\nSELECT METADATA$ACTION, METADATA$ISUPDATE, * FROM customers_std;'),
      item('What are METADATA$ columns in a stream query result?', 'Streams expose system metadata columns describing each change row.\n• METADATA$ACTION: INSERT, DELETE, or combined for UPDATE (appears as DELETE+INSERT pair).\n• METADATA$ISUPDATE: TRUE when row is update-delete half of update pair.\n• METADATA$ROW_ID: unique row identifier within stream result.\n• Use METADATA$ACTION in MERGE logic to route inserts vs deletes.\n• Consumer query should handle UPDATE as delete old + insert new pattern.\n\nTask MERGE templates filter WHERE METADATA$ACTION = \'INSERT\' for append-only consumption.', 'SELECT METADATA$ACTION, METADATA$ISUPDATE, order_id, status\nFROM orders_stream\nWHERE METADATA$ACTION IN (\'INSERT\', \'DELETE\');'),
      item('How do you create a stream on a table?', 'Stream creation is lightweight metadata DDL on existing or new tables.\n• CREATE STREAM stream_name ON TABLE table_name.\n• Optional SHOW_INITIAL_ROWS = TRUE includes existing rows at stream creation (one-time snapshot).\n• Stream must be in same database/schema context or fully qualified.\n• Requires SELECT on base table for stream owner role.\n• Stream does not work on external tables—only Snowflake-managed tables.\n\nAfter CREATE, first SELECT shows changes since stream creation (or all rows if SHOW_INITIAL_ROWS).', 'CREATE OR REPLACE STREAM sales.orders_stream ON TABLE sales.orders;\n\nINSERT INTO sales.orders VALUES (1001, \'2024-06-15\', 250.00);\n\nSELECT * FROM sales.orders_stream;'),
    ],
    medium: [
      item('How do streams advance offset and what happens if a stream is not consumed?', 'Stream offset tracks consumption point on the change log.\n• Querying stream alone does not advance offset—DML using stream results does (INSERT INTO target SELECT FROM stream).\n• Unconsumed streams accumulate changes; very long delay increases Time Travel dependency on base table.\n• Stream becomes stale if base table Time Travel retention exceeded before consumption—data loss risk.\n• SHOW STREAMS displays stale_after hint based on retention.\n• Monitor stream lag: row count in stream vs consumption task schedule.\n\nAlert if stream row count grows monotonically for 24+ hours.', 'SELECT SYSTEM$STREAM_GET_TABLE_TIMESTAMP(\'orders_stream\');\n\nSHOW STREAMS LIKE \'orders_stream\';\n\nSELECT COUNT(*) FROM orders_stream;'),
      item('How do you build a CDC pipeline with stream and task?', 'Stream + task is the native Snowflake CDC pattern for table-to-table replication.\n• CREATE STREAM on source; CREATE TASK scheduled WHEN SYSTEM$STREAM_HAS_DATA(stream).\n• Task body: MERGE INTO target USING (SELECT * FROM stream) ON key ...\n• Task must RESUME after creation (tasks created suspended by default).\n• Use EXECUTE AS CALLER or OWNER for appropriate privilege context.\n• Warehouse required for task execution—size for MERGE volume.\n\nError handling: ON_ERROR = SKIP_TASK or CONTINUE per task reliability requirements.', 'CREATE TASK process_orders\n  WAREHOUSE = etl_wh\n  SCHEDULE = \'1 MINUTE\'\n  WHEN SYSTEM$STREAM_HAS_DATA(\'orders_stream\')\n  AS MERGE INTO target_orders t\n  USING (SELECT * FROM orders_stream) s ON t.id = s.id\n  WHEN MATCHED THEN UPDATE SET ...\n  WHEN NOT MATCHED THEN INSERT ...;\n\nALTER TASK process_orders RESUME;'),
      item('What causes a stream to become stale and how do you recover?', 'Stale stream means change data is no longer available in Time Travel for unconsumed offset.\n• Cause: task failed for longer than table DATA_RETENTION_TIME_IN_DAYS.\n• SHOW STREAMS shows stale = true and stale_after timestamp.\n• Recovery: full reload from base table or CLONE AT timestamp before staleness.\n• Recreate stream with SHOW_INITIAL_ROWS = TRUE after fixing pipeline.\n• Prevent: extend retention on source, faster task recovery, alerting on task failures.\n\nStale stream is data pipeline incident—downstream may have missed changes.', 'SHOW STREAMS IN SCHEMA sales;\n\nCREATE OR REPLACE STREAM orders_stream ON TABLE orders SHOW_INITIAL_ROWS = TRUE;\n\nALTER TABLE orders SET DATA_RETENTION_TIME_IN_DAYS = 7;'),
      item('Can multiple streams exist on one table and multiple consumers share a stream?', 'Multiple streams on same table support independent consumption pipelines.\n• Each stream maintains independent offset on same base table changes.\n• One stream should not have multiple uncoordinated consumers—race on offset advancement.\n• Pattern: one stream per downstream target (analytics stream, audit stream).\n• Views on streams not supported—query stream directly in task.\n• CLONE table copies data but not streams—recreate streams on clone.\n\nDocument stream ownership: which task consumes which stream.', 'CREATE STREAM stream_for_analytics ON TABLE orders;\nCREATE STREAM stream_for_audit ON TABLE orders;\n\nSHOW STREAMS ON TABLE orders;'),
    ],
    hard: [
      item('Design exactly-once CDC from operational table to analytics warehouse with streams.', 'Exactly-once semantics require idempotent MERGE and transactional task boundaries.\n• Stream captures changes; MERGE keyed on business primary key is idempotent on retry.\n• Task ON_ERROR = SUSPEND prevents silent skip; monitor TASK_HISTORY for failures.\n• Handle UPDATE pairs: MERGE logic uses METADATA$ACTION and METADATA$ISUPDATE correctly.\n• Ordering: process stream in transaction; single task consumer per stream.\n• Validation: reconciliation query comparing source COUNT/SUM to target daily.\n• Dead letter: rows failing validation inserted to quarantine table from stream.\n\nSLA: max 5-minute lag; zero duplicate rows measured by unique key constraint.', 'CREATE TASK cdc_orders\n  WAREHOUSE = etl_wh\n  WHEN SYSTEM$STREAM_HAS_DATA(\'orders_stream\')\n  AS\n    MERGE INTO analytics.orders t\n    USING (\n      SELECT * FROM orders_stream WHERE METADATA$ACTION != \'DELETE\'\n    ) s ON t.order_id = s.order_id\n    WHEN MATCHED THEN UPDATE SET ...\n    WHEN NOT MATCHED THEN INSERT ...;\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())\nORDER BY scheduled_time DESC LIMIT 10;'),
      item('How do streams interact with Time Travel, CLONE, and DROP on base table?', 'Stream lifecycle is tightly coupled to base table existence and retention.\n• DROP TABLE invalidates streams immediately.\n• CLONE TABLE does not copy streams—must recreate manually.\n• Time Travel UNDROP restores table but stream offsets may need validation.\n• TRUNCATE TABLE generates DELETE entries in standard stream.\n• SWAP TABLE: streams remain on respective tables post-swap—verify naming.\n\nBlue-green SWAP: recreate streams pointing to new prod table after cutover.', 'CREATE TABLE orders_new CLONE orders;\nCREATE STREAM orders_new_stream ON TABLE orders_new;\n\nALTER TABLE orders SWAP WITH orders_new;\n\nSHOW STREAMS ON TABLE orders;'),
      item('Lead debugging of duplicate rows in downstream table fed by stream-task pipeline.', 'Duplicate rows indicate MERGE idempotency failure or multiple task executions.\n• Check TASK_HISTORY for overlapping executions or manual task runs during schedule.\n• Verify MERGE ON clause uses unique business key—not date alone.\n• Stream consumed multiple times if transaction rolled back but offset advanced—rare; check task error log.\n• Multiple tasks reading same stream—architectural bug.\n• Fix: dedupe CTAS, add UNIQUE constraint, fix MERGE key, suspend duplicate tasks.\n\nRoot cause analysis: compare duplicate key timestamps to task execution log.', 'SELECT order_id, COUNT(*) FROM target_orders GROUP BY 1 HAVING COUNT(*) > 1;\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => \'PROCESS_ORDERS\'))\nWHERE state = \'SUCCEEDED\'\nORDER BY scheduled_time DESC LIMIT 20;\n\nALTER TASK process_orders SUSPEND;'),
      item('Compare Snowflake streams vs external CDC tools (Debezium, Fivetran) for enterprise CDC.', 'Tool selection depends on source systems, latency, ops capacity, and cost.\n• Streams: native for Snowflake-to-Snowflake; no external infra; limited to Snowflake DML visibility.\n• Debezium: true DB transaction log CDC from Oracle/Postgres; requires Kafka ops.\n• Fivetran: managed connectors; SaaS cost; broad source support.\n• Hybrid: Debezium → Snowpipe → landing; streams for silver-to-gold inside Snowflake.\n• Evaluation: source latency, exactly-once guarantees, schema evolution, TCO over 3 years.\n\nPresent decision matrix for hybrid lakehouse referencing existing Kafka investment.', 'CREATE STREAM bronze_to_silver ON TABLE bronze.events;\n\n-- External CDC lands via:\nCOPY INTO bronze.events FROM @kafka_stage FILE_FORMAT = (TYPE = AVRO);\n\nSELECT COUNT(*) FROM bronze_to_silver;'),
    ],
  },

  'tasks': {
    easy: [
      item('What is a Snowflake task and how is it different from an external scheduler?', 'Tasks are Snowflake-native scheduled SQL execution with dependency support.\n• CREATE TASK with SCHEDULE cron or AFTER dependency on another task.\n• Runs SQL/ CALL procedure on specified warehouse when triggered.\n• No external Airflow/cron server required—metadata in Snowflake cloud services.\n• Tasks created in SUSPENDED state—must ALTER TASK RESUME.\n• Task history in INFORMATION_SCHEMA.TASK_HISTORY.\n\nUse external orchestrator when cross-system dependencies exceed Snowflake-only scope.', 'CREATE TASK daily_load\n  WAREHOUSE = etl_wh\n  SCHEDULE = \'USING CRON 0 6 * * * America/New_York\'\n  AS INSERT INTO summary SELECT * FROM staging;\n\nALTER TASK daily_load RESUME;\n\nSHOW TASKS IN SCHEMA sales;'),
      item('Explain task scheduling with CRON expressions in Snowflake.', 'Snowflake tasks use standard cron syntax with timezone specification.\n• Format: USING CRON minute hour day month day-of-week timezone.\n• Example: 0 6 * * * America/New_York = daily 6 AM Eastern.\n• Minimum interval depends on account—typically 1 minute for serverless tasks.\n• SCHEDULE = NULL with WHEN clause for event-driven (stream has data).\n• TIMESTAMP_INPUT_FORMAT for task parameterization with scheduled time.\n\nUse UTC timezone for global teams to avoid DST confusion, or explicit regional timezone.', 'CREATE TASK hourly_agg\n  WAREHOUSE = etl_wh\n  SCHEDULE = \'USING CRON 0 * * * * UTC\'\n  AS CALL aggregate_hourly();\n\nALTER TASK hourly_agg RESUME;'),
      item('Why are tasks created in SUSPENDED state by default?', 'Suspended-by-default prevents accidental execution before validation.\n• Creator must explicitly RESUME after reviewing SQL, warehouse, and schedule.\n• Allows building task DAG (root + children) before starting execution.\n• CI/CD can deploy tasks suspended; resume in controlled change window.\n• ALTER TASK SUSPEND immediately stops future runs—incident response.\n• SHOW TASKS displays state column: started/suspended.\n\nProduction promotion checklist: resume only after dependency tasks verified.', 'CREATE TASK child_task\n  WAREHOUSE = etl_wh\n  AFTER parent_task\n  AS CALL process_child();\n\nSELECT state FROM TABLE(INFORMATION_SCHEMA.TASKS())\nWHERE name = \'CHILD_TASK\';\n\nALTER TASK child_task RESUME;'),
      item('What warehouse is required for task execution?', 'Tasks require an active warehouse to execute SQL—cloud services only orchestrates.\n• WAREHOUSE parameter mandatory on root scheduled tasks.\n• Child tasks in DAG inherit warehouse from root unless overridden.\n• Serverless tasks (Snowflake-managed warehouse) available for some task types—check account.\n• Warehouse must be RESUMED or AUTO_RESUME enabled—suspended warehouse delays task.\n• Right-size warehouse for task SQL—nightly MERGE may need Large.\n\nCost: task credits appear in WAREHOUSE_METERING_HISTORY under task warehouse.', 'CREATE TASK merge_task\n  WAREHOUSE = etl_wh\n  SCHEDULE = \'USING CRON 30 5 * * * UTC\'\n  AS MERGE INTO prod.t FROM staging.t ...;\n\nSHOW WAREHOUSES LIKE \'etl_wh\';\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())\nORDER BY scheduled_time DESC LIMIT 5;'),
    ],
    medium: [
      item('How do you create a task DAG with dependencies?', 'Task graphs chain execution order without external orchestration.\n• Root task has SCHEDULE; child tasks use AFTER parent_task_name.\n• Only root needs SCHEDULE; children trigger when parent succeeds.\n• Resume order: children first, then parents (bottom-up resume).\n• Suspend order: parents first (top-down suspend) to prevent orphan runs.\n• Deep DAGs supported but complex graphs better in Airflow for visibility.\n\nNaming convention: schema.task_layer_step for clear dependency graph.', 'CREATE TASK root_task WAREHOUSE = etl_wh SCHEDULE = \'USING CRON 0 5 * * * UTC\' AS CALL step1();\nCREATE TASK child_a AFTER root_task AS CALL step2a();\nCREATE TASK child_b AFTER child_a AS CALL step2b();\n\nALTER TASK child_b RESUME;\nALTER TASK child_a RESUME;\nALTER TASK root_task RESUME;'),
      item('How do you monitor task failures and set up alerting?', 'Task operational health requires TASK_HISTORY monitoring and notifications.\n• INFORMATION_SCHEMA.TASK_HISTORY or ACCOUNT_USAGE.TASK_HISTORY shows state, error_code, error_message.\n• Failed states: FAILED, CANCELLED, TIMED_OUT.\n• Snowflake email notifications on task failure via notification integration.\n• Custom alert: scheduled task queries TASK_HISTORY and sends via external function.\n• ON_ERROR = SUSPEND_TASK stops DAG on failure—prevents downstream corruption.\n\nDashboard: success rate per task last 7 days, p95 duration trend.', 'SELECT name, state, error_message, scheduled_time, completed_time\nFROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(\n  SCHEDULED_TIME_RANGE_START => DATEADD(day, -1, CURRENT_TIMESTAMP())\n))\nWHERE state != \'SUCCEEDED\'\nORDER BY scheduled_time DESC;\n\nALTER TASK merge_task SET USER_TASK_TIMEOUT_MS = 3600000;'),
      item('What is USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE for serverless tasks?', 'Serverless tasks use Snowflake-managed compute without specifying customer warehouse.\n• Snowflake provisions and scales compute automatically for the task.\n• Billed separately—compare cost vs dedicated warehouse for predictable workloads.\n• USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE sets starting size for managed tasks.\n• Good for sporadic light tasks; heavy MERGE may be cheaper on dedicated warehouse.\n• Not all accounts/regions support all serverless task features.\n\nBenchmark: run task 30 days serverless vs dedicated WH and compare credits.', 'CREATE TASK serverless_refresh\n  SCHEDULE = \'USING CRON 0 */4 * * * UTC\'\n  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = \'MEDIUM\'\n  AS CALL refresh_summary();\n\nALTER TASK serverless_refresh RESUME;'),
      item('How do you pass parameters or context into task SQL?', 'Tasks support limited parameterization through SQL and session context.\n• CALL stored procedure with arguments defined in task body.\n• SYSTEM$TASK_RUNTIME_INFO() returns scheduled time for incremental watermark.\n• Session variables set in stored procedure called by task.\n• No native task parameters like Airflow macros—use procedure arguments.\n• {{scheduled_time}} not available in raw SQL task—wrap in procedure.\n\nPattern: procedure reads runtime info and processes WHERE updated_at > last_watermark.', 'CREATE PROCEDURE process_delta()\nRETURNS VARCHAR\nLANGUAGE SQL\nAS $$\n  DECLARE run_ts TIMESTAMP;\n  BEGIN\n    run_ts := (SELECT SCHEDULED_TIME FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())\n               WHERE name = \'DELTA_TASK\' ORDER BY scheduled_time DESC LIMIT 1);\n    MERGE INTO target USING (SELECT * FROM source WHERE updated_at <= :run_ts) ...;\n    RETURN \'OK\';\n  END;\n$$;\n\nCREATE TASK delta_task WAREHOUSE = etl_wh SCHEDULE = \'USING CRON */15 * * * * UTC\' AS CALL process_delta();'),
    ],
    hard: [
      item('Design a task orchestration replacing Airflow for Snowflake-only ETL with 40 tasks.', 'Migrating 40 tasks requires DAG design, error handling, and observability parity with Airflow.\n• Organize into layered DAGs: ingest → silver → gold per domain to limit blast radius.\n• Root tasks per layer with AFTER dependencies; avoid single monolithic 40-node graph.\n• ON_ERROR = SUSPEND_TASK on all tasks; central monitoring task checks TASK_HISTORY.\n• Warehouse per layer: ingest_wh, transform_wh sized independently.\n• Keep Airflow only for cross-system (Salesforce extract) triggers via external task trigger API.\n• Document resume/suspend order in runbook for deployments.\n\nSuccess criteria: match Airflow SLA, reduce orchestration infra cost 50%.', 'CREATE TASK gold_refresh AFTER silver_clean AS CALL build_gold();\n\nSELECT root_task_id, name, state, scheduled_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY\nWHERE scheduled_time > DATEADD(day, -1, CURRENT_TIMESTAMP())\nORDER BY graph_version DESC, name;'),
      item('Troubleshoot a task chain where parent succeeds but child never executes.', 'Child non-execution despite parent success indicates dependency or resume state issues.\n• Verify child is RESUMED: SHOW TASKS—child state must be started.\n• Parent must complete with SUCCEEDED state—not SKIPPED or cancelled with continue.\n• Check child AFTER clause references correct parent name including schema.\n• Graph version: task DDL changes create new graph version—resume new graph.\n• Warehouse suspended on child prevents run—check warehouse state.\n• WHEN condition on child (stream has data) may be false despite parent success.\n\nExecute: SELECT SYSTEM$USER_TASK_CANCEL_ONGOING_TASKS() only if stuck run.', 'SHOW TASKS IN SCHEMA etl;\n\nSELECT name, state, condition, predecessor\nFROM TABLE(INFORMATION_SCHEMA.TASK_DEPENDENTS(TASK_NAME => \'ROOT_TASK\'));\n\nALTER TASK child_task RESUME;'),
      item('Lead incident where runaway task loop consumed monthly warehouse budget.', 'Runaway tasks create credit emergencies requiring immediate suspension and root cause analysis.\n• Scenario: stream-triggered task reschedules every minute; MERGE full table each run.\n• Detect: WAREHOUSE_METERING_HISTORY spike; TASK_HISTORY shows hundreds of runs/hour.\n• Mitigate: ALTER TASK ... SUSPEND; ALTER WAREHOUSE ... SUSPEND IMMEDIATE.\n• Root cause: missing WHEN SYSTEM$STREAM_HAS_DATA guard; or task resumes itself via procedure.\n• Fix: add stream condition, increase schedule interval, optimize MERGE to delta only.\n• Prevent: resource monitor on task warehouse; alert on >N task runs per hour.\n\nPostmortem credit recovery: request Snowflake support goodwill only if platform bug.', 'ALTER TASK runaway_task SUSPEND;\n\nSELECT name, COUNT(*) AS runs, SUM(DATEDIFF(second, scheduled_time, completed_time)) AS total_sec\nFROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(\n  SCHEDULED_TIME_RANGE_START => DATEADD(day, -1, CURRENT_TIMESTAMP())\n))\nGROUP BY 1 ORDER BY runs DESC;\n\nCREATE RESOURCE MONITOR task_wh_limit WITH CREDIT_QUOTA = 200 TRIGGERS ON 100 PERCENT DO SUSPEND;'),
      item('Compare tasks with dynamic tables for pipeline orchestration in 2024+ architectures.', 'Dynamic tables increasingly replace simple task+stream+MERGE patterns.\n• Dynamic tables: declarative TARGET_LAG, automatic dependency graph, refresh scheduling built-in.\n• Tasks: imperative SQL/procedure, full control, complex branching, external integrations.\n• Migration: replace linear stream MERGE chains with dynamic table equivalents.\n• Keep tasks for: CALL procedures, multi-step branching, non-SQL operations, stream WHEN triggers.\n• Hybrid: dynamic tables for transforms; task for export to external systems post-refresh.\n\nArchitecture review: 60% of task DAG may convert to dynamic tables simplifying ops.', 'CREATE DYNAMIC TABLE dt_orders TARGET_LAG = \'10 minutes\' WAREHOUSE = etl_wh AS\nSELECT * FROM raw.orders WHERE status = \'ACTIVE\';\n\nSHOW DYNAMIC TABLES;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY LIMIT 10;'),
    ],
  },
};
