/** Topics 5-11 for snowflake content */
export function item(q, a, cmd) { return { q, a, cmd }; }

export const PART2 = {
  'micro-partitions': {
    easy: [
      item('What is a micro-partition in Snowflake and how big is it?', 'Micro-partitions are Snowflake\'s fundamental unit of data storage and pruning.\n• Each micro-partition holds 50–500 MB of compressed columnar data (not fixed row count).\n• Snowflake automatically splits data into micro-partitions on load—no user configuration.\n• Each partition stores min/max/null-count metadata per column for partition pruning.\n• Queries scan only partitions whose metadata overlaps filter predicates.\n• Partitions are immutable; updates create new partitions and mark old ones for cleanup.\n\nContrast with Hive partitions: Snowflake pruning is automatic metadata-driven, not directory-based.', 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_name = \'ORDERS\';\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'SALES.PUBLIC.ORDERS\', \'(ORDER_DATE)\');'),
      item('How does partition pruning work during query execution?', 'Partition pruning eliminates micro-partitions from the scan plan before reading cloud storage.\n• Optimizer compares filter predicates (e.g., date range) against per-column min/max in each partition.\n• Partitions with non-overlapping ranges are skipped entirely—no I/O cost.\n• Pruning works on equality, range, and IN predicates on columns with good metadata.\n• Functions on columns (YEAR(order_date)) may prevent pruning—filter on raw column instead.\n• Query profile shows partitions scanned vs total partitions.\n\nStrong answers: pruning is why clustering keys matter for large tables with selective filters.', 'SELECT COUNT(*) FROM orders\nWHERE order_date BETWEEN \'2024-01-01\' AND \'2024-01-31\';\n\nSELECT query_id, partitions_scanned, partitions_total, bytes_scanned\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION())\nORDER BY start_time DESC LIMIT 1;'),
      item('Why do too many small micro-partitions hurt performance?', 'Small files and excessive micro-partitions increase metadata overhead and reduce scan efficiency.\n• Each partition has metadata overhead; millions of tiny partitions slow query planning.\n• Causes: frequent small inserts, lack of batching, tables without natural clustering on filter columns.\n• Symptom: high partitions_total, low bytes per partition, long compilation time.\n• Fix: batch loads, COPY INTO larger files, CLUSTER BY or automatic clustering, periodic recluster.\n• Target roughly 100–300 MB per partition for analytical tables.\n\nMonitor via SYSTEM$CLUSTERING_INFORMATION depth and average partition size metrics.', 'INSERT INTO orders SELECT * FROM staging_orders;\n\n-- Prefer batched load:\nCOPY INTO orders FROM @stage FILES = (\'batch_001.parquet\', \'batch_002.parquet\');\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_DATE)\');'),
      item('Explain columnar storage within a micro-partition.', 'Snowflake stores data column-by-column within each micro-partition for compression and projection.\n• Only columns referenced in SELECT are read from storage—column pruning.\n• Same-type adjacent values compress efficiently (run-length, dictionary encoding).\n• SELECT * forces reading all columns—anti-pattern on wide tables.\n• Joins benefit when both tables prune to overlapping partition subsets.\n• VARIANT columns store semi-structured data but with less efficient pruning on nested paths.\n\nETL best practice: separate wide JSON landing from typed narrow analytical tables.', 'SELECT order_id, order_date, amount FROM orders\nWHERE order_date = CURRENT_DATE();\n\n-- Avoid on 200-column table:\n-- SELECT * FROM wide_events WHERE event_date = CURRENT_DATE();'),
    ],
    medium: [
      item('How do you diagnose poor pruning on a large fact table?', 'Poor pruning means queries scan far more partitions than necessary.\n• Compare partitions_scanned to partitions_total in QUERY_HISTORY for typical filter queries.\n• Check if filter column min/max ranges overlap most partitions—data not clustered on filter key.\n• Verify predicates are sargable: avoid functions on column, avoid implicit type casts.\n• Run SYSTEM$CLUSTERING_INFORMATION to see clustering depth and constant overhead.\n• EXPLAIN or query profile identifies pruning effectiveness.\n\nRemediation path: add clustering key, rewrite ETL to load in sorted order, or use Search Optimization Service.', 'SELECT query_id, partitions_scanned, partitions_total,\n       ROUND(partitions_scanned/NULLIF(partitions_total,0)*100,2) AS pct_scanned\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE table_names ILIKE \'%ORDERS%\'\n  AND start_time > DATEADD(day, -7, CURRENT_TIMESTAMP())\nORDER BY bytes_scanned DESC LIMIT 20;\n\nALTER TABLE orders CLUSTER BY (order_date);'),
      item('What impact do DELETE and UPDATE have on micro-partitions?', 'DML operations in Snowflake are copy-on-write at the micro-partition level.\n• UPDATE/DELETE marks affected rows; new micro-partitions written with remaining rows.\n• Old partitions retained in Time Travel until retention expires—storage grows temporarily.\n• Frequent row-level updates fragment partitions and degrade clustering.\n• MERGE is preferred for upsert patterns in ETL over row-by-row UPDATE.\n• Tables with heavy updates may need periodic CLUSTER or table rebuild via CLONE+SWAP.\n\nOLTP-heavy patterns are poor fit for standard Snowflake tables—consider hybrid tables.', 'UPDATE orders SET status = \'CANCELLED\' WHERE order_id = 12345;\n\nDELETE FROM orders WHERE order_date < \'2020-01-01\';\n\nSELECT active_bytes, time_travel_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_name = \'ORDERS\';'),
      item('How do you measure partition skew across a table?', 'Partition skew occurs when data distribution is uneven across micro-partitions.\n• Skewed partitions: one partition much larger than median—causes straggler scan tasks.\n• Causes: monotonically increasing keys without clustering, hot keys in dimension tables.\n• SYSTEM$CLUSTERING_INFORMATION shows average overlaps and partition depth.\n• Query profile may show one worker processing disproportionate data.\n• Mitigation: salt high-cardinality keys, cluster on composite key, redistribute via CTAS.\n\nCompare max partition bytes to median in storage metrics for skew detection.', 'SELECT SYSTEM$CLUSTERING_INFORMATION(\'EVENTS\', \'(user_id)\');\n\nCREATE OR REPLACE TABLE events_rebalanced AS\nSELECT * FROM events ORDER BY event_date, user_id;\n\nALTER TABLE events_rebalanced CLUSTER BY (event_date, user_id);'),
      item('Compare automatic clustering vs manual CLUSTER BY maintenance.', 'Snowflake offers automatic clustering service that reclusters tables in background.\n• CLUSTER BY (col): declares intent; Snowflake rebalances partitions automatically (credit cost).\n• Manual RECLUSTER (legacy) or automatic service maintains depth metric above threshold.\n• Automatic clustering bills credits proportional to data moved during reclustering.\n• Not all tables need clustering—only large tables with selective filters on clustering key.\n• Disable on append-only tables where load order already matches filter pattern.\n\nMonitor clustering_cost in ACCOUNT_USAGE and depth trending down over time.', 'ALTER TABLE orders CLUSTER BY (order_date);\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_DATE)\');\n\nALTER TABLE orders SUSPEND RECLUSTER;'),
    ],
    hard: [
      item('Design storage layout for a 10 billion row events table with 90-day hot query window.', 'At billions of rows, partition pruning and clustering strategy determine query viability.\n• Cluster on (event_date, event_type) for typical dashboard filters.\n• Load data sorted by event_date via staged COPY—natural clustering without heavy recluster cost.\n• Partition-equivalent: micro-partitions align to date ranges through clustering, not Hive paths.\n• Archive >90 days: move to separate table or external Iceberg with cheaper storage class.\n• Search Optimization on event_id for rare point lookups if needed.\n• SLA: p95 scan <5s for last-7-day queries on Large warehouse.\n\nCapacity model: TB/month growth, recluster credits, retention tiers.', 'CREATE TABLE events (\n  event_id VARCHAR,\n  event_date DATE,\n  event_type VARCHAR(50),\n  payload VARIANT\n) CLUSTER BY (event_date, event_type);\n\nCOPY INTO events FROM @stage\nFILE_FORMAT = (TYPE = PARQUET)\nMATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;'),
      item('How would you investigate a sudden doubling of bytes_scanned for a critical report?', 'Regression in bytes scanned indicates pruning failure or query rewrite issue.\n• Compare QUERY_HISTORY before/after deploy: partitions_scanned, query_text diff.\n• Check for new UDF on filter column, implicit cast, OR clause preventing pruning.\n• Verify table did not receive unclustered bulk load diluting metadata overlap.\n• Check if statistics or clustering depth degraded—SYSTEM$CLUSTERING_INFORMATION.\n• Join explosion: new join key causes cartesian expansion—bytes scanned spikes.\n\nRollback query text or table state via Time Travel clone for A/B validation.', 'SELECT query_text, partitions_scanned, partitions_total, bytes_scanned, start_time\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_id IN (\'before_id\', \'after_id\');\n\nCREATE TABLE orders_debug CLONE orders AT (OFFSET => -86400);'),
      item('Lead postmortem where micro-partition explosion caused metadata service slowdown.', 'Extreme partition counts can degrade cloud services metadata operations account-wide.\n• Symptom: all queries slow compilation; high partitions_total on newly loaded table.\n• Cause: streaming micro-inserts every second without batching created millions of tiny partitions.\n• Impact: 2-hour analytics outage; warehouse compute idle while compilation queued.\n• Fix: pause inserts, CTAS into batched table, SWAP, add clustering, enforce batch window in pipeline.\n• Prevent: Snowpipe with larger files, buffer in stream, alert on partitions_total threshold.\n\nAction items: max file size policy, pipeline review, partition count monitoring dashboard.', 'CREATE TABLE events_fixed CLUSTER BY (event_date) AS\nSELECT * FROM events_broken;\n\nALTER TABLE events_broken SWAP WITH events_fixed;\n\nSELECT COUNT(*) AS partition_estimate\nFROM TABLE(INFORMATION_SCHEMA.TABLE_STORAGE_METRICS(\n  \'EVENTS_BROKEN\'));'),
      item('Explain interaction between micro-partitions and result cache invalidation.', 'Result cache keys depend on micro-partition checksums at query execution time.\n• Any DML changing a scanned partition invalidates cached results for queries touching that partition.\n• High-churn tables rarely benefit from result cache—BI on near-real-time data sees constant invalidation.\n• Stable dimension tables and historical fact partitions cache well.\n• Design: separate slowly-changing aggregates (materialized views/dynamic tables) from raw ingest table.\n• USE_CACHED_RESULT = FALSE for benchmarking; TRUE (default) for production cost savings.\n\nArchitect dashboards to query aggregate tables refreshed hourly, not raw events every refresh.', 'ALTER SESSION SET USE_CACHED_RESULT = TRUE;\n\nSELECT region, SUM(revenue) FROM orders\nWHERE order_date >= DATEADD(year, -1, CURRENT_DATE())\nGROUP BY 1;\n\n-- Re-run identical query — check QUERY_HISTORY for credits_used = 0'),
    ],
  },

  'clustering': {
    easy: [
      item('What is table clustering in Snowflake and why use it?', 'Clustering co-locates related rows within micro-partitions to improve partition pruning.\n• DECLARE CLUSTER BY (column_list) on table—Snowflake maintains sort order over time.\n• Best for large tables (TB+) filtered on specific columns (dates, regions, IDs).\n• Without clustering, data layout follows load order which may not match query patterns.\n• Clustering depth metric indicates effectiveness—higher depth means better pruning potential.\n• Automatic clustering service reorders data in background for a credit cost.\n\nNot a replacement for good ETL load order—loading sorted data reduces recluster needs.', 'ALTER TABLE sales CLUSTER BY (sale_date);\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'SALES\', \'(SALE_DATE)\');'),
      item('How do you check clustering quality on a table?', 'SYSTEM$CLUSTERING_INFORMATION provides clustering health metrics.\n• average_depth: lower is better; target typically <4 for good pruning on large tables.\n• average_overlaps: partition overlap count—lower means cleaner boundaries.\n• cluster_by_keys: active clustering columns.\n• Notes field explains if reclustering is in progress or suspended.\n• Query QUERY_HISTORY partitions_scanned ratio validates real-world impact.\n\nCheck after large bulk loads—depth often spikes until recluster completes.', 'SELECT SYSTEM$CLUSTERING_INFORMATION(\'SALES.PUBLIC.ORDERS\', \'(ORDER_DATE)\');\n\nSELECT partitions_scanned, partitions_total\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nWHERE query_text ILIKE \'%orders%\'\nORDER BY start_time DESC LIMIT 5;'),
      item('What columns should you choose for a clustering key?', 'Clustering key selection should match the most selective filter columns in production queries.\n• High-cardinality date/timestamp columns are common choices for fact tables.\n• Composite keys (region, date) when queries always filter both dimensions.\n• Avoid clustering on low-cardinality alone (boolean flags)—limited pruning benefit.\n• Do not cluster on columns rarely used in WHERE clauses—wasted recluster credits.\n• Maximum practical keys: typically 3–4 columns; more keys increase maintenance cost.\n\nInterview approach: ask about top 5 production queries and their filter columns first.', 'ALTER TABLE events CLUSTER BY (event_date, region);\n\n-- Query pattern that benefits:\nSELECT * FROM events\nWHERE event_date >= \'2024-06-01\' AND region = \'US\';'),
      item('Does clustering eliminate the need for partition pruning knowledge?', 'Clustering enhances pruning but does not remove need to write sargable queries.\n• Pruning still requires filter predicates compatible with min/max metadata.\n• Clustering improves overlap quality so fewer partitions match broad scans.\n• Functions on clustered columns (TO_DATE(varchar_col)) may still block pruning.\n• Joins benefit when both sides cluster on join key—co-located micro-partitions possible.\n• Engineers must still understand EXPLAIN and query profile metrics.\n\nClustering is physical optimization; logical SQL quality remains essential.', 'SELECT * FROM orders WHERE order_date = \'2024-06-15\';\n\n-- Bad for pruning:\n-- SELECT * FROM orders WHERE YEAR(order_date) = 2024;'),
    ],
    medium: [
      item('How do you balance clustering cost vs query performance improvement?', 'Clustering incurs background recluster credits—justify with measured query savings.\n• Baseline: QUERY_HISTORY bytes_scanned and elapsed time before clustering.\n• Enable clustering; monitor SYSTEM$CLUSTERING_INFORMATION depth over 1–2 weeks.\n• Compare bytes_scanned after depth stabilizes—target 50%+ reduction for justified tables.\n• Review AUTOMATIC_CLUSTERING_HISTORY for credits spent on reclustering.\n• Suspend recluster on tables where depth is acceptable and queries are fast enough.\n\nROI formula: (compute credits saved monthly) > (recluster credits + storage overhead).', 'SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.AUTOMATIC_CLUSTERING_HISTORY\nWHERE start_time > DATEADD(day, -30, CURRENT_TIMESTAMP());\n\nALTER TABLE orders SUSPEND RECLUSTER;'),
      item('What happens to clustering when you bulk load unsorted data?', 'Unsorted bulk loads temporarily degrade clustering depth until reclustering catches up.\n• New micro-partitions may have wide min/max ranges overlapping existing data.\n• Queries during this window scan more partitions—temporary performance regression.\n• Mitigation: pre-sort files before COPY, load during maintenance window, temporarily upsize warehouse.\n• PIPE loads with Snowpipe may continuously degrade clustering—schedule recluster or batch files.\n• Consider separate staging table sorted CTAS into clustered production table.\n\nPattern: LOAD staging → CREATE TABLE prod_new AS SELECT * ORDER BY key → SWAP.', 'COPY INTO orders FROM @stage;\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_DATE)\');\n\nCREATE TABLE orders_sorted CLUSTER BY (order_date) AS\nSELECT * FROM orders_staging ORDER BY order_date;'),
      item('Compare CLUSTER BY with Search Optimization Service for point lookups.', 'Different tools solve different access patterns on large tables.\n• CLUSTER BY: optimizes range scans and equality on leading clustering columns across partitions.\n• Search Optimization Service (SOS): builds auxiliary search structures for point lookups (single row by ID).\n• SOS costs storage and maintenance credits; best for "needle in haystack" on billion-row tables.\n• CLUSTER BY insufficient when equality filter column has extreme cardinality spread across all partitions.\n• Can use both: cluster on date, SOS on transaction_id within recent partitions.\n\nEvaluate with query patterns: dashboards need clustering; API lookup by PK needs SOS.', 'ALTER TABLE transactions ADD SEARCH OPTIMIZATION ON EQUALITY(transaction_id);\n\nSELECT * FROM transactions WHERE transaction_id = \'TXN-987654321\';\n\nSHOW SEARCH OPTIMIZATION ON transactions;'),
      item('How do you change clustering keys on a production table?', 'Changing clustering keys requires ALTER and accepts temporary depth degradation.\n• ALTER TABLE ... CLUSTER BY (new_keys) starts new reclustering trajectory.\n• Old partition layout persists until background service rewrites partitions.\n• Safer approach: CREATE TABLE new CLONE/CTAS with new clustering → validate → SWAP.\n• Schedule during low-traffic window; monitor depth and query metrics during transition.\n• Update downstream documentation and ETL load sort order to match new keys.\n\nSWAP approach enables instant rollback if performance regresses.', 'ALTER TABLE orders CLUSTER BY (customer_id, order_date);\n\n-- Safer migration:\nCREATE TABLE orders_v2 CLUSTER BY (customer_id, order_date) AS SELECT * FROM orders;\nALTER TABLE orders SWAP WITH orders_v2;'),
    ],
    hard: [
      item('Design clustering strategy for a multi-tenant table with 10K tenants and date-range queries.', 'Multi-tenant clustering must balance tenant isolation in partition layout with date pruning.\n• Option A: cluster by (tenant_id, event_date) if queries always filter tenant first.\n• Option B: separate table per tenant tier (enterprise vs SMB) with different clustering.\n• Row access policies do not affect physical layout—clustering must match query filter order.\n• Hot tenants with massive row counts may skew partitions—monitor per-tenant scan metrics.\n• Consider tenant_id hash salt for largest tenants to spread partition load.\n\nLoad test top 10 tenants\' typical queries; measure partitions_scanned per tenant.', 'ALTER TABLE tenant_events CLUSTER BY (tenant_id, event_date);\n\nSELECT tenant_id, COUNT(*) FROM tenant_events\nWHERE tenant_id = \'T-100\' AND event_date >= \'2024-06-01\'\nGROUP BY 1;'),
      item('Lead optimization project when clustering depth stuck above 8 despite months of reclustering.', 'Persistently high depth indicates fundamental mismatch between load pattern and clustering key.\n• Diagnose: load order random by key; continuous small inserts; wrong clustering column choice.\n• Analyze top queries—maybe cluster key should be (date, region) not just (date).\n• Nuclear option: CTAS with ORDER BY clustering keys, SWAP, enforce sorted loads going forward.\n• Evaluate if table is too wide for clustering benefit—archive old partitions to separate table.\n• Cost: recluster credits exceeding savings—suspend and accept scan cost or redesign.\n\nPresent data-driven recommendation to leadership with cost/performance trade-off curves.', 'CREATE TABLE orders_rebuilt CLUSTER BY (order_date) AS\nSELECT * FROM orders ORDER BY order_date;\n\nALTER TABLE orders SWAP WITH orders_rebuilt;\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_DATE)\');'),
      item('How does clustering interact with Time Travel storage for frequently updated tables?', 'Clustering maintenance and DML both generate new micro-partitions affecting storage.\n• Each UPDATE creates new partitions; old versions retained in Time Travel.\n• Reclustering rewrites partitions—both old and new versions consume storage temporarily.\n• High-churn + clustering = storage and credit amplification.\n• Mitigation: shorter retention on staging, MERGE batch patterns, separate current-state table from history.\n• SCD Type 2 history tables may cluster on (business_key, valid_from) for temporal queries.\n\nModel storage: active + time_travel + failsafe growth rate with clustering enabled vs disabled.', 'ALTER TABLE order_history SET DATA_RETENTION_TIME_IN_DAYS = 7;\n\nALTER TABLE order_history CLUSTER BY (order_id, valid_from);\n\nSELECT active_bytes, time_travel_bytes, failsafe_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS\nWHERE table_name = \'ORDER_HISTORY\';'),
      item('Explain when to drop clustering entirely and rely on natural load order.', 'Clustering is not free—sometimes natural load order is sufficient.\n• Append-only time-series loaded in chronological order often has excellent natural clustering on timestamp.\n• Adding CLUSTER BY on same column triggers unnecessary recluster credits.\n• Validate: depth already <2 without declared clustering key.\n• Drop clustering: ALTER TABLE ... DROP CLUSTERING KEY; suspend recluster.\n• Re-evaluate if query patterns change to filter on different columns.\n\nDocument decision in table catalog: "natural clustering via ordered Snowpipe ingest."', 'SELECT SYSTEM$CLUSTERING_INFORMATION(\'EVENTS\', \'(EVENT_TS)\');\n\nALTER TABLE events DROP CLUSTERING KEY;\n\nALTER TABLE events SUSPEND RECLUSTER;'),
    ],
  },

  'query-optimization': {
    easy: [
      item('What metrics in QUERY_HISTORY indicate an expensive query?', 'QUERY_HISTORY exposes resource consumption metrics for every executed query.\n• bytes_scanned: primary cost driver—data read from storage regardless of rows returned.\n• partitions_scanned vs partitions_total: pruning effectiveness ratio.\n• total_elapsed_time: end-to-end latency including compilation and queue time.\n• credits_used_cloud_services + credits_used_compute_storage: billing impact.\n• rows_produced vs rows_inserted: detect accidental full table scans returning few rows.\n\nStart optimization triage with highest bytes_scanned queries in last 7 days.', 'SELECT query_id, query_text, bytes_scanned,\n       partitions_scanned, partitions_total,\n       total_elapsed_time/1000 AS elapsed_sec\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nORDER BY bytes_scanned DESC LIMIT 20;'),
      item('How does column pruning reduce query cost?', 'Column pruning reads only columns referenced in the query from micro-partitions.\n• SELECT col_a, col_b reads two columns\' compressed data, not entire wide row.\n• SELECT * on 200-column table scans all columns—massive bytes_scanned increase.\n• Joins prune columns per table independently based on SELECT and JOIN keys.\n• CREATE VIEW with explicit column list encourages narrow queries from BI tools.\n• VARIANT/OBJECT columns are wide—extract needed fields early in ETL to typed columns.\n\nRule: never SELECT * in production ETL or BI semantic layers.', 'SELECT order_id, order_date, amount FROM orders\nWHERE order_date >= CURRENT_DATE() - 7;\n\n-- Compare bytes_scanned with:\n-- SELECT * FROM orders WHERE order_date >= CURRENT_DATE() - 7;'),
      item('What is a result cache hit and how do you identify one?', 'Result cache serves identical query results without re-executing the scan.\n• Cache hit: query returns instantly with 0 or minimal credits_used_compute.\n• Requirements: same query text, same warehouse, underlying partitions unchanged.\n• QUERY_HISTORY may show bytes_scanned = 0 on cache hit.\n• 24-hour cache lifetime; great for repeated dashboard queries.\n• ALTER SESSION SET USE_CACHED_RESULT = FALSE to bypass for testing.\n\nDesign repeated queries with stable SQL text—avoid random comments or timestamps in SQL string.', 'ALTER SESSION SET USE_CACHED_RESULT = TRUE;\n\nSELECT region, COUNT(*) FROM customers GROUP BY region;\n\n-- Run twice; check second execution:\nSELECT query_id, bytes_scanned, credits_used_compute_storage\nFROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())\nORDER BY start_time DESC LIMIT 2;'),
      item('Why should you avoid using functions on filter columns?', 'Functions on filter columns prevent micro-partition pruning in most cases.\n• WHERE YEAR(order_date) = 2024 forces evaluation on every row—scans all partitions.\n• Better: WHERE order_date BETWEEN \'2024-01-01\' AND \'2024-12-31\'.\n• Same issue: UPPER(email) = \'X\' vs email = \'x\' with consistent casing in ETL.\n• Implicit casts (WHERE varchar_col = 123) may also block pruning.\n• Exception: some optimizations may still prune—always verify in query profile.\n\nCode review checklist: sargable predicates on clustered columns.', 'SELECT COUNT(*) FROM orders\nWHERE order_date >= \'2024-01-01\' AND order_date < \'2025-01-01\';\n\n-- Avoid:\n-- SELECT COUNT(*) FROM orders WHERE YEAR(order_date) = 2024;'),
    ],
    medium: [
      item('How do you optimize a query with a large table join to a small dimension?', 'Join optimization leverages broadcast when one table is small enough to fit in memory.\n• Snowflake auto-broadcasts small tables (< ~250 MB default threshold) to all workers.\n• Hint: USE HASH(table) or query profile shows BROADCAST JOIN in plan.\n• If auto-broadcast fails, increase BROADCAST JOIN threshold session parameter cautiously.\n• Large-large joins require sort-merge or hash join with shuffle—both sides must prune well.\n• Pre-aggregate dimension if only subset of columns needed in join.\n\nEnsure stats are current; stale stats may choose suboptimal join order.', 'ALTER SESSION SET JOIN_COLLISION_RATIO = 0.5;\n\nSELECT /*+ BROADCAST(dim) */ f.*, d.category\nFROM fact f\nJOIN dim d ON f.category_id = d.id\nWHERE f.sale_date >= \'2024-06-01\';\n\nSELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_SESSION())\nORDER BY start_time DESC LIMIT 1;'),
      item('What is spilling and how do you detect memory pressure in queries?', 'Spilling occurs when intermediate results exceed available warehouse memory during sorts/joins.\n• Query profile shows bytes spilled to local or remote storage—major latency increase.\n• Causes: oversized joins, DISTINCT on high-cardinality columns, insufficient warehouse size.\n• Fix: increase warehouse size one step, reduce join width, pre-filter before join, break into temp tables.\n• Repeated spills on same query justify permanent warehouse upsize or query rewrite.\n• Monitor QUERY_ACCELERATION and spill metrics in QUERY_HISTORY extended fields.\n\nWarehouse memory scales with size; X-Large has 4× memory of Large—not linear to cost always worth it.', 'SELECT query_id, bytes_spilled_to_local_storage,\n       bytes_spilled_to_remote_storage\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE bytes_spilled_to_remote_storage > 0\n  AND start_time > DATEADD(day, -7, CURRENT_TIMESTAMP());\n\nALTER WAREHOUSE analytics_wh SET WAREHOUSE_SIZE = \'LARGE\';'),
      item('How do materialized views accelerate queries and what are their limitations?', 'Materialized views store precomputed results incrementally maintained by Snowflake.\n• Query rewriter automatically routes compatible queries to MV when beneficial.\n• Best for repeated aggregations on large base tables with predictable patterns.\n• Limitations: not all SQL constructs supported; maintenance lag during heavy base table DML.\n• MV storage adds cost; stale MV if base table changes faster than refresh.\n• Monitor MATERIALIZED_VIEW_REFRESH_HISTORY for failures and duration.\n\nAlternative: Dynamic Tables offer more flexible transformation pipelines with explicit refresh SLAs.', 'CREATE MATERIALIZED VIEW mv_daily_sales AS\nSELECT sale_date, region, SUM(amount) AS total\nFROM sales GROUP BY 1, 2;\n\nSELECT * FROM mv_daily_sales WHERE sale_date >= \'2024-06-01\';\n\nALTER MATERIALIZED VIEW mv_daily_sales REFRESH;'),
      item('How do you use QUERY_TAG for performance troubleshooting at scale?', 'QUERY_TAG attaches metadata to queries for filtering in ACCOUNT_USAGE views.\n• Set per session: ALTER SESSION SET QUERY_TAG = \'tableau:dashboard_sales\'.\n• ETL frameworks set tag per job/run for attribution.\n• Filter QUERY_HISTORY by query_tag to isolate BI vs ETL performance regressions.\n• Combine with user_name and warehouse_name for full context.\n• Standardize tag format: app:object:version for parseable dashboards.\n\nEnforce via network policy or login hook setting tag for service accounts.', 'ALTER SESSION SET QUERY_TAG = \'etl:nightly_orders:v2\';\n\nSELECT query_tag, AVG(total_elapsed_time) AS avg_ms,\n       SUM(bytes_scanned) AS total_bytes\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE start_time > DATEADD(day, -7, CURRENT_TIMESTAMP())\n  AND query_tag LIKE \'etl:%\'\nGROUP BY 1 ORDER BY total_bytes DESC;'),
    ],
    hard: [
      item('Design a query governance framework to prevent runaway scans in a self-service BI environment.', 'Self-service BI needs guardrails without blocking legitimate analysis.\n• Statement timeouts: STATEMENT_TIMEOUT_IN_SECONDS per role or warehouse.\n• Resource monitors on BI warehouses with NOTIFY then SUSPEND thresholds.\n• Row limits in BI tool + semantic layer pre-aggregated models.\n• Automated alert on queries scanning >1 TB without query_tag approval.\n• Query acceleration and result cache for approved dashboard SQL patterns.\n• Education: query profile review office hours for top bytes_scanned users.\n\nTechnical + process: blocked query log reviewed weekly; exceptions via ticket for research queries.', 'ALTER WAREHOUSE bi_wh SET STATEMENT_TIMEOUT_IN_SECONDS = 300;\n\nCREATE RESOURCE MONITOR bi_guard WITH CREDIT_QUOTA = 1000\n  FREQUENCY = MONTHLY TRIGGERS ON 90 PERCENT DO NOTIFY;\n\nALTER WAREHOUSE bi_wh SET RESOURCE_MONITOR = bi_guard;'),
      item('How would you debug a 50x query regression after a Snowflake version upgrade?', 'Version upgrade regressions require systematic before/after comparison.\n• Identify affected query_ids in QUERY_HISTORY around upgrade timestamp.\n• Compare query profiles: join type changes, pruning differences, new optimizer behavior.\n• Test in pre-upgrade clone (Time Travel) vs current with identical warehouse and data.\n• Check release notes for optimizer changes affecting your SQL patterns.\n• Open Snowflake support case with query_id pair if platform regression suspected.\n• Temporary mitigation: rewrite query, add MV, or pin warehouse size up.\n\nMaintain upgrade test suite: top 50 queries with expected bytes_scanned bounds.', 'SELECT query_id, query_text, bytes_scanned, start_time, release_version\nFROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY\nWHERE query_hash = \'abc123def\'\nORDER BY start_time DESC LIMIT 10;\n\nALTER SESSION SET USE_CACHED_RESULT = FALSE;'),
      item('Lead optimization of a 3-hour MERGE statement processing 500M rows nightly.', 'Large MERGE optimization requires staging strategy, clustering, and warehouse sizing.\n• Ensure join keys match clustering on both target and source staging table.\n• Filter source to changed rows only—delta detection via stream or timestamp watermark.\n• Right-size warehouse: test L vs XL measuring spill and duration; multi-cluster rarely helps single MERGE.\n• Break into batch MERGE by date partition if predicate allows independent commits.\n• Use MATCHED / NOT MATCHED clauses efficiently; avoid unnecessary column updates.\n• Monitor lock contention if concurrent readers during MERGE—schedule off-peak.\n\nTarget: <45 min MERGE via 80% source row reduction and clustering alignment.', 'MERGE INTO prod.orders t\nUSING staging.orders_delta s ON t.order_id = s.order_id\nWHEN MATCHED AND s.updated_at > t.updated_at THEN UPDATE SET ...\nWHEN NOT MATCHED THEN INSERT ...;\n\nSELECT SYSTEM$CLUSTERING_INFORMATION(\'ORDERS\', \'(ORDER_ID)\');'),
      item('Explain trade-offs between pre-aggregation tables, dynamic tables, and materialized views.', 'Three patterns solve repeated aggregation with different ops models.\n• Manual pre-agg table + task: full control, explicit refresh schedule, custom logic, ops burden.\n• Materialized view: automatic query rewrite, incremental maintenance, SQL limitations.\n• Dynamic table: declarative pipeline, dependency graph, TARGET_LAG SLA, replaces many task chains.\n• Choose MV for simple rollups queried variably; Dynamic Tables for multi-stage pipelines.\n• Cost: compare refresh credits + query savings across options in PoC.\n\nMigration path: task-maintained summary → dynamic table with equivalent SELECT for simpler lineage.', 'CREATE DYNAMIC TABLE dt_daily_kpis\n  TARGET_LAG = \'1 hour\'\n  WAREHOUSE = etl_wh AS\nSELECT order_date, SUM(amount) AS revenue FROM orders GROUP BY 1;\n\nSELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.DYNAMIC_TABLE_REFRESH_HISTORY\nWHERE name = \'DT_DAILY_KPIS\' ORDER BY refresh_start_time DESC;'),
    ],
  },
};
